### ISSUE TITLE
build @64bit for MacOS 10.15 Catalina that cannot execute 32bit app

### ISSUE THREAD

**Issue by efa** [XQuartz/XQuartz#10]
hi,
we need a build @64bit of XQuartz

**Comment by IComplainInComments** [comment]
Lastest version already contains a 64bit build.

**Comment by efa** [comment]
32 bit applications should be run with 32 bit version or can be used with 64 bit version?

**Comment by IComplainInComments** [comment]
> 32 bit applications should be run with 32 bit version or can be used with 64 bit version?

32bit applications cannot run on Catalina, no matter if its a Aqua Drawn app or an X11 app. In this case its not the problem of a 64bit X11 not allowing 32bit applications to run, its the fact Catalina does not allow 32bit applications to run anywhere on the system.

**Comment by efa** [comment]
is there an already built 64 bit version of Xquartz, in DMG format?
The one on:
https://www.xquartz.org/
seems 2.7.11  from 2016 and is 32 bit only

**Comment by jeremyhu** [comment]
2.7.11 is absolutely not 32-bit only.

**Comment by efa** [comment]
sorry, I haven't a macOS, I'm cross-compiling from Linux to macOS, and asking to some macOS friend users to test my GTK binaries, and I got feedback of errors, but I know about nothing of macOS.

Can I ask you to confirm the following statement:
0) GTK backend for Quartz is buggy and feature incomplete, seems it is on rewrite: https://wiki.gnome.org/Projects/GTK/OSX
1) current GTK stack work well using X backend on macOS
2) using Xquartz 2.7.11 on recent macOS (10.14  Mojave and next, so 64 bit only), building for 64 bit and GTK with X backend should work

thank you
and sorry again for noise

**Comment by jeremyhu** [comment]
My understanding is that the Quartz backend has matured to the point of being production ready.  I don't really know.  You should ask GTK folks.

**Comment by efa** [comment]
I can confirm this, in the past month (so after my last post) I cross-compiled GTK using Quarz backend (64 bit) and work well (2.x too).
Anyway it is of interest to have a XQuartz backend and this server, in case you need network display export for remote operations. Thank you.
