### ISSUE TITLE
Multi-monitor support could be improved

### ISSUE THREAD

**Issue by rogeriomm** [XQuartz/XQuartz#101]
Running XQuartz on Mac OS big sir 11.2.2/Intel with 4 monitors, XQuartz terminal application windows can be moved to any monitor, X11 windows created using "ssh -X" opens only on monitor number 4(not my primary monitor, it's 50" TV), it's not possible to drag the open app to another monitor

**Comment by jeremyhu** [comment]
Yeah, Xinerama support is not quite where it should be, and is likely not to get much better.  This would not be an issue if we had a compositing window manager.  It'd be nice if someone could pick up and fomplete that project =/

**Comment by jeremyhu** [comment]
#92
