### ISSUE TITLE
port is the default when running XQuartz on MacBook?

### ISSUE THREAD

**Issue by wonkyungup** [XQuartz/XQuartz#104]
Hello, I'm a beginner developer.
If you don't mind, may I know which port is the default when running XQuartz on MacBook?

It doesn't open with 6000 ports, but another port seems to open.

By any chance, can you do passive mode?

**Comment by jeremyhu** [comment]
XQuartz does not listen over TCP by default.  You need to enable that in its Preferneces.  6000 would be used if available and then increasing by 1 until it finds an available port.
