### ISSUE TITLE
Remote IGLX clients not working correctly with XQuartz-2.8.0_rc2

### ISSUE THREAD

**Issue by cfdguru** [XQuartz/XQuartz#107]
When I login to a remote server with "ssh -X", some of the X11 apps do not function correctly on my Mac running High Sierra. While gnuplot seems to display and function correctly when displaying plots, other applications such as Paraview-4.4 display the window but none of the GUI buttons functions and the viewer display portion of the window has the same color as the GUI background when it should display a bluish-grey background. Another applications that now fails to functions properly is CFD-GEOM (a 3D meshing application). An in-house developer version on an older code base (CFD-GEOM2004), the application window displays and functions correctly, except the view window remains the color of the background buttons instead of the expected black background and nothing is visible in the viewer. In a new version of the code (CFD-GEOM13), the application starts with the file selection screen, but when a valid file or create new file is selected, the following error occurs on the command line: HOST: attempting connection on port 21234
HOST: made connection on port 21234
SPLASH: updating window contents
continuing CFD-HOST...
loading plugins...
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error: code 2 major 149 minor 3: BadValue (integer parameter out of range for operation).
X Error: code 161 major 149 minor 5: GLXBadContext.
X Error: code 0 major 149 minor 26: 0.
![gnuplot-4 6p2_centos7 5](https://user-images.githubusercontent.com/16901452/109902946-c04e6580-7c60-11eb-823f-d4a3552508f5.png)
![CFD-GEOM2004_dev](https://user-images.githubusercontent.com/16901452/109902958-c80e0a00-7c60-11eb-99a6-56c21daf6a4f.png)

**Comment by cfdguru** [comment]
Yes, it worked fine in the previous version (which may have been 2.7.10_rc2 or 2.7.11). However, as soon as I installed the 2.8.0_rc2, it stopped working correctly. Will I need to restart XQuartz or reboot after the defaults write command to get it to take effect?

**Comment by jeremyhu** [comment]
You'll need to relaunch XQuartz after setting the defaults.

**Comment by jeremyhu** [comment]
Also, please report if the solution mentioned in #54 works for you.

**Comment by matthiasschroder** [comment]
As I encounter the same issue, can you let me know which solution from https://github.com/XQuartz/XQuartz/issues/54 you mean?

**Comment by jeremyhu** [comment]
> As I encounter the same issue, can you let me know which solution from #54 you mean?

The second comment there:

> For me it doesn't hang and seems to work, but with a bit of a hack. I've modified a bit line 117 in /opt/X11/bin/startx:
> 
>     defaultserverargs="$defaultserverargs +iglx +extension GLX"
> 
> and issued then defaults write org.xquartz.X11 enable_iglx -bool true

**Comment by matthiasschroder** [comment]
OK, thanks. Yes, that does it for me. Tested on macOS 11.2.3 Intel and M1 :)

**Comment by jeremyhu** [comment]
Ok, let's dupe this to #54 then.  I don't see why that would be needed.

**Comment by cfdguru** [comment]
I finally had a chance to try #54 and everything works fine now!

Thanks,
Chris
