### ISSUE TITLE
on macOS Big Sur /bin/ls does not work for Desktop directory

### ISSUE THREAD

**Issue by weissdorn** [XQuartz/XQuartz#109]
/bin/ls /Users/myname/Desktop typed from an xterm is failing: 
ls: Desktop: Operation not permitted
(macOS Big Sur 11.2.1, MacBook Pro (13-inch, M1, 2020), (XQuartz 2.8.0_rc1)
The same command typed from the terminal application just works fine.

This problem is specific to the Desktop; other files and directories are fine; when setting up another user
on the MacBook and trying to "ls" the Desktop in this new account, the problem still occurs. 

It is possible to "cd" to Desktop, but then "ls" still fails:
myname> ls -lat
ls: .: Operation not permitted

Any standard access to Desktop, e.g. using the Finder Application to copy or remove files 
(working with the trackpad) works okay.
Thanks for looking into this
weissdorn

**Comment by jeremyhu** [comment]
#6
