### ISSUE TITLE
My app using XQuartz fails to connect to display :0 often

### ISSUE THREAD

**Issue by RoyceTheBiker** [XQuartz/XQuartz#11]
I have an old, time tracking program that was made to run on Linux. I found XQuartz when my company switched me to a Mac OS laptop. Most of the time XQuartz works but some times it fails with a magic cookie error. The only workaround is to fully close XQuartz and relaunch it.

```
Invalid MIT-MAGIC-COOKIE-1 keycouldn't connect to display ":0"
```
Any hints as to how to fix this?

**Comment by LIFanAr** [comment]
same question. hope to be answered. THX

**Comment by espoelstra** [comment]
Is it possible your IP changed? See this note from the XQuartz Preferences.

![image](https://user-images.githubusercontent.com/7798975/86304115-7c87f580-bbd3-11ea-87b2-21557ace916c.png)
