### ISSUE TITLE
XQuartz-2.8.0_rc2 does not set working directory when X clients are launched via ~/.xinitrc

### ISSUE THREAD

**Issue by ballapete** [XQuartz/XQuartz#114]
When I launch GNU Emacs from ~/.xinitrc its working directory is / while the simultaneously launched XTerm's shell has it in ~.

When I launch GNU Emacs from the Applications menu its working directory is ~.

**Comment by ballapete** [comment]
This is a bit strange: The behaviour described is true only for Big Sur, macOS 11.2.2. On High Sierra, macOS 10.13.6, it's the very opposite! Could be it's caused by Launch Service?

**Comment by jeremyhu** [comment]
No, LaunchServices isn't involved here.
