### ISSUE TITLE
Need xhost+ on ssh forwarded connections

### ISSUE THREAD

**Issue by bferrell** [XQuartz/XQuartz#116]
when connecting to a linux system:

ssh -X hostname

or 

ssh -Y hostname

The following message is seen:

Unable to init server: Broadway display type not supported: localhost:10.0
Error: cannot open display: localhost:10.0

xquartz is NOT automatically launched.  When xquartz is launched manually before or after connecting the following message is seen:

Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Broadway display type not supported: localhost:10.0
Error: cannot open display: localhost:10.0

ssh connection is then dropped and xhost+ is executed on the OS X system.

ssh connection made and remote X application connects and works

executing xhost + without manually launching xquartz does not launch xquartz automatically.

**Comment by jeremyhu** [comment]
You seem to have misconfigured the system.  You should absolutely not be using `xhost +` as that is a security risk.  In fact, we disable TCP connections by default.  I suggest reaching out on the x11-users mailing list for help.

**Comment by bferrell** [comment]
The point is that a forwarded X connection does NOT auto launch on Big Sur.

As to a misconfigured system, this is a fresh install of Big Sur with NO additional configuration or changes.

For the record, this works on Mojave and High Sierra as expected.

It is NOT a generic x11 issue, but unique to OS X/Big Sur - xquartz

**Comment by jeremyhu** [comment]
I have a Ubuntu VM on my local system.

I don't have XQuartz running.

I opened Terminal and ran:

    local $ echo $DISPLAY
    /private/tmp/com.apple.launchd.drREC61dJT/org.xquartz:0
    local $ ssh <VM's IP>
    vm $ echo $DISPLAY
    localhost:10.0
    vm $ xterm

XQuartz.app launched, and the xterm appeared.  Please see https://www.xquartz.org/FAQs.html for help debugging ssh forwarding issues, and reach out on the mailing list if you need more support as there are plenty of folks there willing to help.

**Comment by bferrell** [comment]
Thank you!  

MacPorts had set the DISPLAY variable in .zshrc of unix$DISPLAY and .zprofile DISPLAY:0 on my macbook pro

With those commented, xquartz operated as it has on earlier versions of OS X

**Comment by jeremyhu** [comment]
Yeah, there was a bug in older MacPorts installers that thought macOS 11.0 was older than 10.6.
