### ISSUE TITLE
Preferences documentation

### ISSUE THREAD

**Issue by e-gaulue** [XQuartz/XQuartz#117]
Hi all,

Is preferences pane options describe somewhere?

While written in my own language input options are still not clear to me.
![Capture d’écran 2021-03-12 à 12 25 48](https://user-images.githubusercontent.com/4291874/110934361-340e0380-832e-11eb-88bd-bb4c3a0e2ac0.png)

I suppose those options apply when the application is running (frontmost). What htey do?

I think I understand the fourth one, but second and third are still not clear to me.

Regards,

**Comment by jeremyhu** [comment]
The second one updates the X11 keymap when the macOS keymap changes (ie: if you switch keyboard layouts in macOS's System Preferences).

The third one turns results in key equivalents being sent to X11 rather than handled by AppKit (ie: cmd-q).  I just tried turning it off, and it seems to not be working (at least on Big Sur).  I'll dig into that.

**Comment by e-gaulue** [comment]
Hi,

Maybe it's just a translation trouble.

I didn't see the english version but for french for the second one "Suivre la disposition..." would be more explicit than "Utiliser la disposition...". 

For the 3rd, I understand it's something to bypass AppKit (so OS X default keyboard shortcut), and directly send the corresponding keys to X11. I agree with the fact, nothing change on Mojave too.

It's just a shame we do not have an option to exchange ctrl and cmd. I found the solution on the web. It looks we are a lot looking for such an option and relying on modmap. Could be great if in Xquartz as ALT_L and ALT_R.

Regards,

**Comment by jeremyhu** [comment]
Yep, .Xmodmap is really the way to handle that.

Regarding the translation, would you be able to provide updated french localization?  You can open the nib in Xcode, edit the strings, and then send me a PR.  See https://github.com/XQuartz/xorg-server/tree/master/hw/xquartz/bundle/Resources/French.lproj
