### ISSUE TITLE
Matlab problem (similar to <https://github.com/XQuartz/XQuartz/issues/31>)

### ISSUE THREAD

**Issue by Huiping-Huang** [XQuartz/XQuartz#118]
I am using XQuartz 2.8.0_rc1, when I open Matlab, there are two issues. The first one is the Matlab window is dark; the second one is shadow exist in the desktop. Please see attached.

![IMG_0244](https://user-images.githubusercontent.com/61904156/110948150-49d8f400-8341-11eb-9845-39274293d833.jpg)

**Comment by jeremyhu** [comment]
Ok, then closing this as a duplicate.
