### ISSUE TITLE
Xquartz / catalina / change shell

### ISSUE THREAD

**Issue by saracazzoli** [XQuartz/XQuartz#12]
Hi, 
I am starting to use MAC Os with Catalina.
I would like to use the bash shell instead of the zsh shell.
I successfully change the shell in "normal terminal windows" with: chsh -s /bin/bash.
However, in Xquartz this command does not work (not even with super user permission) and it kept using the zsh shell.  How can I fix this ?
I am going to customize my set up in the .profile/.bashrc and not in the .zprofile or .zshrc, so I prefer to avoid any possible conflicts that could possibly arise when using two shells at the same time. Thanks!

**Comment by mathieu-lemire** [comment]
I have the same issue with Catalina. In XQuatrz, the command

chsh -s /bin/bash 
will return:
chsh: no changes made

whereas in Terminal, the change to bash is made.

**Comment by jeremyhu** [comment]
Please report the bug to Apple via Feedback Assistant.

**Comment by pdelong42** [comment]
Hi @jeremyhu ,

I'm not sure how filing a bug with Apple will help.  Both of the people above reported that the problem only manifests when they're in XQuartz, and not when they're in Terminal.app (also, what incentive does Apple have to fix a bug that only affects users of X11).

I'm also having the same problem:  Running XQuartz 2.8.1 (xorg-server 1.20.11) on macOS 11.4, my xterm will continue to spawn /bin/zsh, even though I switched to /bin/bash using chsh and restarted X11 (but Terminal.app will use /bin/bash, as it's supposed to).

 - Paul
