### ISSUE TITLE
[Big Sur]{XQuartz 2.8.0_rc3] Copy/Paste in an xterm pre- and post-pends gunk

### ISSUE THREAD

**Issue by randyqx** [XQuartz/XQuartz#123]
in an xterm, i double left click select `75F2C46EF1697D9292761465CCCC05ECB83A02ED` and then middle click paste it and get `00~75F2C46EF1697D9292761465CCCC05ECB83A02ED01~`

**Comment by randyqx** [comment]
it's likely the paste operation.  if i do the select/copy using c-w from an emacs frame, the paste has the same rubbish.  fwiw, the paste into an emacs frame does not have the rubbish.

**Comment by jeremyhu** [comment]
Do you see this in other X11 apps or just xterm?

What aplication is the source of the data?

**Comment by randyqx** [comment]
only pasting into xterms.  from browsers, xterms, emacs, ...

**Comment by jeremyhu** [comment]
Yeah, I'm not reproducing this at all.  ¯\_(ツ)_/¯.

I suggest reaching out to Thomas Dickey given that this is only happening with xterm.

**Comment by jeremyhu** [comment]
Given lack of response here, I'm closing this out.  If you're still seeing this issue, can you point me to an upstream ticket or thread to follow?
