### ISSUE TITLE
2.8.0_rc3 installer exit message

### ISSUE THREAD

**Issue by giardiacorp** [XQuartz/XQuartz#125]
hi jeremy, great job keeping up with all this. 

i noticed that the rc3 installer (unlike several previous installers) does not tell users that they need logout and log back in to make Xquartz the default X11 server. maybe this step is no longer needed?

**Comment by jeremyhu** [comment]
It's only needed after the first install (or the first time you upgrade from 2.7.x).  There was a bug in some versions of macOS which was causing us to report that we always needed to logout.  This was worked around in 217d75d5edc90b1e50dd23c8cd9b4ccd0dce7868 with the unfortunate side-effect that the installer will tell the user that we're going to run an external program to check for system compatibility (we don't).
