### ISSUE TITLE
libXp.6.dylib missing from 2.8.0_rc3

### ISSUE THREAD

**Issue by giardiacorp** [XQuartz/XQuartz#126]
i tried to launch IDL Version 8.5.1 under Xquartz 2.8.0_rc3, and it failed with this error message:
`dyld: Library not loaded: /opt/X11/lib/libXp.6.dylib`
`  Referenced from: /Applications/exelis/idl/bin/bin.darwin.x86_64/libidl.8.5.dylib`
`  Reason: image not found`
`Abort`

THIS WORKED: 
- wipe /opt/X11
- reinstall Xquartz 2.7.11
- preserve a copy of /opt/X11/lib/libXp.6.dylib
- wipe /opt/X11
- reinstall Xquartz 2.8.0_rc3
- copy the old libXp.6.dylib into /opt/X11/lib/

i had been using IDL successfully in rc2 for quite some time, without this error message. but then when i got the error with rc3, i found that wiping/reinstalling rc2 did not bring back libXp.6.dylib. i cannot really explain this.

**Comment by jeremyhu** [comment]
#124
