### ISSUE TITLE
Installation files (dmg & pkg) are not cleaned after updating to 2.8.0

### ISSUE THREAD

**Issue by sygo75** [XQuartz/XQuartz#129]
Updating from XQuartz to 2.8.0_rc3 and then to 2.8.0_r4, the dmg & pkg files are not deleted

**Comment by jeremyhu** [comment]
Well the .pkg is within the .dmg...

And as far as not deleting it.  That's correct.  The system Installer provides an option for you to delete it after installation completes, but that's an OS feature and not something we have control over.  Are you saying that's not working for some reason?  If so, file a bug report at http://bugreport.apple.com
