### ISSUE TITLE
Tips on macOS Catalina and Linux using XQuartz

### ISSUE THREAD

**Issue by lifan18** [XQuartz/XQuartz#13]
## For MacOS Catalina

1. download the latest version https://www.xquartz.org
2. install it as the instructions
3. **restart your Mac** (this step can solve "cannot open display")
4. open the terminal application in XQuartz and input `xterm` to test
___

## For Linux
Once you restart your Mac, you can directly login your remote host
`ssh -Y yourUserName@host`
test `xterm`, it will open a new window on your Mac.

**DO NOT  `export DISPLAY=IP address` in your `.bashrc`file** 
___

Using the steps above, I succeeded in solving problem like 'Gtk-WARNING **: cannot open display:' 

Hope these tips will help someone in the same trouble like me.

Good luck!

**Comment by bishopdynamics** [comment]
Instead of using `-Y` you should use `-X`
You will need to add the following to `.ssh/config` on the mac side:
```
Host *
	XAuthLocation /opt/X11/bin/xauth
```
this is because `xauth` lives in a different location on macos than it normally would on linux

**Comment by LIFanAr** [comment]
> Instead of using `-Y` you should use `-X`
> You will need to add the following to `.ssh/config` on the mac side:
> 
> ```
> Host *
> 	XAuthLocation /opt/X11/bin/xauth
> ```
> 
> this is because `xauth` lives in a different location on macos than it normally would on linux

Received with thanks;D
