### ISSUE TITLE
Software Update window scrolls in lockstep with X11 window underneath

### ISSUE THREAD

**Issue by sckendall2** [XQuartz/XQuartz#130]
Sometimes when I scroll the Software Update window's Release Notes panel, some X11 terminal window underneath it scrolls in lockstep. This happens reliably when I click on the XQuartz icon in the dock, bringing the Software Update window up; click in the Release Notes panel; and scroll up and down using the one-finger gesture on my Apple Magic Mouse.

I can't reproduce this with other methods of scrolling, such as mousing the scroll bar or the "page up" and "page down" buttons on my keyboard.

I'm running 2.8.0_rc3 on Big Sur. This bug is more odd and amusing than inconvenient.

**Comment by jeremyhu** [comment]
Should be easy enough to triage and fix this, so putting on 2.8.1.

**Comment by jenstroeger** [comment]
Hah! Yes I noticed the same on Catalina with the just-shipped 2.8.0.
