### ISSUE TITLE
Missing header in 2.8.0_rc4

### ISSUE THREAD

**Issue by dwcaress** [XQuartz/XQuartz#131]
Thank you for restoring libXp in 2.8.0_rc4.

Associated with libXp is the header file X11/extensions/Print.h - this file is not included in the  2.8.0_rc4 install. I think that Print.h was removed in prior 2.8.0 beta and rc distributions as well, but this was unclear because Xquartz updates did not remove newly missing header files, so the old Print.h from Xquartz 2.7 persisted.

My context is building applications using X11/Motif/OpenGL/GLX, using Xquartz + OpenMotif installed through Homebrew. Unfortunately, in addition to the OpenMotif library libXm requiring requiring linking with libXp, the OpenMotif header file Xm.h references the X11 header Print.h. Consequently, the lack of Print.h breaks building any Motif based program. 

       https://github.com/dwcaress/MB-System

**Comment by jeremyhu** [comment]
The inclusion of the libraries are to preserve binary compatibility with existing software.

The header and the build time library symlink were intentionally not included when re-adding libXp in 2.8.0_rc4 as clients should no longer be using this library.  Please update your software to not link against libXp.

OpenMotif does not require libXp.  It's a configure-time option to enable or disable libXp support.  Given that libXp hasn't been supported by servers for ~decade and never really took off before that, current softare should just remove that dead code.
