### ISSUE TITLE
Title bar from X11 windows missing

### ISSUE THREAD

**Issue by shahpnmlab** [XQuartz/XQuartz#132]
Dear Devs,

I am running the latest version of Xquartz on my M1 macbook pro. Upon starting an xquartz client for eg xclock or xterm, the title bar from the windows has disappeared (see screenshot). Is this is a bug or a borked preference issue? If its the latter could you direct me to a solution?
![Screenshot 2021-03-21 at 14 50 42](https://user-images.githubusercontent.com/34034134/111910804-c57e2380-8a5a-11eb-9d25-5298868406f7.png)

**Comment by jeremyhu** [comment]
This usually means quartz-wm isn't running.  The most common cause of that is the existence of ~/.xinitrc.  If you need further help, please join the x11-users mailing list.

**Comment by JeffFessler** [comment]
Just in case it helps anyone else, I had the same issue on an Intel iMac and removing `~/xinitrc.d/` and restarting XQuartz resolved it.
