### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by codingbutstillalive** [XQuartz/XQuartz#133]
Actually, I would like to connect to an Azure Virtual Machine from my MacBook Pro via x2go.

The tutorial says it is as easy as to download the x2go client and install it. But on the website of x2go it says it requires Xquartz.

Then, I found a webpage saying that in order to install Xquartz I will need homebrew or MacPorts.

Since I am coming from Windows and Linux, I am confused by this complexity.

Could someone please explain what is really needed. I want to install as little software as needed on my machine due to security concerns. This is the reason why I want to develop on a virtual cloud machine in the first place.

**Comment by jeremyhu** [comment]
What website says you need MacPorts or homebrew?

Goto xquartz.org and the main page should give you a link to the installer package.

**Comment by codingbutstillalive** [comment]
Well. I cannot remember the URL of the tutorial website. But even on the official website of Xquartz there is a recommendation to install via MacPorts, as far as I saw.

**Comment by jeremyhu** [comment]
The XQuartz website states, "Another way to get a current X11 installation on your system is through MacPorts" ... it is the only way to get current versions on Mountain Lion and earlier.

**Comment by codingbutstillalive** [comment]
I still don’t understand. Do I need MacPorts to have a current version? I am using Big Sur.

**Comment by jeremyhu** [comment]
No.  Just install the package.  https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.0/XQuartz-2.8.0.dmg

**Comment by codingbutstillalive** [comment]
Thank you very much!
