### ISSUE TITLE
xterm boundaries are not properly honoured under desktop spaces

### ISSUE THREAD

**Issue by weissdorn** [XQuartz/XQuartz#134]
When using "spaces" (multiple desktops) and multiple xterms 
it seems that xquartz looses the correct understanding 
of the window boundaries.

A number of artifacts/failures can be seen:

a) when clicking and holding the title bar of an xterm window,
   the window can be moved up too far, until the xterm title bar
   is moved beyond the menu bar of the desktop.
   if you leave it a this point, it can no longer be moved
   anywhere since the xterm title bar is hidden below the desktop 
   menu bar.

b) the lower few lines of an xterm can no longer be highlighted 
   (marked using the mouse or trackpad).
   If you move the mouse to the last text line and start
   marking (highlighting) this line, another line a few lines
   before gets marked instead. It seems that for this activity
   the xterm has a wrong understanding about which line
   is the last line of the window, and you cannot mark
   the actual last three or so lines.
   (I am using xterms with 40 lines, 90 coloumns).

c) when dragging xterms left or right across the destop
   the movement stops too early, before the xterm  window reaches 
   the desktop boundary. It should actually move even further, over
   to the next desktop as configured with "Spaces". 
   (I am using four desktops)
   However, the position where the movement is blocked depends
   on the initial click on the xterm title bar. 
   if it has been clicked far to the left, it can be tragged
   further to the right. Otherwise, if it has been clicked close to
   right end of the title bar, the movement of the xterm window
   to the right side of the desktop is blocked quite early.

d) whem two xterm windows partly overlay, it is not always
   possible to click the lower window in order to move in upward.
   Again, it seems that xquartz has a wrong understanding
   of the  boundary positions and assumes that the lower window
   is completely hidden, while instead it is partly visible and 
   should be "clickable".

All this behaviour is occuring some time after working with
multiple windows. After starting xquartz and starting a single
xterms, all works okay. When starting more xterms the problem
happens at some point, so can't tell what exactly triggers
the problem and when it starts occurring. When working with
multiple xterm windows on four desktops it is consistendly 
reprodusable, i.e. it will always reoccur after some working time.

XQuartz 2.8.0 (xorg-server 1.19.7)
MacBook Pro 13-inch , M1, 2020
macOS Big Sur 11.2.1

**Comment by jeremyhu** [comment]
#92 should tackle this.
