### ISSUE TITLE
XQuartz

### ISSUE THREAD

**Issue by claudiopascoal** [XQuartz/XQuartz#135]
I installed XQuartz-2.8.0.dmg. It opens but then It crashes with no information at all what happened. This was also occurring for the older versions of XQuartz. The app just opens and then closes with no information. I tried to run it from the terminal but it does the same thing. I tried to uninstall it several times but it didn't work at all.

**Comment by jeremyhu** [comment]
This is most often caused by init scripts like ~/.xinitrc, ~/.xinitrc.d, ~/.profile, ~/.bashrc, ~/.zprofile, ~/.zshrc, ~/.bash_profile.

Please move all of those aside and then investigate what about them is causing your failure.
