### ISSUE TITLE
upgrade fail by homebrew

### ISSUE THREAD

**Issue by iseku** [XQuartz/XQuartz#137]
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Upgrading 1 outdated package:
xquartz 2.7.11 -> 2.8.0
==> Upgrading xquartz
==> Downloading https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.0/XQuartz-2.8.0.dmg
==> Downloading from https://github-releases.githubusercontent.com/201858552/92f11c80-8a94-11eb-931e-f4762e8b10ea?X-Amz-Algorithm=AWS4-HMA
######################################################################## 100.0%
==> Removing launchctl service org.macosforge.xquartz.startx
==> Removing launchctl service org.macosforge.xquartz.privileged_startx
==> Uninstalling packages:
==> Removing files:
/opt/X11
/private/etc/manpaths.d/40-XQuartz
/private/etc/paths.d/40-XQuartz
==> Running installer for xquartz; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
==> Purging files for version 2.8.0 of Cask xquartz
==> Purging files for version 2.8.0 of Cask xquartz
Warning: Reverting upgrade for Cask xquartz
==> Running installer for xquartz; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is XQuartz 2.7.11
installer: Installing at base path /
installer: The install was successful.
Error: xquartz: Could not find PKG source file 'XQuartz.pkg', found 'Xquartz.pkg' instead.

**Comment by jeremyhu** [comment]
Whoops.  I let go of shift too quickly, and nobody caught that until after release =/  I'll fix that, but homebrew will probably need to adjust for now.

**Comment by Gcenx** [comment]
@jeremyhu honestly I don’t think it’s worth changing the name back it’s not a real issue unless you just want consistency between the old and new versions of XQuartz.
