### ISSUE TITLE
xquartz not automatically lauching with iterm2

### ISSUE THREAD

**Issue by lthilnklover** [XQuartz/XQuartz#138]
Till now, when I connect to server using ssh -X on iterm2, Xquartz was automatically launched, and everything was fine. However, now it is not launching automatically and xforwarding is not working either. 

I have both updated OS and Xquartz  yesterday, so I am guessing they might be causing problems.

**Comment by lthilnklover** [comment]
It works, but only with ssh -Y. It used to also work with ssh -X. I am not sure  what is the difference.

**Comment by jeremyhu** [comment]
What is your DISPLAY before your run ssh -X?  Is it using the launchd socket or the traditional socket (:0)?

**Comment by lthilnklover** [comment]
> What is your DISPLAY before your run ssh -X? Is it using the launchd socket or the traditional socket (:0)?

you mean my local DISPLAY?

on my mac 
> echo $DISPLAY
/private/tmp/com.apple.launchd.NTGXhek537/org.xquartz:0

**Comment by jeremyhu** [comment]
Ok, then that should work just fine.  Nothing about xauth should be messing with that... hrm... not sure.  It works fine here =/

The main difference is in the use of the SECURITY extension to block things like keyloggers from running on that connection.

**Comment by lthilnklover** [comment]
> Ok, then that should work just fine. Nothing about xauth should be messing with that... hrm... not sure. It works fine here =/
> 
> The main difference is in the use of the SECURITY extension to block things like keyloggers from running on that connection.

Maybe the recent OS update (which was related to security issue) might be the problem. But since ssh -Y still works, I will just stick to using ssh -Y. Thank you for the reply.
