### ISSUE TITLE
The X11 connection broke (error 1). Did the X11 server die?

### ISSUE THREAD

**Issue by 836304831** [XQuartz/XQuartz#139]
I install Xquartz on my mac machine, then running a container using docker, in container, I start my pyqt application. unfortunately,  when running for some, my application crashed and print "The X11 connection broke (error 1). Did the X11 server die?".
could you give me any help?

**Comment by jeremyhu** [comment]
Did the server crash?  Did you quit XQuartz?  Is there a crash log?

**Comment by jeremyhu** [comment]
No response.  Closing.
