### ISSUE TITLE
xQuartz for ARM64

### ISSUE THREAD

**Issue by maxebert2020** [XQuartz/XQuartz#14]
Hi there,

I already sent this question to the mailing list but I am not sure who is monitoring what in the project. I wanted to know what are the chances to see an ARM64 binary build of xQuartz?

Thanks,
Max

**Comment by IComplainInComments** [comment]
In theory compiling the project for ARM64 should render a build as X.org already runs amazing on ARM.

**Comment by jeremyhu** [comment]
Yeah, it works fine and has since very early in our bringup of Apple Silicon Macs.  There just isn't a package available because nobody has taken over managing releases, so your best bet is to use MacPorts.
