### ISSUE TITLE
Mapping Mac Command key to mod1 (for i3 wm).

### ISSUE THREAD

**Issue by jenstroeger** [XQuartz/XQuartz#141]
On my laptop I use XQuartz 2.7.11 (xorg-server 1.18.4) and the [i3 window manager](https://i3wm.org/) built with [brew](https://brew.sh/) (although I can’t find it there anymore).

Now on my new Mac I updated XQuartz to 2.8.0 and installed [i3 using MacPorts](https://ports.macports.org/port/i3/summary), copied over `.Xdefaults` and `.Xmodmap` and `.Xresources` — and for the life of me I can’t figure out how to map the Mac <kb>Command</kb> key to [i3’s <kb>mod1<kb> key](https://i3wm.org/docs/userguide.html#keybindings) 🤔 

Did anything change, anything I need to be aware of that I forgot?

**Comment by jeremyhu** [comment]
Nothing changed here.  Is the issue that yo have "Enable key equivalents..." enabled in X11 -> Preferences -> Input?  That would cause some keystrokes to be grabbed by AppKit.

.Xmodmap should "just work"

**Comment by jeremyhu** [comment]
Please join the x11-users mailing list to ask for help on this subject if you're unable to figure it out.

**Comment by jenstroeger** [comment]
Thanks @jeremyhu, you mean [this mailing list](https://lists.apple.com/mailman/listinfo/x11-users)?

**Comment by jeremyhu** [comment]
Yes
