### ISSUE TITLE
After reinstalation of XQuartz 2.7.11, any X11 binary hangs

### ISSUE THREAD

**Issue by eojero** [XQuartz/XQuartz#143]
Due to some issues detected when running our applications after upgrading to XQuartz 2.8.0 in macOs Catalina and BigSur, we decided to return to XQuartz 2.7.11 where these issues where not present. Then, on both Catalina and BigSur, when attempting to run an xterm or any other X11 application from the Terminal, it gets hanged. No error, no timeout, nothing! However, if we activate the XQuartz root full screen mode, we can open any X11 application. Before the upgrade to XQuartz 2.8.0, the installed v2.7.11 was not producing any problem. Any X11 binary was working when launched from a standard terminal. Is there any setting required to get back to this behaviour? Any help is very much appreciated. Best regards!

**Comment by jeremyhu** [comment]
> Due to some issues detected when running our applications after upgrading to XQuartz 2.8.0 in macOs Catalina and BigSur

What are those issues?  You should file bugs about them.

---

The issue is likely that you did not follow the uninstallation instructions.  I suspect you still have the org.xquartz.startx launchd.plist.  See https://www.xquartz.org/FAQs.html
