### ISSUE TITLE
makedepend no longer shipped in 2.8.0

### ISSUE THREAD

**Issue by dmacks** [XQuartz/XQuartz#145]
cernlib2006 and possibly some other old codebases still use the old X11/bin/makedepend utility. It used to be distributed as part of XQuartz, but when I upgraded to 2.8.0, it was no longer present. I can understand dropping very old and obsolete tools, but I also didn't see any release-notes about this change (https://www.xquartz.org/releases/XQuartz-2.8.0.html). If this is an intentional change, please make sure to document it.

**Comment by jeremyhu** [comment]
Yeah, I missed this.  I'll update the release note.
