### ISSUE TITLE
Xquartz 2.8.0 does not acknowledge .xinitrc file

### ISSUE THREAD

**Issue by karlwkrieger** [XQuartz/XQuartz#146]
I tried to extend the default font path by creating a .xinitrc startup file with the following commands:

xset fp+ /Users/this_user/my_own_fonts
xset fp rehash

However, with this .xinitrc file in the user home directory, whenever Xquartz is started by an X11 routine such as xterm, it crashes after a few seconds and tries to restart again. This repeats until the .xinitrc file is deleted or renamed. I assume that .xinitrc is not accepted by Xquartz for defining additional X11 initialization commands by a user or it is interpreted in a different way than in the default X11 distribution. Is this a bug or a feature? In case of the latter, how is it possible to define and execute user level initializations such as adding font directories to fontpath?

**Comment by jeremyhu** [comment]
This is the correct behavior.  The X11 server terminates when ~/.xinitrc terminates.

If you want to *ADD* to the initial startup environment, you should create a ~/.xinitrc.d directory with scripts within it.
