### ISSUE TITLE
compile.sh

### ISSUE THREAD

**Issue by gaming-hacker** [XQuartz/XQuartz#15]
there are no commands in this file 'compile.sh', it just points to directories.

**Comment by zebity** [comment]
hi @gaming-hacker ,

as you say the compile.sh script just points to directory not any executable ...

did you make any progress on this or did you give up ?

I have force the repo and am looking to get Catalina compile going.

Cheers,

Zebity/John

**Comment by jeremyhu** [comment]
Yes, the compile.sh script was a WIP to start putting together a new build script for XQuartz, but nobody has taken it on, so it'll be a while...
