### ISSUE TITLE
New XQuartz doesn't provide libpng15.15 breaks current Winehq packages.

### ISSUE THREAD

**Issue by Gcenx** [XQuartz/XQuartz#151]
https://github.com/XQuartz/XQuartz/blob/5bf34b03d54a99796b5ea332c729618a1cc6ac85/compile.sh#L36-L41

I see `libpng15.15` listed in the TODO section will this happen in a later release?

I'll update the issue with with the other needed dylibs when I have time to verify the other required dylibs.

**Comment by jeremyhu** [comment]
I decided to omit these because I was not aware of any clients.  libpng is primarily provided for XQuartz internal use, and there were no such issues reported during beta and rc testing.  I could re-add libpng15 if needed, but it's probably best for winehq to update.

**Comment by Gcenx** [comment]
I’m sure most users wouldn’t have even noticed an rc for XQuartz, especially Winehq users who commonly install using brew.

Already modified the macOS wiki section specifying the need to use an older version of XQquartz due to this.

Winehq updating packages theres currently no official packages since Wine-5.7 after this the cross-compiler was taken out of service.

Currently I’m providing unofficial winehq packages that won’t be affected as badly as the older official packages, having the older packages working helps narrow down what versions to do regressions testing on.

**Comment by jeremyhu** [comment]
I'm working on getting a 2.8.1 beta out with this re-added.  As a workaround for now, you could backup the dylib, install 2.8.0, then put the dylib back in place.

**Comment by sc0ttdav3y** [comment]
I came here from the link on https://wiki.winehq.org/MacOS

I notice that on the same page, the homebrew installation instructions say to run `brew install --cask xquartz`, but that results in 2.8.0 being installed. 

Do I need to run `brew install --cask xquartz@2.7.11` instead?

**Comment by Gcenx** [comment]
@sc0ttdav3y You'll need to uninstall XQuartz via brew then install the older 2.7.11 package yourself as [homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions) doesn't have a cask for 2.7.11, you could extract the older version locally and pin that to force installing the needed version until the next release is available via brew. (only when stable not an -rc)

Alternatively you can avoid that all together by using my tap and packages
```
brew tap gcenx/wine
brew install --cask --no-quarantine gcenx-wine-stable
```

The tap provides;
- gcenx-wine-stable
- gcenx-wine-devel
- gcenx-wine-staging

These provided the current version of each package, the `gcenx-` was required due to brew not handling duplicate casks/formulas very well. These only function on macOS High Sierra and later.

The provided gcenx-wine-devel cask is being used for the wine-mono GitHub workflow already and after talking to a couple of the wine developers/maintainers bug reports are allowed for my packages.

**Comment by Gcenx** [comment]
@jeremyhu I’ll take a look once I’m home but as they listed XQuartz 2.8.0 there issue would make sense due to the lack of libpng15.15

This should be resolved within https://github.com/XQuartz/XQuartz/releases/tag/XQuartz-2.8.1_beta1 but I’ll confirm that’s the case as I’ve not had change.

**Comment by g6ai** [comment]
If anyone wonders how to install XQuartz 2.7.11 with Homebrew Cask (Me personally haven't run into Wine problems using XQuartz 2.8.*), I maintain a tap [g6ai/ale](https://github.com/g6ai/homebrew-ale) which contains an XQuartz 2.7.11 version called `xquartz-2-7` (.rb file excerpted from the official repo). Steps are:

```console
$ brew tap g6ai/ale
$ brew install xquartz-2-7
```

**Comment by Gcenx** [comment]
@g6ai this issue was lightly specific to Winehq releases that linked to libpng15.15 that was disabled in the initial release.

XQuartz-2.8.1 added back these removed libraries, the only current benefit I can see for installing XQuartz-2.7.7 would be for OS X 10.8 support and as far as I know tigerbrew doesn’t support casks/taps.

**Comment by g6ai** [comment]
@Gcenx Thanks for the knowledge! So the reason I didn't have problem with XQuartz 2.8 is probably that I skipped 2.8.0 and went straight to 2.8.1.

**Comment by Gcenx** [comment]
@g6ai if you were using Winehq packages then that’s lightly the case. If you were using my Wine packages those function without XQuartz when using macDriver.
