### ISSUE TITLE
XQuartz 2.8.1_rc1 performance regression

### ISSUE THREAD

**Issue by autonomic** [XQuartz/XQuartz#156]
Good evening,

I just installed XQuartz 2.8.1_rc1 to test and noticed very sluggish performance. Even when using the default xterm application and running 'ps awux' there were large delays in the output and drawing on screen.

I'm running macOS 11.3 (release candidate) on a MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports).

I decided to remove 2.8.1_rc1 and re-install 2.8.0 and performance was back to normal, so there is something in 2.8.1_rc1 that's causing a massive performance hit. I'm happy to help run some debugging for you so please let me know what you would need.

**Comment by jeremyhu** [comment]
Can you backup your XQuartz.app (ie: create a tarball of XQuartz.app itself) then update from 2.8.0 to 2.8.1_beta1?  Does 2.8.1_beta1 also have the issue?  I assume so becasue beta1 and rc1 are very similar.

Assuming so, please update to 2.8.1_rc1.  Then unpack your backed up XQuartz.app (2.8.0) to another location and run it.  Does it work fine?  Assuming so, this seems to be a server regression between the 1.19 and 1.20 branches.

**Comment by autonomic** [comment]
@jeremyhu so I ran through those tests. I upgraded from 2.8.0 -> 2.8.1_beta1 and the delayed output/drawing exists in this version. I then upgraded from 2.8.1_beta1 -> 2.8.1_rc1 and the same issue occurs. Please see video below.

Using the backup of XQuartz 2.8.0 I untared this into another application folder and ran it and I am not experiencing the performance issues seen in the 2.8.1 versions.

https://user-images.githubusercontent.com/13229225/115752814-547aa600-a34f-11eb-9d93-bf52bb240252.mov

**Comment by jeremyhu** [comment]
Great thanks.  That means this is certainly a server side performance regression.  And on top of the one that we got from macOS a few years back (in El Cap?), this is pretty bad =/

**Comment by jeremyhu** [comment]
Bisected it to:

```
ac7a4bf44c68c5f323375974b208d4530fb5b60f is the first bad commit
commit ac7a4bf44c68c5f323375974b208d4530fb5b60f
Author: Chris Wilson <chris@chris-wilson.co.uk>
Date:   Sun Apr 15 15:40:03 2018 +0100

    os/WaitFor: Check timers on every iteration
    
    Currently we only check timer expiry if there are no client fd (or
    other input) waiting to be serviced. This makes it very easy to starve
    the timers with long request queues, and so miss critical timestamps.
    
    The timer subsystem is just another input waiting to be serviced, so
    evaluate it on every loop like all the others, at the cost of calling
    GetTimeInMillis() slightly more frequently. (A more invasive and likely
    OS specific alternative would be to move the timer wheel to the local
    equivalent of timerfd, and treat it as an input fd to the event loop
    exactly equivalent to all the others, and so also serviced on every
    pass. The trade-off being that the kernel timer wheel is likely more
    efficiently integrated with epoll, but individual updates to each timer
    would then require syscalls.)
    
    Reviewed-by: Peter Harris <pharris@opentext.com>
    Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>

 os/WaitFor.c | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)
```

**Comment by jeremyhu** [comment]
https://gitlab.freedesktop.org/xorg/xserver/-/issues/1167
