### ISSUE TITLE
After the latest update X not sarting automatically on macOS Catalina v10.15.7 (19H524)

### ISSUE THREAD

**Issue by FleXoft** [XQuartz/XQuartz#157]
XQuartz 2.8.1_rc1 (xorg-server 1.20.11)

**Comment by jeremyhu** [comment]
Seems to be working fine here.  Can you please debug it and determine the problem?  Please create a fresh user account to see if the issue is unique to your account settings.  Ask for help on the x11-users mailing list if you need support.
