### ISSUE TITLE
Unable to connect to X-server on ios -- with `getattrlist failed for [non-existent .dylib]`

### ISSUE THREAD

**Issue by Geof23** [XQuartz/XQuartz#158]
This is from my system.log:

```
system.log.0:Apr 23 23:06:54 [username] com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.org.xquartz.X11.3274875.3274883(501)> [2028]
system.log.0:Apr 23 23:06:55 [username] X11.bin[49359]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
system.log.0:Apr 23 23:06:55 [username] X11.bin[49359]: getattrlist failed for /Library/GPUBundles/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
system.log.0:Apr 23 23:06:55 [username] X11.bin[49359]: getattrlist failed for /System/Library/Extensions/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
system.log.0:Apr 23 23:06:55 [username] X11.bin[49359]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
```

The above is happening while opening an x-win app on remote host:
```
emacs &
[1] 1945942
[username]~% X11 connection rejected because of wrong authentication.
Display localhost:10.0 unavailable, simulating -nw
```

**Comment by Geof23** [comment]
(macOS Big Sur 11.2.3)

remote is CentOS 8

**Comment by jeremyhu** [comment]
The logs you provided do not represent any problem with XQuartz.

The issue you are reporting is because of an issue with xauth.  Please ask for help on the x11-users mailing list if you have problems with X11 forwarding.  There is also a faq at https://www.xquartz.org/FAQs.html

**Comment by Geof23** [comment]
@jeremyhu so the X11.bin errors are normal?

**Comment by jeremyhu** [comment]
"Coalition Cache Hit" is informational.
The lines about various graphics drivers are probably because something in the graphics stack is looking for drivers that aren't there for some reason (completely unrelated to your issue... probably just logging noise in OpenGL.framework in macOS)

**Comment by Geof23** [comment]
Jeremy, thanks for confirming those system.log entries are not related to
my Xauth problem -- Geof
