### ISSUE TITLE
[BigSur][XQuartz 2.8.1] Problems with black background

### ISSUE THREAD

**Issue by kolibril13** [XQuartz/XQuartz#159]
# Problem
I have problems with the colours when using Matlab remotely with XQuartz:
When I use only the laptop display, everything seems to be black when seeing the display:
![photo5208772608596751528](https://user-images.githubusercontent.com/44469195/116385428-141c9b80-a819-11eb-9675-4a3a56b45c6a.jpg)
I also did a screenshot, but the screenshot does not make this strange black background (although, also here the resolution is a bit weird):
![image](https://user-images.githubusercontent.com/44469195/116385384-09620680-a819-11eb-8aac-5b78b066651a.png)
# When the problem does not occur:
When I use two display, and the mouse is *not* on the display where x11 is shown, everything looks good, but as soon as I change the mouse to the other display, the resolution is bad again.
https://user-images.githubusercontent.com/44469195/116384531-395cda00-a818-11eb-9404-1dee5a1dfcf8.mp4

**Comment by jeremyhu** [comment]
#31
