### ISSUE TITLE
crash at XkbAdjustGroup when running emacs from Ubuntu 20.04 through XQuartz 

### ISSUE THREAD

**Issue by michaelawells** [XQuartz/XQuartz#160]
This issue is similar to the problem reported at https://gitlab.freedesktop.org/xorg/xserver/-/issues/283 and elsewhere.

To reproduce:
   From a Mac OS 10.5.7 terminal, ssh to a Ubuntu 20.04 machine:
      ssh -Y foo@bar
  Open emacs:
     emacs &
  An emacs window will open in XQuartz.
  In emacs, type: <Meta-X> shell <RET>
  Instead of opening a shell, XQuartz will crash.  See attached crash log.
 The crash invariably occurs at "XkbAdjustGroup".

There are many ways to get XQuartz to crash while running emacs.  Opening a shell within emacs is a simple way to reproduce the problem.

 I don't have this problem when using emacs running on Ubuntu 16 or 18.

I want to continue to use Macs to develop for Linux machines.  XQuartz has been a godsend.  I can enjoy all the good things about OSX/MacOS and develop for Linux on the same machine.
I very much want to continue to use MacOS for Linux development, but I must be able to run emacs in XQuartz.  Otherwise I'll have to move to using a not nearly as good desktop environment, which will make me very sad.

[crash.txt](https://github.com/XQuartz/XQuartz/files/6396645/crash.txt)

Please let me know if I can provide any additional information.
(I think this issue is related to the problem reported at https://github.com/XQuartz/XQuartz/issues/71 as well.)

**Comment by jeremyhu** [comment]
This is the same crash as #71

**Comment by michaelawells** [comment]
Some further information:
This line was in my .bashrc:
setxkbmap -option ctrl:nocaps

If I take out this line, and fire up a new terminal, emacs does not crash as reported.
