### ISSUE TITLE
"Unknown sequence number while processing queue"

### ISSUE THREAD

**Issue by josephwright** [XQuartz/XQuartz#161]
I'm trying to run a program called GView (part of [Gaussian16](https://gaussian.com/gaussian16/)) on a remote Linux-based system. Trying to access from my mac I get the error
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
gview: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
and no access to GView. I'm using  XQuartz 2.8.1 (xorg-server 1.20.11) on macOS 11.3.

Accessing the same system from Windows (PuTTY/Xming) or Linux (Ubuntu Xenial) works without this error, so I think it is not an issue of the server system.

**Comment by jeremyhu** [comment]
Well is gview a multi-threaded app?  Can you report this to the authors?  This is most likely catching a reall bug in your app.
