### ISSUE TITLE
Using XQuartz (Xvfb) within Github Actions for Continuous Integration

### ISSUE THREAD

**Issue by dkfellows** [XQuartz/XQuartz#162]
[We (the Tcl/Tk maintainers)](/tcltk) have been using XQuartz (specifically the build of Xvfb that's part of it) for allowing us to do automatic testing of [Tk](/tcltk/tk) in Github Actions, but this seems to have broken with the 2.8 release. The issue appears to be that the trick we were using to avoid having to log out after installing Xvfb (a _critical_ requirement for CI use!) is no longer working. (We test on as many platforms as we can; toolkits can be devilishly tricky in their interaction with the underlying platform and supporting _real_ XQuartz use by users of downstream projects is a target goal.)

1. What should we do instead? (If it was documented what the system setup actually needed to be, we could just write our own. That'd be messy, but what we were/are doing right now is also messy.)
2. Is there any possibility of some sort of assurance that the CI use case will have consideration in the future?

Sorry for not raising this query earlier.

**Comment by dkfellows** [comment]
Relevant log sections (from https://github.com/tcltk/tk/actions/workflows/mac-build.yml?query=branch%3Amain):
```
==> Installing Cask xquartz
==> Running installer for xquartz; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is 
installer: Installing at base path /
installer: The install was successful.
installer: The install requires logging out now.
🍺  xquartz was successfully installed!
sudo: /opt/X11/lib/X11/xinit/privileged_startx.d/10-tmpdirs: command not found
```
…
```
Launched Xvfb :0 as process 14897
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
_XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for local
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
```
…
```
couldn't connect to display ":0"
```

(There's a great deal more stuff in-between that isn't relevant. The CI script is at https://github.com/tcltk/tk/blob/main/.github/workflows/mac-build.yml)

**Comment by jeremyhu** [comment]
> sudo: /opt/X11/lib/X11/xinit/privileged_startx.d/10-tmpdirs: command not found
> ...
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

That's the relevant parts.  The tmpdirs are not being created.

Why are you trying to execute /opt/X11/lib/X11/xinit/privileged_startx.d/10-tmpdirs directly?  You should execute /opt/X11/libexec/privileged_startx which will run all of the privleged startup scripts.

**Comment by fvogelnew1** [comment]
Many thanks! This answer moved us one step forward. There are further issues, but xvfb does not seem to be involved at first sight.
