### ISSUE TITLE
Cannot work remotely anymore

### ISSUE THREAD

**Issue by patri06** [XQuartz/XQuartz#163]
Hi, I use a Mac with the BigSur 11.2.3 version. Since I have installed Xquartz I cannot work remotely on paraview, but it worked before. Now, paraview gives and error such as:
Could not receive tag. 1010580540
Endian Handshake failed.

While the remote where I am trying to work gives me the following error:
/usr/lib/ssh/ssh-askpass: line 47: /usr/lib/ssh/x11-ssh-askpass: No such file or directory.

Any clues?? 
Thanks in advance!

**Comment by jeremyhu** [comment]
You'll have to ask for suport from your work on this one.  That error message is unrelated to anything in XQuartz.  Probably an issue with their system-wide shell init scripts or something.
