### ISSUE TITLE
Bug Report: App not opening

### ISSUE THREAD

**Issue by aryanL-x86** [XQuartz/XQuartz#164]
## `/Applications/Utilities/XQuartz.app` doesn't open

- Description:
I opened the app and only the menu bar shows and when I click to open Terminal, xman or xlogo, a blank screen appeared.
a minute later, again it popped into the dock, jumping and showed the menu bar. after about 5 seconds it again disappeared and (this repeated and finally I had to reboot.)

- OS/App Info
- Executable: `/Applications/Utilities/XQuartz.app/Contents/MacOS/X11`
 - Mount - Macintosh HD macOS 11.0 (not a HackIntosh)
 - `% uname -a`
 `Darwin XXX-MacBook-Air.local 20.4.0 Darwin Kernel Version 20.4.0: Mon Jan  1 XX:XX:XX PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64`
 - `% uname -p`
`i386`
- About This Mac (serial number cropped)
![image](https://user-images.githubusercontent.com/80169337/117292119-6f8c0080-ae8d-11eb-95df-9b2605b92511.png)

**Comment by jeremyhu** [comment]
This usually happens because of buggy init scripts.  Please move aside ~/.profile, ~/.bashrc, ~/.xinitrc, etc to find your problematic file and then start looking into what in it is causing your problem.
