### ISSUE TITLE
XQuartz window not showing plots made using ggplot2 R pkg

### ISSUE THREAD

**Issue by jdunic** [XQuartz/XQuartz#168]
Version: **XQuartz 2.8.1** (but same bug occurred in 2.7.11 and 2.8.0 after updating from Catalina to Big Sur)
MacOS: **Big Sur 11.2.2**

After updating from Catalina to Big Sur plots produced using the `ggplot2` package in R do not always show up in a quartz window. When a quartz window is:
1.  manually opened using `dev.new()`
2.  resized with a mouse
3. moved to another monitor 

calling a ggplot2 object fails to show it in the quartz window until I call a base plot, manually resize the Quartz window with my mouse, or move the Quartz window to another monitor. Using the base plot strategy seems to 'reconnect' ggplot and the quartz window and subsequent ggplots will show up without resizing/moving. However, the latter two strategies only work to show the current plot, subsequent plots will not show up. This behaviour does not give me an error.

Examples of the different cases.:

```
library(ggplot2)

# Case 1: open new plotting window using dev.new()
dev.off()
dev.new()
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point()  # does not show up and no error notification

plot(1)  # works - seems to 'reconnect' ggplot to quartz window
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point()  # works
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point(colour = 'orange')  # plot updates properly 
```
```
# Case 2 & 3: resize quartz window with mouse or move to a different monitor
plot(1)   # get ggplot working again before resizing
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point()  # works
# Manually resize window and try:
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point(colour = 'blue')  # does not show up until resized/moved to new monitor

# After resizing/moving to new monitor, can get it working again:
plot(1)
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point()  # works
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point(colour = 'blue')  # works
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point(colour = 'orang')  # works

```

This behaviour was recently noted in a [ ggplot2 issue](https://github.com/tidyverse/ggplot2/issues/4288) (which has a helpful gif showing the behaviour) but was closed as it was considered to be an issue with XQuartz. I tried to replicate the `Error in UseMethod("depth")` found by the original poster in that issue but I cannot. The following code automatically opens a new quartz window and shows the plot. 

```
# Open new R session
library(ggplot2)
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point()  
```

```
# But if I manually open a new device window after starting a fresh R session it does not work. 
# Open new R session
library(ggplot2)
dev.new()
ggplot(data = mtcars, aes(x = cyl, y = mpg)) + geom_point()  # Does not show plot
```

My R sessionInfo()

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ggplot2_3.3.2.9000

loaded via a namespace (and not attached):
 [1] magrittr_2.0.1   tidyselect_1.1.0 munsell_0.5.0    colorspace_1.4-1
 [5] R6_2.5.0         rlang_0.4.10     fansi_0.4.2      blob_1.2.1
 [9] dplyr_1.0.5      grid_4.0.3       gtable_0.3.0     utf8_1.2.1
[13] DBI_1.1.1        withr_2.3.0      ellipsis_0.3.1   digest_0.6.27
[17] assertthat_0.2.1 tibble_3.1.0     lifecycle_1.0.0  crayon_1.4.1
[21] purrr_0.3.4      farver_2.0.3     vctrs_0.3.7      glue_1.4.2
[25] labeling_0.3     compiler_4.0.3   pillar_1.5.1     generics_0.1.0
[29] scales_1.1.1     pkgconfig_2.0.3
```

**Comment by afranks86** [comment]
I'm having the same issue, although I'm on Monterey.  Has any fix been identified?

**Comment by MrJGao** [comment]
I am having the same issue, and I'm on Monterey, too.

**Comment by juliapartheymueller** [comment]
Still no solution?

**Comment by jeremyhu** [comment]
There probably won't be unless someone impacted by this issue spends the time to triage it... =/

**Comment by juliapartheymueller** [comment]
After having updated to R version 4.2. everything now works just fine.

**Comment by jeremyhu** [comment]
Ok, great to hear!  Is there an upstream bug report that tracked fixing the issue?  It would be good to have a link to it from here.  I'm curious what the issue was.

**Comment by Debilski** [comment]
I made an attempt to do a `git bisect` to find out if there was a particular change in the R code base, but getting it to compile from the [git mirror](https://github.com/wch/r-source) is not super straightforward, so I gave up eventually.
Curiously, the self-compiled one worked fine even for v4.0, although the pre-compiled binaries of v4.0 exhibited the same error with ggplot2.

**Comment by jdunic** [comment]
Thank you, the R 4.2 update worked. My workflow is restored! Thank you to anyone who took time to chime in with their info,  investigate, and troubleshoot this issue!

**Comment by nigiord** [comment]
Hello, am I the only one to observe a regression on this on R version 4.3.3 (2024-02-29) and XQuartz 2.8.5 ?

I don’t know if this could be related but I have the following option enabled:
`defaults write org.xquartz.X11 enable_render_extension 0`
(this is a workaround for this other issue: https://github.com/XQuartz/XQuartz/issues/31#issuecomment-1702739686 )

Basically: the Quartz window opens but the plot is either blank or partially blank (missing text, labels, axis, etc) until I slightly resize the window. It’s really annoying on a day-to-day basis when working interactively.
