### ISSUE TITLE
Disappearing cursor Xquartz bug

### ISSUE THREAD

**Issue by DSfusion** [XQuartz/XQuartz#170]
I often find in running Xquartz (I'm at 2.8.0_beta3, but I seen this with other versions) on the Mac, that when I go to quit, the cursor goes away. Also, the pop-up window that asks if I really want to quit X11 has both the "Cancel" and "Quit" buttons greyed out, so I can't just hit return to Quit. The only way I can quit is to shift to one of my other window-pages (this brings the cursor back) and Force quit on Xquartz.

**Comment by jeremyhu** [comment]
This was addressed in 2.8.0_rc3.  #100
