### ISSUE TITLE
XQuartz  not starting on BigSur

### ISSUE THREAD

**Issue by recursive68** [XQuartz/XQuartz#172]
Not sure if this is best place to post this but XQuartz is not starting on BigSur for me, seeing these errors in the system.log:

May 15 16:09:22  com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.org.xquartz.X11.8677363598.8677363606(501)> [1955]
May 15 16:09:23 X11.bin[52554]: getattrlist failed for /System/Library/Extensions/AppleIntelBDWGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelBDWGraphicsGLDriver: #2: No such file or directory
May 15 16:09:23  X11.bin[52554]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory

Any help appreciated.
Thanks

**Comment by jeremyhu** [comment]
Those aren't errors.  Those are just informational.

**Comment by recursive68** [comment]
They may not be errors but it still doesn't work, it launches in Dock, "bounces" and then closes.

**Comment by jeremyhu** [comment]
That usually means you have an alternative server owning $DISPLAY (often because you did not logout after installation).  What do you see for this in Terminal:

    $ launchctl getenv DISPLAY
    $ echo $DISPLAY
