### ISSUE TITLE
Update ssh config files at server launch due OS updates removing customizations

### ISSUE THREAD

**Issue by raoultrines** [XQuartz/XQuartz#174]
I wish to report an issue with how XQuartz interacts with SSH. I am not sure whether this should be classed as a bug report, a feature request or a documentation issue; the developers can decide.

In the ssh_config manual, it says that SSH looks for xauth at /usr/X11R6/bin/xauth by default. After installing XQuartz, this file does indeed seem to exist. Unfortunately its path contains a symbolic link (/usr/X11R6), and SSH does not like symbolic links for security reasons. Thus, if I use ‘ssh -X’, it refuses to launch /usr/X11R6/bin/xauth.

Of course, the true location of xauth (/opt/X11/bin/xauth) could be set in /etc/ssh/ssh_config or /etc/ssh/sshd_config, and the XQuartz FAQ informs me that this is indeed happening during XQuartz installation. Unfortunately this will only last until the next MacOS update, when those two files will be returned to their originals, and the correct location of xauth is lost. The users are not warned about this, but the next time they run ‘ssh -X’, it will mysteriously fail with this error message:
“Warning: untrusted X11 forwarding setup failed: xauth key data not generated.”
There will be an SSH connection, but without X11. No clear indication of what is really going on (SSH refusing to start /usr/X11R6/bin/xauth because of the symbolic link in the path).

I read somewhere that users should reinstall XQuartz after each MacOS update, probably for this very reason, but this should not be necessary, and there are better ways to fix this issue. The most robust solution I found is this:
1.  Start XQuartz, go to Preferences with "Cmd-, " and go to the Security tab. Enable the first option: “Authenticate connections".
2.  Edit or create the file "~/.ssh/config" on the Mac and add the line "XAuthLocation /opt/X11/bin/xauth" at the very top, to set the correct location of xauth.
3.  Use "chmod 600 ~/.ssh/config" to set the correct permissions for this file.
4.  Use "ssh -X" to connect to a remote server including X11.

Since system updates do not normally mess with files in users’ home directories, this solution will survive any updates to MacOS. Even better: ‘ssh -X’ runs xauth, and xauth starts XQuartz, so you can run ‘ssh -X’ from a normal Terminal application rather than Xterm, which is much better in terms of copy/paste and related matters.

I can see none of the above in the XQuartz FAQ. Instead, I see this:
“This list shows the expected behavior of the system.
…
[4] local $ ssh -Y remote
Warning: No xauth data; using fake authentication data for X11 forwarding.
…
The warning message in step 4 is harmless. …”

I do not think that the above warning message is ‘harmless’. Warning messages usually indicate that someone is cutting corners. In this case, the corner that is being cut is the extra security layer provided by ‘ssh -X’ that is absent for ‘ssh -Y’; see the SSH manual. A much better solution would be to ensure that ‘ssh -X’ works for all users of XQuartz. At the very least, the correct procedure should be given in the XQuartz manual and/or FAQ. An even better solution would be to change the XQuartz installation such that the settings for XAuthLocation survive any system updates.

Looking around the internet, I get the impression that many XQuartz users are struggling with this issue, without having the remotest idea what is going on or how to fix it. Resolving this issue, or at least improving the documentation, will help many.

**Comment by jeremyhu** [comment]
The post-install script (https://github.com/XQuartz/XQuartz/blob/master/pkg/scripts/postinstall) sets this up for you:

```
$ tail -n 3 /etc/ssh/ssh_config 
# XAuthLocation added by XQuartz (https://www.xquartz.org)
Host *
    XAuthLocation /opt/X11/bin/xauth
```

This file used to not get replaced by macOS on update.  If it is, that seems like a macOS bug, so please file at at http://bugreport.apple.com

---

Yes, the steps you provided will certainly work well as ~/.ssh/config will defintiely not be replaced by system updates.

---

Could you please provide a pull request to https://github.com/XQuartz/xquartz.github.io to update the FAQ to address your concerns?

**Comment by raoultrines** [comment]
Thank you for your response. I am using a MacBook Pro with macOS Catalina 10.15.7 and XQuartz 2.7.11. When I first installed XQuartz, ‘ssh -X’ worked fine, so I am fairly sure that the ‘postinstall’ script did its job. Then, as soon as I updated MacOS, ‘ssh -X’ failed with the above error message. I then applied my fix and ‘ssh -X’ has been working for me ever since.

When I check /etc/ssh/ssh_config or /etc/ssh/sshd_config, there is no sign of the specific setting of XAuthLocation that XQuartz needs. The date stamp of these files has also changed, so I’m pretty sure that the changes by the ‘postinstall’ script were undone by a system upgrade.

I’ve lost count of the number of colleagues and students that I had to help with the same issue, certainly more than ten. I also spotted this very same issue in the comments to issue #108: user ‘jschnack-uni’ noted that ‘ssh -Y’ stopped working after a MacOS Big Sur update, and that setting XAuthLocation would fix the problem.

I’ll certainly file a bug report with Apple. I’ll also try to provide a pull request, but since I am fairly new to Github, some guidance would be appreciated.

**Comment by raoultrines** [comment]
I just filed a bug report with Apple, and I'll let you know what they say.

**Comment by raoultrines** [comment]
Right now, I do not have the time to learn how to submit an official 'pull request'. Therefore I provide a version of the "X11 forwarding" section of the FAQ, how i would like to see it. I hope someone else (@jeremyhu ?) will be able to insert this into the FAQ. (Note: formatting not always perfect.)

### ssh X forwarding debugging

You can forward X11 over an SSH connection by using either ‘ssh -X’ or ‘ssh -Y’. Since ‘ssh -X’ provides tighter security, it is preferred over ‘ssh -Y’; see the SSH manual.

If you are sshing to another system, be sure that remote server allows ssh forwarding. You may need to have an administrator edit that system’s sshd_config file.

The XQuartz installer should automatically setup SSH for xauth by editing ssh_config and sshd_config during its post-install script. Unfortunately, these two files are often overwritten during a macOS update, and the specific SSH settings that XQuartz needs are then lost. When that happens, X11 forwarding over SSH will suddenly fail with one of the following error messages:

ssh -X : “Warning: untrusted X11 forwarding setup failed: xauth key data not generated.”
ssh -Y : “Warning: No xauth data; using fake authentication data for X11 forwarding.”

This problem can be fixed as follows.

1. Start XQuartz, go to Preferences with "Cmd-, " and go to the Security tab. Enable the first option: “Authenticate connections".
2. Edit or create the file "~/.ssh/config" on the Mac and add these three lines:
```
# XAuthLocation added by XQuartz (https://www.xquartz.org)
Host *
    XAuthLocation /opt/X11/bin/xauth
```
3. Use 'chmod 600 ~/.ssh/config' to set the correct permissions for this file.
4. Use ‘ssh -X’ to connect to a remote server including X11.

In general, you can try these SSH troubleshooting steps. This list shows the expected behavior of the system.

local $ — refers to commands run on your local Mac

remote $ — refers to commands run on a remote Unix machine, of any type
```
[1] local $ echo $DISPLAY
/private/tmp/com.apple.launchd.UFeDJu0S1Q/org.xquartz:0
[2] local $ grep DISPLAY ~/.*rc ~/.login ~/.*profile ~/.MacOSX/environment.plist 2>/dev/null
[3] local $ grep -r DISPLAY /opt/local/etc /sw/etc /etc 2>/dev/null
[4] local $ ssh -X remote
[5] remote $ echo $DISPLAY
localhost:10.0
[6] remote $ grep X11 /etc/ssh/sshd_config ~/.ssh/*
X11Forwarding yes
X11DisplayOffset 10
```

Notes:

If step 1 returns :0, localhost:0 or anything similar, you have a configuration file that is overriding launchd’s $DISPLAY.

If step 2 outputs anything, it indicates that a configuration file in your home directory may be the culprit; try creating a new user and repeating the steps with that user.

If step 3 outputs anything, it indicates that a system-wide change was made that is overriding your environment. If it begins with /opt/local, it is MacPorts; if it begins with /sw, it is Fink. Otherwise, it is probably a commercial program that uses X11; contact your vendor for an updated version.

Step 4 should not return any error or warning messages. If you get any messages about ‘xauth’: see above. If you get any other messages: use ‘ssh -vvv -X remote’ to obtain more information.

If step 5 does not output anything, then step 6’s results probably include X11Forwarding no. In this case, you must fix the configuration on the remote side.

If step 5 outputs anything other than localhost:xx.0, then your remote configuration is overriding the DISPLAY environment variable set by sshd on the remote side.

**Comment by jeremyhu** [comment]
@raoultrines Can you please provide me the FB number of your report?

**Comment by jeremyhu** [comment]
And can you attach the copy of the file as an attachment ratehr than inline text, so I can just copy it in place rather than re-do formatting?  Thanks.

**Comment by raoultrines** [comment]
@jeremyhu I suppose you mean the report I submitted to Apple. It's FB9120923.

**Comment by raoultrines** [comment]
Here is a modified version of the file FAQs.md.
[FAQs_modified.md](https://github.com/XQuartz/XQuartz/files/6583756/FAQs_modified.md)

**Comment by raoultrines** [comment]
This version contains only ASCII characters (single and double quotes, dashes, etc.)
[FAQs_v2.md](https://github.com/XQuartz/XQuartz/files/6583810/FAQs_v2.md)

**Comment by jeremyhu** [comment]
Thanks.  I'm a bit busy this week, but I'll get this in soon!

**Comment by raoultrines** [comment]
I just upgraded my Mac to macOS Big Sur. XQuartz 2.7.11 still seems to work, without me doing anything. However, the date stamp of the files /etc/ssh/\*config has changed once again, so these files are definitely overwritten at every system update. It does not matter what the XQuartz 'postinstall' script does; the next system update will spoil it.

@jeremyhu: Did you get in touch with Apple about this issue? They did not respond at all to my bug report. Maybe they'll listen to you more, since you are an actual developer while I am a mere user.

**Comment by jeremyhu** [comment]
I have followed up on the bug internally and will try to work towards a solution.

**Comment by jeremyhu** [comment]
In the short term, I might just have privileged_startx do this instead of postinstall.

**Comment by raoultrines** [comment]
That would be great, thanks. You may also wish to consider setting `ForwardX11Timeout 0` to disable the 20 minute timeout on new X11 connections in a running session. Anything to make sure the users keep using 'ssh -X' and do not switch to 'ssh -Y'.

If it is any help: complaints about this issue started appearing on internet forums late 2016, while my colleagues first mentioned this to me in January 2017. This roughly coincides with the release of macOS Sierra.

**Comment by raoultrines** [comment]
Fixed a typo.
[FAQs_v3.md](https://github.com/XQuartz/XQuartz/files/6756580/FAQs_v3.md)

**Comment by chetstone** [comment]
@jeremyhu Please consider adding `X11Forwarding yes` to sshd_config in your postinstall script. It doesn't work for me without it.

Thanks

**Comment by jeremyhu** [comment]
Adding `X11Forwarding yes` needs to be done on the ssh server side.  So that would only fix cases of folks sshing into the system that installed XQuartz.  It is also a step that has security implications and not something that should be done by an installer script.
