### ISSUE TITLE
VIM +/* register not work with clipboard on remote server

### ISSUE THREAD

**Issue by CodeisCold** [XQuartz/XQuartz#175]
Local System: mac os Big sur 11.2.1
Remote System: ubuntu 18.04.2 LTS
XQuartz version: 2.8.1
Vim: `+clipboard` and `+xterm_clipboard` is enabled
Question: 
when connect remote server with `ssh -X`,  `+`/`*` register in vim not work with clipboard; `:reg` show `.` register which holds clipboard content, but can not put selection content in vim into `.` register.
After run `xclock` in same session, close it, and use vim again, every thing works fine, `.` register disappears too.
`ssh -X -vvv` show nothing different.

**Comment by jeremyhu** [comment]
I suggest reaching out to the vim authors to triage this.

**Comment by Leeeooooo** [comment]
same problem with me!! And when I  connect remote server with Windows and XcXsrv, every thing works fine!

**Comment by Leeeooooo** [comment]
@CodeisCold Have you solved this problem?
