### ISSUE TITLE
cannot open emacs on separate window in xQuartz

### ISSUE THREAD

**Issue by FabSalva** [XQuartz/XQuartz#176]
Hi, 

I have a MacBook Pro (13-inch, M1, 2020) and v 2.7.11 of xQuartz. I don't seem to be able anymore to open emacs (/opt/homebrew/emacs) on a separate window - it will only open on the same termina window from where I give the 'emacs' command on the command line. However, if I define an alias that points to the 'Emacs' App on my Mac (in teh 'Applications' folder), I can open emacs on a separate window. 
I tried to upgrade to the latest xQuartz (2.8), but it is even worse: when I try to call 'emacs' it comes with an error message saying that 'This program cannot run on this system, sorry' (both when I try to run the Emacs App or the emacs program in homebrew. 
Has anyone else encounter the same issue? Does anyone have any suggestion of a possible cause? Or am I just missing something in the configuration of xQuartz? 

Thanks a lot !

Fab

**Comment by jeremyhu** [comment]
This means you're opening emacs in terminal mode and not as an X11 application.  Please reach out to homebrew for this issue.
