### ISSUE TITLE
not seeing DISPLAY variable set for one user

### ISSUE THREAD

**Issue by bferrell** [XQuartz/XQuartz#177]
This is on Big Sur 11.14

One user gets:
echo $DISPLAY
/private/tmp/com.apple.launchd.UFeDJu0S1Q/org.xquartz:0
This is good.

And an existing gets:
echo $DISPLAY

This is bad

I've executed the following, per the FAQ, just to assure it's working
launchctl load -w /Library/LaunchAgents/org.xquartz.startx.plist

And checked for DISPLAY overrides (had THAT happen before)

Any thougts on how to shoot/correct this?
It happened after updating from 2.7 to 2.8.1

**Comment by jeremyhu** [comment]
1. For good measure, reboot after the `launchctl load -w /Library/LaunchAgents/org.xquartz.startx.plist`

2. Check the output of `launchctl getenv DISPLAY`  ... this is what launchd is setting as DISPLAY for processes it spawns, and that is what we expect to be set.  If that doesn't match 'echo $DISPLAY' then some startup script is unsetting it.

**Comment by bferrell** [comment]
Thanks again Jeremy!  

Something somewhere is doing an over ride, but it doesn't appear to be shell initialization. 
Your feedback lets me manually set DISPLAY correctly and work around until I can rebuild the user.

**Comment by jeremyhu** [comment]
You should be able to check `sudo launchctl procinfo <PID of Terminal.all>` you can look at the environment that launchd passed on to Terminal.  You should see a section with DISPLAY set correctly.  If it is set correctly there (which it sounds like it should be as it should match `launchctl getenv`), then it's definitely something in or below Terminal.app.
