### ISSUE TITLE
vi does not work for larger text files after big sur update

### ISSUE THREAD

**Issue by dwvasco** [XQuartz/XQuartz#178]
After the latest upgrade to big sur the vi text editor stopped working for files 
that are bigger than a few hundred lines long.  In particular, when I use the $ command to
move to the bottom of the file all the text in the window becomes scrambled.

I had to switch to the default mac terminal utility which still works, but now
I cannot use the xterm from xquartz.

**Comment by jeremyhu** [comment]
XQuartz does not distribute vi.  Please file a feedback report with Apple at http://bugreport.apple.com
