### ISSUE TITLE
uninstall instructions

### ISSUE THREAD

**Issue by crogers-rhino** [XQuartz/XQuartz#179]
I can't find uninstall instructions anywhere.  I'd like to remove all traces of xquartz from my computer please.  I have moved the application icon to the trash as well as removing some stuff from `~/Library/Application Support`.  I see that the `DISPLAY` variable is still being set in my environment.  I'd like to stop this please.  Apologies if this is documented somewhere, I can't seem to find it.  Any guidance is appreciated

**Comment by chaserogers** [comment]
ah nevermind i actually figure this out.  i had to remove the launch daemon and the launch agent.  might be helpful to document this somewhere, if it isnt already written down

**Comment by crogers-rhino** [comment]
ah nevermind i actually figure this out. i had to remove the launch daemon and the launch agent. might be helpful to document this somewhere, if it isnt already written down

**Comment by jeremyhu** [comment]
Yeah, this is included in the FAQ.
