### ISSUE TITLE
XQuartz windows can't be manipulated by Rectangle

### ISSUE THREAD

**Issue by jrejaud** [XQuartz/XQuartz#18]
Rectangle, https://rectangleapp.com/, is a macOS app which lets you move windows around using keyboard shortcuts.

It works on everything else, but it doesn't work with XQuartz:
https://github.com/rxhanson/Rectangle/issues/107

Have you considered making XQuartz compatible with Rectangle (this should also make it work on Spectacle and other macOS window manager apps)

**Comment by jeremyhu** [comment]
There are a lot of hacks in place to get X11 windows working with the system.  It's not likely going to happen with XQuartz as it is, but hopefully someone will continue the work of making an X11 compositor replacement in which this would work...
