### ISSUE TITLE
X11 forwarding very slow and strange colors for Matlab

### ISSUE THREAD

**Issue by Jann5s** [XQuartz/XQuartz#180]
<img width="1680" alt="Screen Shot 2021-06-03 at 10 59 14" src="https://user-images.githubusercontent.com/15977950/120617904-d683e180-c45a-11eb-96d3-9e9562fe8e17.png">

I'm trying to get X11 Forwarding to work from an ubuntu machine to my M1 MacBook (Big Sur 11.2.3 (20D91)). I've installed XQuartz 2.8.1 (xorg-server 1.20.11).

Looking at the output off "ssh -vvv" I can't seem to detect an issue:
```
debug2: x11_get_proto: /opt/X11/bin/xauth  list /private/tmp/com.apple.launchd.NhPB3kiaWr/org.xquartz:0 2>/dev/null
debug1: Requesting X11 forwarding with authentication spoofing.
debug2: channel 0: request x11-req confirm 1
```

However, most GTK windows open very slowly (taking about 60 seconds). I've tried (evince, nautilus, edit). But when they open they look fine. However when I open a Matlab window the colors are incorrect. I've included a screenshot which looks strange, but on my screen it even looks stranger than in the screenshot.

I have a feeling that I'm misconfigured something, or maybe that I need a different version of XQuartz for my M1

Can someone tell me where to start digging to try to solve this issue?

**Comment by jeremyhu** [comment]
#31
