### ISSUE TITLE
Download/Install of XQuatz 2.8.1 fails

### ISSUE THREAD

**Issue by code-rabbit** [XQuartz/XQuartz#184]
I tried to install XQuartz to the latest version on my Mac 10.15.7 (19H1217) ... but somehow it fails after few seconds ...
Any idea what is wrong ?

![XQuertz_fails](https://user-images.githubusercontent.com/20427440/121528607-ec197e00-c9fb-11eb-92cd-d5d4e13c0d2a.png)

**Comment by jeremyhu** [comment]
The file is hosted by github and seems to work for other folks.  Maybe a transient failure?
