### ISSUE TITLE
Issue w/ external displays and window size & position management

### ISSUE THREAD

**Issue by eblot** [XQuartz/XQuartz#185]
XQuartz 2.8.1 (xorg-server 1.20.11) on macOS 11.4 (20F71) is not able to recover from screen shutdown with multiple external displays.

I'm not sure about the actual configuration that causes trouble. I'm using a MBP Intel 2020 with 2x 4K external display (one HDMI, on DisplayPort). When the computer is left unused for a while, screen saving kicks in so external displays go to sleep. The computer stays powered up by the external adapter, and "Prevent computer from sleeping automatically when the display is off" is enabled, i.e. the Mac does not enter deep sleep.

When opened app in XQuartz is restored, I'm using a remote SSH session for Sublime Merge as the unique X11 app here, its window either:
 - does not appear, or
 - appear on the internal display while it was previously shown one of the 4K display

First issue here is that the wrong display is used. It would not be a bug deal if ... the size of the window were updated, but it is not: the original window size is preserved, which means it is far larger than the internal display capabilities. 

The second issue is that only the bottom half of the window is shown, and left and right sides are cut off, as the window is not resized.

This lead to the third issue as I'm unable to either move or resize this window. There is no handle to move it (top bar is not displayed so it cannot be moved, bottom right corner is not displayed so it cannot be resized). There's no way to move/resize it, which is a big issue - there may be some existing shortcut to do it, but I have yet to find it/them :-)

The forth issue is that for some reason, the XQuartz window is the only one in the system I cannot move from one display to another using the Magnet (v2.6.0) app: when XQuartz is selected, all Magnet actions are disabled/greyed. It seems it does not behave as other windows.

The fifth issue is that if I closed the X11 app and XQuartz keeps running, if I restart the app from the same - or another - SSH session, the app window is restored ... to the same display, with the same dimension: the app is not resized to the actual display capabilities, so closing/restarting the app is not an option to workaround this issue.

I'm not sure what is the best way to leave this loophole, but any piece of advice is welcomed.

Thanks.

**Comment by CataRay** [comment]
I am having the same issue when using multiple displays.
Any solutions?

**Comment by eblot** [comment]
The only workaround I found up to now is to invoke Mission Control (F3 key) so that X-windows become visible. It is therefore possible to move them around and find a position that once Mission Control view is cancelled, it is possible to move or resize the windows.

It is barely usable, but at least it is possible to recover from this crazy state.

**Comment by jeremyhu** [comment]
#92

**Comment by XPOL555** [comment]
a possible workaround seems also to go to system settings, desktop & dock and **uncheck** the option "displays has separated spaces"; it requires logout/login and in this way you'll have the same "space" shared between every display so might not be ideal solution if you like to have separated spaces per each display/monitor

https://developer.apple.com/documentation/appkit/nsscreen/screenshaveseparatespaces
https://macos-defaults.com/mission-control/spans-displays.html
