### ISSUE TITLE
xQuartz doesn't launch correctly on Big Sur

### ISSUE THREAD

**Issue by recursive68** [XQuartz/XQuartz#187]
Try to run it and it launches in Dock, "bounces" and then closes. Any ideas why it's doing this. Used to work with a very old version.

**Comment by jeremyhu** [comment]
You have not provided much data, so I cannot know for certain, but this sounds like maybe your $DISPLAY envvar is not correct.  Be sure you have only one startx LaunchAgent loaded (ie: unload the one from MacPorts if you have it installed), install XQuartz 2.8.2, and reboot your system.
