### ISSUE TITLE
Two different screen sizes make some applications unusable

### ISSUE THREAD

**Issue by AndreasFMueller** [XQuartz/XQuartz#188]
I use XQuartz with two displays of different size attached to my MacMini: a 1920x1080 display on the left and an a 30" cinema display with resolution 2560×1600 on the right. They are aligned at their lower borders because the stands for those monitors are about the same height.

XQuartz constructs a single 4480x1576 display from this. Of this large area, the top left 1920x496 rectangle is not visible and not accessible with the pointer. If an application opens a Window with the top bar in this area, it becomes impossible to move the window around. E.g. when I log in via ssh to a raspberry pi to run mathematica, then the mathematica help function opens a chromium browser in such a way as to make help unnavigable. If the window is not very high, it will not even be visible.

I could of course configure the monitors to be aligned along the top border in settings, but that would be very confusing because they physically are not aligned that way. It would result in a rectangle in the lower left corner to be inaccessible.

I agree that creating a single large virtual screen is the best solution if the screens have the same height. However, for setups like mine, it simply does not work. I suggest this be resolved in one of the following ways:
1. Give the user an option in the XQuartz settings where he can specify which monitors should actually be used for the X11 display. This ways I could configure XQuartz to use only the Cinema display.
2. Give the user an option in configuration where he can specify that separate monitors should be treated as different X11 screens of the same X11 display. It should be possible to specify which monitor is :0.0 and which one is :0.1.

Solution 1 would be good enough for me because the Cinema display is my main work surface anyway, the smaller display is mainly used for mail, youtube, music and the occasional documentation page. Working in X11 usually is "real work"...
Solution 2 would allow to use all available screen area but it is somewhat more complicated to implement and to use.

**Comment by nbriggs** [comment]
+1 for doing *something* about this -- I think I'd prefer option 2, though.  I'd be even happier with option 2 if I could drag X11 windows from one display to the other... I don't remember whether classic X11 implemented that.

**Comment by jeremyhu** [comment]
Those are great ideas for anyone interested in implementing a solution.  IMO, moving to a compositing WM (or a Wayland compositor + Xwayland) would be better.

**Comment by jeremyhu** [comment]
#92
