### ISSUE TITLE
Submitting minor patches to xinit/startx?

### ISSUE THREAD

**Issue by gaelicWizard** [XQuartz/XQuartz#189]
I'd like to submit some small tweaks to startx and related, but the XQuartz org doesn't have a repo for xorg-xinit. Since they're Mac-specific, I figure I should go through here? How should I go about that?

I've alsö got some other fixups I'd like to try out with xinit, launch_startx, &c

**Comment by eddieh** [comment]
This is not an authoritative answer, but it looks like those changes would go to the upstream (freedesktop.org) projects unless they're XQuartz build related changes in which case those are maintained as a serious of patches in this repo.
