### ISSUE TITLE
Backend server won't start (keeps crashing)

### ISSUE THREAD

**Issue by pmidford** [XQuartz/XQuartz#196]
Hi,
     I am running MacOS 11.5 and just uninstalled and reinstalled XQuartz 2.8.1_1.  I have been unable to get XQuartz to run since I got a new Mac several weeks ago (was running successfully with some version of Catalina on the old machine).  When I check the System console, it reports the following:

Aug 12 09:52:45 AICCAS027Spence com.apple.xpc.launchd[1] (org.xquartz.privileged_startx[1199]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): org.xquartz.privileged_startx
Aug 12 09:52:46 AICCAS027Spence com.apple.xpc.launchd[1] (application.org.xquartz.X11.11429167.11429175[1180]): Service exited due to SIGABRT
Aug 12 09:52:48 AICCAS027Spence com.apple.xpc.launchd[1] (org.xquartz.startx): Service only ran for 4 seconds. Pushing respawn out by 6 seconds.

Any ideas how to debug this problem.  [Note  I also mentioned this issue on the Xquartz IRC, it's the same problem]

Thanks,
Peter Midford

**Comment by jeremyhu** [comment]
Closing due to lack of response.
