### ISSUE TITLE
Migrate to using eddsa to sign sparkle updates

### ISSUE THREAD

**Issue by opoplawski** [XQuartz/XQuartz#199]
Why ship the .pkg inside a .dmg?  It just adds another layer.  If you just shipped a .pkg I could download and install that automatically.  Thanks.

**Comment by jeremyhu** [comment]
Because this is what Sparkle expects.

**Comment by zorgiepoo** [comment]
This isn't true for >= Sparkle 1.26 which I believe XQuartz uses. See [Sparkle's package updates](https://sparkle-project.org/documentation/package-updates/) for more notes.

**Comment by jeremyhu** [comment]
Correct.  But we need to support much older versions of Sparkle.

**Comment by zorgiepoo** [comment]
There's a balance of compatibility and developer-required work here, and several ways to look at this.

For example one approach the documentation specifically notes is switching to a new appcast in a new update which guarantees that apps that use that new appcast are on a recent version of Sparkle. So those versions can be provided the modern pkg, so to say. (this isn't specific to bare pkgs, just for adopting new appcast features in general)

Another lesser-sound approach is switching to .pkg eventually when you acknowledge within a long / reasonable amount of given "window", that most users that would have updated from a pre 1.26 version have already done so.

Another approach is realizing that the website provided download doesn't have to be the same as the ones provided for software updating (in fact this is sometimes not the case, for example for a normal app dmg may be more suited for website delivery, but tar.* or zip is more efficient for updating)

This requires either giving up some compatibility, or putting in more work, but it's not an unsolvable problem. If it's worth it for the small user experience gain for this project is not my call though.

**Comment by jeremyhu** [comment]
I'm going to update 2.8.2 to use a new appcast URL with the next beta, but I'll be posting through 2.8.2 in the old appcast as well.

**Comment by jeremyhu** [comment]
Hitting some issues transitioning to EdDSA -- https://github.com/sparkle-project/Sparkle/discussions/2160

**Comment by jeremyhu** [comment]
WIP on https://github.com/XQuartz/XQuartz/tree/eng/PR-199

**Comment by jeremyhu** [comment]
The milestone here is 2.8.2, but it's really the 2.8.3 release that will be the first one that is delivered this way.  2.8.2 sets us up with the new feeds to enable this.
