### ISSUE TITLE
Problems after upgrading to Xcode 11.1 on Mojave

### ISSUE THREAD

**Issue by alehyze** [XQuartz/XQuartz#2]
Hi,

I am writing some code to run on Xquartz with xcb and  OpenGL. It's a command line tool in C. Everything was ok.

Since when I upgraded to Xcode 11.1 I get the following error when running the tool and then it crashes:

dyld: Library not loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  Referenced from: /opt/X11/lib/libXplugin.1.dylib
  Reason: Incompatible library version: libXplugin.1.dylib requires version 1.0.0 or later, but OpenGL provides version 0.0.0

I am not linking directly to libXplugin.

Does anyone know how to deal with this?

**Comment by jeremyhu** [comment]
What's the output of `otool -L /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL` ?  That doesn't seem right.  I suggest asking for help on the mailing list.  This isn't an XQuartz bug.
