### ISSUE TITLE
X11 forwarding not working on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by Rajrup** [XQuartz/XQuartz#20]
I am trying to connect to Ubuntu server from my macbook using xterm and forward **gedit** window, but it throws error:

> Unable to init server: Could not connect: Connection refused
> 
> (gedit:31531): Gtk-WARNING **: 22:13:14.983: cannot open display:

My server configurations are fine because I can perform x11 forwarding using another Ubuntu machine to the Ubuntu server. It doesn't work from my macbook. 
I tried with XQuartz 2.7.11 from the https://www.xquartz.org/ and brew install.

**Comment by zigg** [comment]
The message you shared suggests to me `DISPLAY` isn't set on your Mac. I needed to log out and log back in to get it set.

If you run `echo $DISPLAY` in a terminal, what do you see?  e.g.

```
% echo $DISPLAY
/private/tmp/com.apple.launchd.XXXXXXXXX/org.macosforge.xquartz:0
```

In a pinch, you can also run Applications → Terminal (⌘N) from XQuartz, which will open an xterm for you—`DISPLAY` should be properly set inside there.

**Comment by jeremyhu** [comment]
It should work if you use macOS's ssh or ssh from MacPOrts.
