### ISSUE TITLE
XQuartz on MacBook with M1 chip unable to correctly display X11 forwarding

### ISSUE THREAD

**Issue by Yasinli1028** [XQuartz/XQuartz#200]
I am using the same version of macOS (11.5.2) and XQuartz (2.8.1) on my two computers. One is an iMac with an Intel chip and the other one is MacBook with an M1 chip. XQuarze on iMac can successfully display X11 forwarding while not on the M1 chip. XQuartz on the M1 can forward GUI windows but it flips the color and contrast of the window. For example, white color in GUI displays black and it is impossible to control the GUI smoothly. Does anyone encounter the same issue as mine?

**Comment by jeremyhu** [comment]
Closing as dupe.
