### ISSUE TITLE
Why XQuartz stopped updating new version?

### ISSUE THREAD

**Issue by Jeoren** [XQuartz/XQuartz#21]
Hi everyone, I am new to XQuartz. 

But I started to use it daily with SSH to connect to the server in my company.
On the website https://www.xquartz.org, I see that the last stable version is 2.7.11, which was released on 2016-10-29. 

I am just wondering why there is no new release within these 4 years?

**Comment by eabolden** [comment]
Look at MacPorts for a current working version.

https://ports.macports.org/port/xorg/summary

https://ports.macports.org/port/xorg-server/summary

**Comment by securingmom** [comment]
XCode is a big ask on a non-developer machine though @eabolden .  Is there not another simple option?   I only want to use G'MIC on GIMP
https://github.com/aferrero2707/gimp-plugins-collection

**Comment by jeremyhu** [comment]
Because I had kids and nobody stood up to take over making releases ;)
