### ISSUE TITLE
add homebrew instructions

### ISSUE THREAD

**Issue by rdp** [XQuartz/XQuartz#210]
Might be nice to add homebrew install instructions, for those of us bereft of MacPorts
Sadly it's not named xorg so the MacPorts instructions aren't much guidance.

This page:
https://www.xquartz.org/releases/index.html

brew install --cask xquartz

**Comment by jeremyhu** [comment]
Can you send a pull request with your suggested changes to https://github.com/XQuartz/xquartz.github.io ?

**Comment by rdp** [comment]
Thanks everyone!

On Monday, November 8, 2021, Jeremy Huddleston Sequoia <
***@***.***> wrote:
> Closed #210.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci5.googleusercontent.com/proxy/en5WsrYVbhWXhf3egNOpz1t416BQFtR034EDqfHRlj_Lykne871goVg__whwLAjQ54eAARVfAAtOcKtxX4luUI-kgNhxJbymnSt6N6AfvUZ6C_0l4oiaWWXpuOKYD5Jdj7TDv7V8HPeR3bbS2Xm06xoX14i6b7BO1o0CEaQEDNjVMQ8Iz1HgoQbV1lwSqmoQjHBSEeQzOkLe7SEtQ-ic3OjWq9hcsc130rIrNQ-KwaXkEviPb3Dh5AmUkTzCvWpc5dUzajc=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUF35K6TKARE77ZFGXTULCWKZA5CNFSM5EPFI4BKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGPAAAAAAKNA6Y3O.gif>
