### ISSUE TITLE
Issue with XQuartz & legacy X forwarding

### ISSUE THREAD

**Issue by mzryz** [XQuartz/XQuartz#22]
Firstly I just want to say this isn't about indirect rendering or iglx etc ... The team over at sgi.sh have been trying to get X11 forwarding working on SGI IRIX > MacOS for a while without luck. First was the iglx issue which we worked out, but secondly there seems to be an issue with Xinerama and its interaction with XQuartz. After doing research into this issue, it seems to have been a consistent bug for almost 15 years (I will provide references at the end)

`X Error of failed request: BadWindow (invalid Window parameter) Major opcode of failed request: 128 (XINERAMA) Minor opcode of failed request: 1 (XINERAMAGetState) Resource id in failed request: 0xa9010000 Serial number of failed request: 760 Current serial number in output stream: 760` 

This error presents when running 'certain' applications over Xforwarding, notably ones with more complex GLX requirements, like the window manager in Irix that uses vector icons etc. It doesn't seem to be related to indirect rendering, but it does require indirect rendering to be working correctly. We currently have Mac users forced to run Linux VM's on their glorious MacOS in order to use Xforwarding... the horror! :)

I hope this is something the team here might be able to look in to? Thanks

Our forum thread on the issues: https://forums.sgi.sh/index.php?threads/x11-forwarding-adventures.383/

Here are a few historical links to this issue constantly cropping up:
2004: http://sunmanagers.cs.toronto.edu/2004/5331.html
2007: https://discussions.apple.com/thread/1101676
2010: https://lists.apple.com/archives/X11-users/2010/May/msg00010.html

**Comment by dillera** [comment]
The current alphas and beta seem to have fixed this issue. Xnest working great with my octane and fuel running 6.5 now with this latest update. This has been broken for years. Using this perfectly in Big Sur now without any issues!

Thanks XQuartz devs!

**Comment by dillera** [comment]
Works for Intel and Apple Silicon

https://imgur.com/NqjFREh.png

https://i.imgur.com/wffN1Lr.png

**Comment by jeremyhu** [comment]
Ok, great.  Thanks for reporting.  I'll close this out then.  I was not looking forward to digging into this =)
