### ISSUE TITLE
xterm won't launch

### ISSUE THREAD

**Issue by konsta61** [XQuartz/XQuartz#221]
Hello,

I'm running XQuartz 2.8.1 on macOS 12.0.1. XQuartz starts OK and I can run various X programs, like xman etc.
However, xterm does not launch properly. There is no new window after running xterm from command line, nor from XQuartz Application menu. 

If I start xterm from command line the 'ps' shows that there are two xterm instances and if I kill either, they both disappear.

If I start xterm from Application menu nothing happens, but 'ps' shows that there is one xterm. If I kill the xterm instance I get blank xterm window which does not respond to anything and 'ps' does not show any xterms any more.

I have opened a question on "apple.stackexchange.com" forum too, but it is marked as duplicate because similar question was made some six years ago:

[the-xterm-launches-ok-on-freshly-rebooted-machine-only](https://apple.stackexchange.com/questions/430341/the-xterm-launches-ok-on-freshly-rebooted-machine-only)

Cheers, Timo

**Comment by konsta61** [comment]
It seems, that on freshly booted machine just after login the xterm is able to open a window. But after awhile no new windows can be opened. At least Android Studio triggers this behaviour.

**Comment by konsta61** [comment]
Oops, accidentally closed the issue. :)

**Comment by konsta61** [comment]
The same problem is described here:

https://apple.stackexchange.com/questions/224929/why-xterm-would-run-only-once-on-xquartz/430290#430290

**Comment by raoultrines** [comment]
Hi Timo,

Do you really need the xterm? I myself launch all my X11 applications from the MacOS Terminal app. You see, according to the XQuartz FAQ, the contents of the DISPLAY variable should look something like this:

    $ echo $DISPLAY
    /private/tmp/com.apple.launchd.UFeDJu0S1Q/org.xquartz:0

This should mean that every attempt to access the X11 display on the Mac should cause launchd to start XQuartz if it isn't already running. In practice, every X11 application that I start from a normal MacOS Terminal starts XQuartz for me automatically. This includes `ssh -X`, provided that XAuthLocation has been set correctly, see #174 .

As a result, I stopped using the XQuartz xterm years ago. If it would disappear, I would not even miss it.

**Comment by konsta61** [comment]
Hello, as a matter of fact, I don't need xterm anymore. I solved the problem using plain old OSX Terminal. 👍 

Let me be more specific:

I'm developing an embedded software and I'm using Segger to debug the code. The debug session consist of two windows on my Mac, the server and the client. Both are needed to display the debug messages from the embedded device.

In the Makefile I have target to launch two windows (formerly xterm and currently OSX Term). The Segger server is started in one window and the Segger client in the other window.

Opening the windows from the Makefile was very handy with xterm, like this:

The server:
`xterm -bg white -fg black -geometry 80x8+10+10 -e bash -c 'JLinkExe ... ; exec bash' > /dev/null 2>&1 &`

The client:
`xterm -bg blue -fg white -geometry 120x80+10+10 -e bash -c 'JLinkRTTClient ; exec bash' > /dev/null 2>&1 &`

This is what I'm still doing from the Makefile in my Linux box. JLinkExe is the Segger server binary and JLinkRTTClient is the Segger client binary.

While on my Mac I had to create a special "Term profiles" which I'm opening from the Makefile like this:

Server:
```
echo "JLinkExe ..." > $(JLINK_SCRIPT)
chmod 700 $(JLINK_SCRIPT)
open $(JLINK_EXE_TERM)
```

Client:
`open $(JLINK_RTT_CLIENT_TERM)`

Where $(JLINK_EXE_TERM) and $(JLINK_RTT_CLIENT_TERM) are Makefile variables for the Segger server and client "Term profiles" respectively.

The server "Term profile" is set to run the $(JLINK_SCRIPT) shell script.

**Comment by jeremyhu** [comment]
What is $DISPLAY set to?  What if you execute /opt/X11/bin/xterm (just in case something else is in $PATH...

Please ask for support in the mailing lists as this is for reporting bugs.

**Comment by konsta61** [comment]
Hmm...

$DISPLAY and $PATH are OK. Otherwise xterm wouldn't start in the first place.

**Comment by jeremyhu** [comment]
You said that you couldn't launch xterms after a while... so I want to know what your DISPLAY is when you cannot launch.  If it is something like "localhost:10" that might indicate you are trying to forward through an ssh connection and are likely hitting the timeout in ssh.

**Comment by jeremyhu** [comment]
And when it fails, what happens?  Does it exit?  What is the exit code?  Does it print out any errors?  Does it hang?

**Comment by konsta61** [comment]
```
tke@Timos-iMac-Pro ~ % echo $DISPLAY
/private/tmp/com.apple.launchd.joQszkZwSx/org.xquartz:0
```

```
tke@Timos-iMac-Pro ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/Nordic Semiconductor/bin/
```

```
tke@Timos-iMac-Pro ~ % which xterm
/opt/X11/bin/xterm
```

```
tke@Timos-iMac-Pro ~ % xclock &
[3] 19233
Warning: locale not supported by Xlib, locale set to C
Fontconfig warning: ignoring UTF-8: not a valid region tag
tke@Timos-iMac-Pro ~ % 
```

[ xclock pops up OK ]

```
tke@Timos-iMac-Pro ~ % xterm
Warning: locale not supported by Xlib, locale set to C
^Z
zsh: suspended  xterm
```

```
tke@Timos-iMac-Pro ~ % ps aux | grep xterm
tke              18679   0.0  0.0 34288640    860 s001  Ss+  11:19AM   0:00.00 /opt/X11/bin/xterm
tke              18507   0.0  0.0 34287356   4188   ??  S    11:19AM   0:00.03 /opt/X11/bin/xterm
tke              18719   0.0  0.0 34253900    952 s000  S+   11:20AM   0:00.00 grep xterm
tke              18685   0.0  0.0 34419712    840 s003  Ss+  11:19AM   0:00.00 xterm
tke              18684   0.0  0.0 34410236   4296 s000  T    11:19AM   0:00.02 xterm
```

```
tke@Timos-iMac-Pro ~ % xterm &
[2] 19046
tke@Timos-iMac-Pro ~ % Warning: locale not supported by Xlib, locale set to C
```

```
tke@Timos-iMac-Pro ~ % ps aux | grep xterm
tke              18685   0.0  0.0 34419712    840 s003  Ss+  11:19AM   0:00.00 xterm
tke              18684   0.0  0.0 34410236   4296 s000  T    11:19AM   0:00.02 xterm
tke              18679   0.0  0.0 34288640    860 s001  Ss+  11:19AM   0:00.00 /opt/X11/bin/xterm
tke              18507   0.0  0.0 34287356   4188   ??  S    11:19AM   0:00.03 /opt/X11/bin/xterm
tke              19055   0.0  0.0 34253900    952 s000  S+   11:27AM   0:00.00 grep xterm
tke              19047   0.0  0.0 34279424    848 s005  SNs+ 11:27AM   0:00.00 xterm
tke              19046   0.0  0.0 34279164   4316 s000  SN   11:27AM   0:00.02 xterm
```

**Comment by jeremyhu** [comment]
You should also setup your locale correctly.

**Comment by jeremyhu** [comment]
In the failing case, xterm is blocked in a write(2) syscall.

What version of XQuartz are you using here?

**Comment by konsta61** [comment]
XQuartz 2.8.2_beta2 (xorg-server 1.20.14)

**Comment by jeremyhu** [comment]
xterm[0x10005b6b3] <+4819>: callq  0x10005cdb0               ; spawnXTerm at main.c:3735
    xterm[0x10005b6b8] <+4824>: movl   $0x14, %edi

So that's odd that we see `write` rather than `spawnXTerm` in the backtrace.  That could be explained by a tail call optimization in spawnXterm() calling write() (or calling something that calls write), but I don't see any tail call optimizations in spawnXterm (and this was a beta build, so built with -O0 anyways...)... peculiar.

This is the only write() that seems like it could potentially be tail-call optimized away.

My next step would be to connect to the process with a debugger, figure out what fd we're trying to write to, and then figure out why it's blocked.

---

Does the issue go away if you quit and relaunch XQuartz?  If not, what about if you logout and log back on?  Or do you really need a full reboot?

Can you collect a sysdiagnose focused on the problematic xterm process (eg: `sudo sysdiagnose -q <pid>`) when in this state and send it over in an Apple Feedback Report (using Feedback Assistant)?  Include the FB# here and also include a link to this issue in the report.

**Comment by konsta61** [comment]
Is there any news concerning this issue?

**Comment by jeremyhu** [comment]
Nope, and just the one report.  It would be helpful if you could debug it a bit further as I mentioned above.

**Comment by konsta61** [comment]
What do you mean by "debug it a bit further" ? I already issued Feedback Report. What else do you need?

**Comment by jeremyhu** [comment]
Since only your system is exhibiting the problem, I suggest you follow my " next steps" above:

connect to the process with a debugger, figure out what fd we're trying to write to, and then figure out why it's blocked.

**Comment by konsta61** [comment]
There are other people suffering with the (same?) problem:

https://apple.stackexchange.com/questions/224929/why-xterm-would-run-only-once-on-xquartz

**Comment by jeremyhu** [comment]
That link indicates that there are at last a couple people over the past 7 years that have seen something similar to what you are experiencing... but still, there's nothing I can do based on the information here.  If you're able to debug the situation and determine if it's a bug somewhere in X11-land, I'll happily point you in the right direction to getting it fixed.  As it is now, all I can see is that we're waiting on a read() syscall that we think should not be blocking.  The only way to dig deeper is with a live repro.

**Comment by hfath** [comment]
Ahh, finally at the right place!

This started for me many moons ago on 10.6 -- coincidentally, after I took out a Kerberos ticket.

Through system updates (10.6 -> 10.12 -> 10.13 on this MBP 2011), re-installing the OS, {de,re}installing Xquartz, testing with a new user, I always have about ten minutes after a reboot where I can create a stash of local xterms. Then, it's game over. Other local X clients are not a problem, nor are any remote clients.

**Comment by jeremyhu** [comment]
I wonder if there is something similar about your two configs... kernel extensions, preferences, etc.  I'm at a loss, sorry...

**Comment by konsta61** [comment]
Looks much better now on:

XQuartz 2.8.2 (xorg-server 1.20.14)
macOS Version 13.2.1 (22D68)

xterm launches OK from XQuartz -> Applications -> Terminal
as well as from any terminal (xterm or iTerm2) using:  xterm&

**Comment by jeremyhu** [comment]
Ok.  Not sure what happened or why this works now... ¯\_(ツ)_/¯
