### ISSUE TITLE
"Error: couldn't get an RGB, Double-buffered visual" with Xquartz 2.8.1 on M1 macOS 12

### ISSUE THREAD

**Issue by matthiasschroder** [XQuartz/XQuartz#222]
When running glxgears on a centos 7 box with display set to M1 based Mac with macOS 12 glxgears aborts with 

Error: couldn't get an RGB, Double-buffered visual

Having the display on an Intel based Mac with macOS 12 and Xquartz 2.8.1 works fine.

Any idea what might be wrong?

**Comment by patricorgi** [comment]
I created a post at StackExchange site. 

https://unix.stackexchange.com/questions/676862/glxgears-gives-error-couldnt-get-an-rgb-double-buffered-visual-on-one-remote

**Comment by jeremyhu** [comment]
#144

**Comment by matthiasschroder** [comment]
Hi Jeremy,

can you let me know what is the relation of this ticket to https://github.com/XQuartz/XQuartz/issues/144? In #144 I see plenty of errors mentioned, it is all but clear to me whether these are related. And I see no solution...

**Comment by jeremyhu** [comment]
This is a dupe of #144, which tracks IGLX not functioning very well...
