### ISSUE TITLE
Missing font in macOS 12.0.1 causing issues?

### ISSUE THREAD

**Issue by clmccall** [XQuartz/XQuartz#226]
Hello,
I'm running macOS 12.0.1 and XQuartz 2.8.1 and I get the following error when trying to open gaia through Starlink,

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  45 (X_OpenFont)
  Value in failed request:  0x60015d
  Serial number of failed request:  1742
  Current serial number in output stream:  1743

Any suggestions on how to fix this? X programmes seem to work (xterm, xclock, xeyes etc) and I didn't have this error on older versions of macOS, if that information is useful.

Thanks!

**Comment by rin67630** [comment]
I am getting in Mojave 10.14 this when trying to open Wine fater having installed the XQuartz package and the Wine stable package, both downloaded today:

Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org

**Comment by JKomp** [comment]
I was getting the same issue with Mojave and XQuartz 2.8.1. Reverted back to 2.7.11 and problem was resolved. Perhaps Mojave is looking for the fonts in a different place?

**Comment by clmccall** [comment]
Thank you both for your responses. Reverting back to 2.7.11 did the trick, and it looks as though 2.8.0 also works. Just not 2.8.1!
