### ISSUE TITLE
Problem with printenv DISPLAY

### ISSUE THREAD

**Issue by jesa974** [XQuartz/XQuartz#228]
After installing xQuartz using `brew install xquartz`, I just had the output "Successfully installed"
So, I tried to launch my app remotly but it didn't work ...

I tried `printenv DISPLAY` and .... nothing

I think it could be a good idea to avoid the user that he needs to restart his computer before doing anything else because the environnement variable DISPLAY is empty while the user does not restart his computer.

**Comment by jeremyhu** [comment]
The installer forces you to logout.  If Homebrew somehow bypasses that, then that sounds like a Homebrew bug.  The installer is configured correctly.
