### ISSUE TITLE
Caps lock is reversed in Xterm

### ISSUE THREAD

**Issue by biancardi** [XQuartz/XQuartz#232]
I must have done something really stupid on my Mac - but in the last week, I noticed that when I have caps lock off in xterm, the characters are all in upper case.  When I turn on caps lock in xterm, it is all in lower case.   

when I am not in xterm, my caps lock key works normally. Please help, I tried looking this up and I cannot find anyone else who has this issue.

thank you

michele

**Comment by jeremyhu** [comment]
Odd.  It seems to be working fine for me...

**Comment by raoultrines** [comment]
You can also start X11 applications from a normal MacOS Terminal, see #221 . This way, you don't need the XQuartz xterm at all. I myself stopped using it years ago.

**Comment by nkizz** [comment]
It's also working fine for me, are you using any external keyboards or other input peripherals? What model of Mac are you using?

**Comment by biancardi** [comment]
after rebooting several times, it resolved itself.  so weird
thank you for all of your suggestions and help
