### ISSUE TITLE
XQuartz fails to compile with supplied scripts. 

### ISSUE THREAD

**Issue by lbibass** [XQuartz/XQuartz#234]
I'm attempting to build XQuartz locally on my machine in order to test Zink on macOS. When attempting to compile XQuartz on my machine, it fails with the error message 

```configure: WARNING: dot not found - doxygen targets will be skipped
checking for check >= 0.9.6... no
checking for xcb-proto >= 1.14... no
configure: error: Package requirements (xcb-proto >= 1.14) were not met:

Variable 'PYTHON_PREFIX' not defined in '/opt/X11/lib/pkgconfig/xcb-proto.pc'

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XCBPROTO_CFLAGS
and XCBPROTO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
++ pwd
+ die 'Could not configure in /Users/lbibass/git/XQuartz/src/xorg/lib/libxcb'
+ echo 'Could not configure in /Users/lbibass/git/XQuartz/src/xorg/lib/libxcb'
Could not configure in /Users/lbibass/git/XQuartz/src/xorg/lib/libxcb
+ exit 1
```

Amy ideas on what is happening here? I've tried building it in a fresh virtual machine as well. No go. Same exact error code.

**Comment by hutm** [comment]
same problem for me. Apple M1 chip.

**Comment by jeremyhu** [comment]
I think you need to install python.  You should be able to use the install-or-update-macports.sh script in the repo to setup the build environment.

**Comment by lbibass** [comment]
I had already done that.

**Comment by jeremyhu** [comment]
Ok, well if you can fix the script, please send a pull request... otherwise, I'll take a look at it the next time I have some time to work on this...

**Comment by jeremyhu** [comment]
Yeah, reproduced.  Something seems to have changed in MacPorts... =/

**Comment by jeremyhu** [comment]
If I used the /opt/buildX11 install that I have on my system (presumably leftover from 2.8.1's release), I can build fine... so that confirms it's something related to changes in that area that is tickling this...

**Comment by jeremyhu** [comment]
According to https://github.com/macports/macports-ports/commit/f28c3f1454912c5cdee68f5613ef2f9e1d8b35d0, it looks like this is a regression from automake 1.16.4
