### ISSUE TITLE
How to automatically launch  xquartz

### ISSUE THREAD

**Issue by jacksparrow601** [XQuartz/XQuartz#235]
Hey guys, thanks for viewing my question. I am a freshman about linux and Mac terminal. And I am not native speaker.
Here is my question. I try to input
 $ xeyes(to test XQuartz installed or not)
,but the problem is I can only successfully execute the command "$ xeyes" after I open xquartz. If I do not open XQuartz background, the output information would only be"can't open display"
I spend a long time searching solution. So I change execute "export DISPLAY=0.0" and add this command to my .zprofile(bash_profile). But I still need to open xquartz firstly.
And I am using MacBook 14 m1pro chip.
Thank you so much, if you have any advice. I am also learning the basic linux.

**Comment by raoultrines** [comment]
Hi Jack, I think your DISPLAY value is set incorrectly.

According to the XQuartz FAQ, the contents of the DISPLAY variable should look something like this:

    $ echo $DISPLAY
    /private/tmp/com.apple.launchd.UFeDJu0S1Q/org.xquartz:0

This should mean that every attempt to access the X11 display on the Mac should cause launchd to start XQuartz if it isn't already running. Note that the XQuartz installation should do this for you automatically, without you having to tinker with it.

On my Mac (Intel MacBook Pro, MacOS Monterey 12.1, XQuartz 2.7.11), I managed to get what you seem to want: every X11 application that I start from a normal MacOS Terminal starts XQuartz for me automatically. This includes `ssh -X`, provided that XAuthLocation has been set correctly, see #174 . But that's under the condition that the DISPLAY variable is set correctly.

**Comment by jacksparrow601** [comment]
> Hi Jack, I think your DISPLAY value is set incorrectly.
> 
> According to the XQuartz FAQ, the contents of the DISPLAY variable should look something like this:
> 
> ```
> $ echo $DISPLAY
> /private/tmp/com.apple.launchd.UFeDJu0S1Q/org.xquartz:0
> ```
> 
> This should mean that every attempt to access the X11 display on the Mac should cause launchd to start XQuartz if it isn't already running. Note that the XQuartz installation should do this for you automatically, without you having to tinker with it.
> 
> On my Mac (Intel MacBook Pro, MacOS Monterey 12.1, XQuartz 2.7.11), I managed to get what you seem to want: every X11 application that I start from a normal MacOS Terminal starts XQuartz for me automatically. This includes `ssh -X`, provided that XAuthLocation has been set correctly, see #174 . But that's under the condition that the DISPLAY variable is set correctly.

Thank you for your reply.  Actually, I reinstall xquartz2.8 for several times. I use the brew install xquartz, and it installs the latest version. But it didn't automatically set the DISPLAY like yours /private/tmp/com.apple.launchd.UFeDJu0S1Q/org.xquartz:0. After I execute echo $DISPLAY , the terminal just output blank space.  I am still confused, what should I do next. May be install the XQuartz 2.7.11 version?

**Comment by raoultrines** [comment]
I installed XQuartz 2.7.11 using the package from the XQuartz website. I did not use Homebrew for this. The installation package also contains a post-install script that may set things like DISPLAY for you, unlike the Homebrew installation. Maybe @jeremyhu should also know about this.

**Comment by jeremyhu** [comment]
The launchd.plist is what sets DISPLAY.  You need to logout / login. XQuartz 2.8.x should be forcing you to do so.

**Comment by jacksparrow601** [comment]
> launchd.plist




> The launchd.plist is what sets DISPLAY. You need to logout / login. XQuartz 2.8.x should be forcing you to do so.

Thanks for your advice ,but it is still a little hard for me to understand what to do next. I Google what is launched.plist, is it a file on my Mac?

**Comment by jeremyhu** [comment]
It's a type of  configuration file that tells the system how to load this service.  In this case, the important part is that you need to logout and log back in, and then you should have DISPLAY set.

**Comment by jacksparrow601** [comment]
> It's a type of configuration file that tells the system how to load this service. In this case, the important part is that you need to logout and log back in, and then you should have DISPLAY set.

I uninstall the (home-brew version xquartz)and download xquartz.pkg from (https://www.xquartz.org). After following the instruction to install the xquartz, my Mac log out automatically , but it makes no difference .I type echo $DISPLAY in terminal, 
still nothing output.

**Comment by jeremyhu** [comment]
Did you disable or delete the LaunchAgent?  (eg: in Ventura's Login Items section in System Preferences)?

What does `launchctl getenv DISPLAY` report?  If it shows something and you cannot echo it, then something in your shell init scripts is unsetting it.

**Comment by jacksparrow601** [comment]
> Did you disable or delete the LaunchAgent? (eg: in Ventura's Login Items section in System Preferences)?
> 
> What does `launchctl getenv DISPLAY` report? If it shows something and you cannot echo it, then something in your shell init scripts is unsetting it.

Thank u, I just do not know I need to reboot. I have no problems
