### ISSUE TITLE
XQuartz failed to connect to X server localhost

### ISSUE THREAD

**Issue by batjaxman** [XQuartz/XQuartz#237]
I'm a student at Dixie State University conducting research in computational and theoretical chemistry, and I'm trying to run the Xquarts software in order to run molden. I was having a problem running the application but it was recently troubleshooted by the staff at xsede. When I attempted to use molden it gave me this error: Invalid MIT-MAGIC-COOKIE-1 keyMolden: cannot connect to X server localhost:10.0

      Do you know why this error is occurring? Why would I not be able to connect to the server? Is there some preventative measures on Macbooks that restricts access to X-Quarts? My Macbook is a 2020 with the M1 chip, version 12.0.1. Thank you for the help!

**Comment by jeremyhu** [comment]
Please ask for support on the xorg or x11-users mailing lists.  In this case, you probably need to enable ssh forwarding.
