### ISSUE TITLE
Two windows open when using SPICE Protocol

### ISSUE THREAD

**Issue by runultra** [XQuartz/XQuartz#238]
When opening a SPICE protocol application with xquartz on MacOS Monterey I am experiencing that xQuartz will open 2 windows. One with the application looking fine, and a second fully black window. Screenshot attached to show the left window is the all black window and the right window being the window that should be open. If you close the left window the whole thing closes.

This seems to only be happening on Monterey with Intel and M1.
![Screen Shot 2022-01-18 at 2 04 13 PM](https://user-images.githubusercontent.com/54156332/150002105-62eadc6e-78b8-4527-9d82-36859c653669.png)

**Comment by jeremyhu** [comment]
I'm not familiar with SPICE.  I suggest reaching out to that community for support in debugging this.

**Comment by jeremyhu** [comment]
Closing due to lack of response, so this is not actionable.  Please reopen if you have additional details to provide.
