### ISSUE TITLE
MAC OS High Sierra shift+ctrl+command+4 snapshot a remote java 11 application on linux, get white figures but normal font

### ISSUE THREAD

**Issue by wangmeijiao** [XQuartz/XQuartz#24]
My situation:  the remote machine is a linux (CentOS7) box with java 11 installed. I can successfully open a java GUI application in a local(MAC OS) xquartz window and everything seems normal. But if I shift+ctrl+command+4 snapshot the xquartz window,  I get nearly empty snapshots (the font show normal). Google tells me to tune the color in xquarz but this does not improve. Also changed the java version, no use. Something with linux graphic card driver? It seems that there is no graphic card installed. Please help!

**Comment by jeremyhu** [comment]
Please file a bug report with Apple using http://bugreport.apple.com or the Feedback Assistant app.  Please report back the FB number, so we I can dig it up internally and help evangelize it.
