### ISSUE TITLE
Request underlying `NSWindow*` from server?

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [XQuartz/XQuartz#240]
(This might make no sense whatsoever but thought I might aswell ask)

Is there any way to request the underlying `NSWindow*` from the server for creating `NSView*`s to create Metal layers to wrap in surfaces? (Trying to use XQuartz with MVK)

Sorry if there's some technical reason this doesn't make sense or the server refrains from extensions - not too familiar with XQuartz nor with Cocoa.

**Comment by jeremyhu** [comment]
The windows are not NSWindows.  Not sure what you are doing, but hopefully that's enough to help.

Really, the right approach here is to do a compositing window manager.
