### ISSUE TITLE
XGetKeyboardMapping() returns same result even if "Follow system keyboard layout" and layout changes

### ISSUE THREAD

**Issue by nbriggs** [XQuartz/XQuartz#246]
With the XQuartz option "Follow system keyboard layout" set, I expected that a call to `XGetKeyboardMapping()` would return different information for the system input being US keyboard vs German keyboard -- for example, the grave accent key (keycode 58) which is that on the US keyboard but `<` on the German keyboard.

XGetKeyboardMap returns (when follow system keyboard layout is set):
```
US:  Keycode 58:	      Keysyms:  60	       7e	     fe50	       60
DE:  Keycode 58:	      Keysyms:  60	       7e	     fe50	       60
```
where `keysymdef.h:#define XK_grave                         0x0060  /* U+0060 GRAVE ACCENT */`

This is on a MacBook Pro with a US keyboard, running 10.11.6.

**Comment by jeremyhu** [comment]
#148

**Comment by nbriggs** [comment]
Is there a way for an X11/XQuartz client to determine what the system keyboard mapping is? (e.g., German vs US/English standard mapping)

**Comment by jeremyhu** [comment]
Maybe, but what would you want to do with that data?  You cannot set the keymap using it.

**Comment by nbriggs** [comment]
The Interlisp virtual machine, an X11 application on macOS (and other X11 supporting systems) uses the X11 keycodes, not the keysyms, for input... which it runs through its own mapping table to present the "physical" keyboard bit transitions to the Lisp code that then interprets those.  On systems other than macOS, the code that sets up the first stage of the mapping tables (system physical keyboard to VM pseudo physical keyboard) uses what it finds in the XGetKeyboardMapping to influence the key assignments.  It never tries to set an X11 keyboard mapping.

Additionally, knowing whether the system keyboard is, for example, German (or that the user will be typing on it as if it were German) allows the upper levels of the input handling to install the correct international mappings in the Lisp code (vs. the VM's lowest level mappings).
