### ISSUE TITLE
X11 cannot open display in macOS 11.6.1

### ISSUE THREAD

**Issue by trevorVlong** [XQuartz/XQuartz#248]
When in terminal trying to open xterm (or any x window) the error

"""
xterm: Xt error: Can't open display: :0
""" 
is returned. If instead, xquartz is launched manually and the same command is run a new xterm will open. I've followed some forums on this and the symptom (though not the cause) of the issue appears to be that in all cases 
"""
echo $DISPLAY 
"""
returns :0

**Comment by jeremyhu** [comment]
Please do not overide DISPLAY.  You are probablt setting that (incorrectly) in a shell init script.
