### ISSUE TITLE
clipboard syncing only works between xclip clipboards in the local machine and in the server

### ISSUE THREAD

**Issue by YanzhaoW** [XQuartz/XQuartz#249]
Hi,

I notice that by enabling `enable syncing`(and also first three options) in pasteboard option only syncing the clipboard between the xclip clipboards in local machine and the xclip clipboards in the server. When changing the clipboard using `pdcopy` in local macOS, the output from 
```sh
xclip -sel clip -o
```
in the remote server doesn't change. Nor can `xclip -sel clip -i` in the server change the outcome of `pbpaste` in the local macOS. And same problem applies for all other xclipboards (primary, secondary etc). However, as is previously mentioned, they do change the outcome from xclip clipboards in the local macOS (if xclip is installed in the local macOS). 

Is this a bug or I just didn't set it up correctly?

XQuartz version: 2.8.1
macOS version: 12.2.1 Monterey

**Comment by jeremyhu** [comment]
#142
