### ISSUE TITLE
Meta key is not working

### ISSUE THREAD

**Issue by jkitchin** [XQuartz/XQuartz#250]
I am forwarding a GUI emacs to XQuartz from a Docker image. The forwarding works fine, but I cannot use the option key as Meta in Emacs. Instead of M-x doing what it is supposed to, it inserts ≈.

It seems like unchecking Enable key equivalents under X11 should have fixed this, but it doesn't seem to do anything. If I set Option keys sent Alt_L and Alt_R, they do indeed send Alt modifiers, but not Meta. At least in Emacs, a potential work around is using `(setq x-alt-keysym 'meta)`, but it seems like that should not be necessary.

The X11 preferences look like this:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1610070/157878539-82477b99-5b94-4b74-873a-14360b99fb07.png">

Relatedly, the command keys are bound to Meta, but I would like them bound to super and hyper. Is that something that is set in XQuartz somewhere? 

Is there something I am overlooking on this?

Thanks,

**Comment by jeremyhu** [comment]
You'll need to setup a custom Xmodmap for your desiderd mapping.
