### ISSUE TITLE
XQuartz 2.8.1 segfault with mfix/OpenGL

### ISSUE THREAD

**Issue by RobbieTheK** [XQuartz/XQuartz#251]
I posted on the [mfix discussion board](https://mfix.netl.doe.gov/forum/t/mfix-21-4-rhel-7-5-with-x11-starts-and-fails-to-open-glew-could-not-be-initialized-missing-gl-version/3629/13), as well as [on OpenGL](https://community.khronos.org/t/finding-opengl-es-2-0-mesa-18-3-4-on-rhel-7-for-mfix/108359). I have mfix working via Mobaxterm and a Debian remote desktop. However there's the following seg fault:

```
vtkOpenGLRenderWindow.c:499  ERR| vtkXOpenGLRenderWindow (0x55555d7967e0): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.
Segmentation fault
```

I also start mfix with  `MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150`. glxgears opens fine. `defaultserverargs="+iglx"` is definitely set in the file `/opt/X11/bin/startx` as [suggested here](https://github.com/XQuartz/XQuartz/issues/243#issuecomment-1038904497). I also ran `defaults write org.macosforge.xquartz.X11 enable_iglx -bool true.`

Is there a work around or another setting change I'm missing?

**Comment by jeremyhu** [comment]
Your title says XQuartz crashes.  Does it crash or does your X11 application just exit?  I assume the latter, in which case this is #144.

**Comment by BigBang019** [comment]
@RobbieTheK Have you solve the issue? I also encountered this Segmentation fault while using X11 forwarding.
My remote machine is an Ubuntu 18.04 and host machine is Big Sur 11.6 with XQuartz 2.8.2.
```
2022-08-16 18:29:38.256 (  17.948s) [        176D6740]vtkOpenGLRenderWindow.c:499    ERR| vtkXOpenGLRenderWindow (0x562958181ac0): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.
Segmentation fault
```

After this issue happend, my X11 application does not exit. It looks like it's not the same issue as is in #144 .
