### ISSUE TITLE
XQuartz 2.8.1 not working (MBP16, intel, macOS Monterey 12.2.1 (21D62))

### ISSUE THREAD

**Issue by mgiugliano** [XQuartz/XQuartz#253]
I got the same behaviour installing XQuartz with brew or by the *.dmg. 

Launching Xquartz upon clicking on the app icon (or by /opt/X11/bin/xquartz from Terminal.app or iTerm2.app) does launch the process that becomes visible on the Activity Monitor. This lasts 5-10s and then the process dies.

Launching "xeyes", "xterm" or another app requiring X11 does relaunch Xquartz, but nothing happens: the apps hang and do not respond. I see that the $DISPLAY variable gets initialised (e.g. to /private/tmp/com.apple.launchd.uERODEzS1s/org.xquartz:0). In this case the process xquartz stays in the background.

No error message is displayed in the terminal or in the Console.app log files.

**Comment by jones77** [comment]
Same problem on Big Sur 11.6.4.

**Comment by mgiugliano** [comment]
@jones77 I have a (weak) theory: could the problems related to an "interference" with homebrew and its installed x11 libraries?

**Comment by shahnawaz323** [comment]
On MacOS 12.3 I am trying to use X2go with Xquartz and process quits with a 'Finished' message

**Comment by jeremyhu** [comment]
You should not be executing /opt/X11/bin/xquartz directly.

What happens if you run `xterm` directly on the command line?
What happens if you execute `/Applications/Utilities/XQuartz.app/Contents/MacOS/X11.sh`?
What happens if you execute `/Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin`?

**Comment by shahnawaz323** [comment]
Nothing happens when I run these command in terminal. May be bcoz xquartz is already running when I execute these commands

**Comment by jeremyhu** [comment]
Yes.  The comments above are for the folks reporting that XQuartz isn't launching at all.  This is usually because of a bad init file.

**Comment by jeremyhu** [comment]
Please hop in the x11-users mailing list to get support for issues like this.

**Comment by mgiugliano** [comment]
Thank you for providing me with a link to the x11-users mailing list. I would love to enjoy XQuartz and help improving it, but I am not aware of all mailing lists.

**Comment by jeremyhu** [comment]
https://www.xquartz.org/Mailing-Lists.html
