### ISSUE TITLE
My Windows tab for XQuartz is greyed out

### ISSUE THREAD

**Issue by biancardi** [XQuartz/XQuartz#257]
Hi all

this is recent and I don't remember what I did for this to happen.   This was working the other day with no issues.  Now, I see that menu option greyed out and every time I open an X11 window, there is no menu bar and I cannot move it.  When I bring up my gui interface for the app I run under this, it will crash after several minutes.  I cannot zoom, minimize,cycle thru windows, etc. see [https://media.fotki.com/2v2aWS9cNxA8PBn.png] 

This is not an issue with my other apps. I deleted my my X11 folder and reinstalled. Still the same thing.  Do I have some weird permissions issue thing going on?  

I am not an expert on XQuartz - it is just a tool for me to develop my applications that need that GUI interface. 

please let me know what I might be doing wrong here.

I am  running OS X El Capitan version 10.11.6 (yes, it is old, but it works still) and  XQuartz 2.8.1 (xorg-server 1.20.11)

**Comment by biancardi** [comment]
I also have two more photos.

When I mouse over, I get a HUGE X instead of my normal mouse icon.  My gui app also crashes within minutes 

huge icon [https://media.fotki.com/2v2aWSuN2xA8PBn.jpg](https://media.fotki.com/2v2aWSuN2xA8PBn.jpg)
error report [https://media.fotki.com/2v2aWSuN2xA8PBn.jpg](https://media.fotki.com/2v2aWSuN2xA8PBn.jpg)

**Comment by jeremyhu** [comment]
This sounds like quartz-wm not launching.  Can you share a sysdiagnose of the situation?

**Comment by kdona** [comment]
I also have this issue. If I manually run the quartz-wm executable I can regain the menu bar but the app still crashes regularly. This occurs with the most recent version of xquartz, but I have also had it with earlier versions when I tried to reinstall from scratch.

**Comment by jeremyhu** [comment]
Do you have a custom .xinitrc or similar?  I'd need to know why quartz-wm isn't launching for you...
