### ISSUE TITLE
OpenGL GLX extension not supported on M1 Macs

### ISSUE THREAD

**Issue by stenheinze** [XQuartz/XQuartz#259]
When trying to run remotely the following error is shown on M1 Macs (it works in Intel Macs):

`freeglut OpenGL GLX extension not supported by display 'localhost:10.0'`

This is on an up to date M1 Mac with XQuartz 2.8.1, the remote being Ubuntu 20.04.4 LTS.

Is there a fix or workaround for this?

**Comment by stenheinze** [comment]
Is there any further information that I can provide?

**Comment by jeremyhu** [comment]
IGLX isn't well supported at all.

#144
