### ISSUE TITLE
Matlab displays dark and it's impossible to use on MacBook Pro with M1 Max chip

### ISSUE THREAD

**Issue by lorelunghini** [XQuartz/XQuartz#260]
Hi, using Matlab on working node with my MacBook Pro with M1 Max chip, the GUI displays all black and no text is possible to read, I have this issue since I bought the pc. By default Matlab has a white background.
If I change window, for example clicking on terminal the window gets normal but if I move the mouse it's come back to dark window.

I have XQuartz at the current latest version: 2.8.1 (xorg-server 1.20.11).
This issue persist if I use different version of Matlab on working node, I also report that this issue affects only Macs with Apple silicon chips because all the Intel based Macs I've tested for works perfectly.

I hope that a solution will be find quite fast.

**Comment by NicolaTibo** [comment]
I have the same issue. It works on every other computer. The bug also appears if someone with an intel CPU generates MATLAB and then I open their session on xquartz with my M1 chip.

Also, if I am on a text box (example if i rename a file). MATLAB's colors turn back to normal for a brief moment.

**Comment by lorelunghini** [comment]
@ayearout Tried but this issue persist.

**Comment by dthuynguyen** [comment]
Tried too, it is not working, still black in background

**Comment by jeremyhu** [comment]
#31
