### ISSUE TITLE
“XQuartz.app” is damaged and can’t be opened. (macOS 13 Developer Beta 1)

### ISSUE THREAD

**Issue by lbibass** [XQuartz/XQuartz#261]
I can't open the app. There's no error log other than this. 
<img width="372" alt="Screen Shot 2022-06-08 at 4 22 30 PM" src="https://user-images.githubusercontent.com/27320050/172709992-4adc5d72-215a-4f30-9c54-4c9396429ca2.png">

**Comment by jeremyhu** [comment]
Can you file a bug report (Feedback Assistant) with Apple.  Include a sysdiagnose and XQuartz.app as it is on your system.  Report the FB number here.

Did you install XQuartz before or after installing the beta?

**Comment by lbibass** [comment]
After reinstalling xQuartz and deleting all the x11 bits still hanging around my system, it worked correctly again.

**Comment by jeremyhu** [comment]
Ok, then unfortunately, I don't have enough here to dig into what went wrong ... =/
