### ISSUE TITLE
XQuartz windows are always on top of all other windows on macOS Ventura

### ISSUE THREAD

**Issue by tim1724** [XQuartz/XQuartz#262]
On the first developer beta of macOS Ventura (build 22A5266r) XQuartz seems to mostly work ok but all of the XQuartz windows are always on top of all the non-X11 windows. This is a little annoying. It would be nice if they'd go back to being able to be interleaved with non-X11 windows.

**Comment by jeremyhu** [comment]
Please file a feedback assistant report and report the db number here

**Comment by tim1724** [comment]
Filed.   #FB10232621

**Comment by jeremyhu** [comment]
I'm going to move this to 2.8.3 for continued tracking.  I expect this to be an OS fix, but keeping it on us just in case.

**Comment by jeremyhu** [comment]
The bug that was tracking this is marked as fixed in macOS 13 Beta 4 (released yesterday, I believe).  Please update to it and confirm whether or not it is addressed.

**Comment by tim1724** [comment]
No, it’s not fixed yet.

I still have this problem on beta 4 (Ventura build 22A5311f)

Here’s a screen recording showing the problem:  https://www.cs.hmc.edu/~tcb/XQuartz_on_top.m4v

**Comment by PC1210** [comment]
Still an issue with beta 5 (Ventura build 22A5321d) in combination with XQuartz 2.8.3_rc1

**Comment by jeremyhu** [comment]
This should finally be resolved with beta 6.
