### ISSUE TITLE
Matlab doesn't work perfectly with XQuartz 2.8.2 beta 1 on M1 Pro Max chip.

### ISSUE THREAD

**Issue by lorelunghini** [XQuartz/XQuartz#263]
HI, after the update 2.8.2 beta 1, setting the color set to 256 Matlab doesn't appear dark anymore so the issue #31 is "fixed", it's not perfect to see but it's possible to see the interface clearly.
Another problem comes out with this update: after selecting 256 colors Matlab gives an error telling that Matlab does not support bit depths less than or equal to 8 so figure windows may not be usable. This issue is quite noisy because you are unable to make any type of plot, if you try to make a plot Matlab crash.
I've tried to change the color setup setting thousands or millions colors but the black screen come back (#31).
How can I fix?

**Comment by jeremyhu** [comment]
#31 needs to be fixed properly.  Not many apps support pseudocolor any more.  We should be removing that in #165.
