### ISSUE TITLE
Tektronics mode has extra characters at prompt: ?24004h

### ISSUE THREAD

**Issue by rth238** [XQuartz/XQuartz#265]
Mac Studio, ultra, MacOS 12.4:
Invoking xtern - t -bg b  (to give that Tektronics 4010 feel) has garbage characters at prompt:
%
>?2004h

Is there a fix for this, via settings or something deeper?

**Comment by jeremyhu** [comment]
What version / config has the problem?
What version / config works?

Can you narrow down what the difference is between working and not working?

**Comment by rth238** [comment]
I've just found old Plot10 programs and started trying to get them to work with xterm.
Every line includes this as a "prompt":
%
>?2004h
even upon just opening the window with xterm -t. (It does not happen when just opening an xterm window, that just give the prompt)
I am running Xquartz 2.8.1 (I tried the 2.8.2 beta 3 and got the same results). This is on a Mac Studio, M1 Ultra, Monterey 12.4
Searching the web, I saw a similar issue, but don't understand the problem or the fix: https://github.com/cgdb/cgdb/issues/256

**Comment by jeremyhu** [comment]
I suggest reaching out to Thomas Dickey https://github.com/ThomasDickey/xterm-snapshots, https://invisible-island.net/xterm/xterm.html for support here.  We don't do anyhing special for xterm, so he'd be the best one to help you out.

**Comment by rth238** [comment]
Thanks to you and Thomas, I've tracked this to an issue with the Apple default shell, zsh, currently version 5.8.1 
In zsh 5.1, a new  "Bracketed Paste Mode" was introduced as a default. (It is deemed a safety issue so that pasted text is bracketed with control sequences so that the program can differentiate between pasted and typed text.) Unfortunately, escape sequences that are ignored by most modern terminals show up in the Tektronix mode of xterm. One way to get rid of the extra characters after the prompt is to:
unset zle_bracketed_paste
However, at least with the prompt that I have, I still get a % separating each line. (I've not searched long, but have not found a way to remove that.)
So, at least for me, it's easier to use the Tektronix mode with csh.
So, to invoke this mode, I use:
xterm -t -bg black -fg green csh
So with this, there are no "%" symbols before each line, and no "?2004h" at the end of each prompt. So this seems best for me, at least for now...
Thanks, again.

**Comment by jeremyhu** [comment]
ooh a csh uers.  You're a rare breed, my friend ;)  Glad you're up and running again.
