### ISSUE TITLE
Xquartz does not work on my Mac Studio

### ISSUE THREAD

**Issue by jimrome** [XQuartz/XQuartz#266]
On version 2.81, or the new beta, I can no longer launch any X apps from an iTerm2 login to my OpenSUSE 15.4 machine. No error messages. just no windows.
The xterm from the Xquartz menu does work.
This works all the time on my old Mac Pro running Mojave.

**Comment by jeremyhu** [comment]
There is possibly a lot of difference in configuration between your two systems.  Please ask for help on the x11-users mailng list to investigate your issue.  You should start by making sure that starting an xterm from iTerm2 (locally, not on opensuse) works fine.  And then check what DISPLAY is after you login to your linux machine becuase DISPLAY forwarding might be disabled.
