### ISSUE TITLE
macOS 11.6 (Big Sur) XQuartz 2.8.2 (xorg-server 1.20.14) Applications/Customize: Modifications are not persisted.

### ISSUE THREAD

**Issue by jgenoese** [XQuartz/XQuartz#267]
Steps to reproduce:
1. Click Applications
2. Click Customize..
3. Make modifications on one item, pressing <Enter> to ensure that changes actually register
4. Switch to another item (to change focus)
5. Observe changes made in (3) are reverted.

**Comment by jgenoese** [comment]
Ancilalry info:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9

**Comment by jeremyhu** [comment]
Looks like we can add entries, but there is some bad behavior when editing them.

[X11.bin-2022-07-02-133921.ips.txt](https://github.com/XQuartz/XQuartz/files/9033683/X11.bin-2022-07-02-133921.ips.txt)

**Comment by jeremyhu** [comment]
Please test in 2.8.3_beta2 or later when it's available.
