### ISSUE TITLE
M1 problem

### ISSUE THREAD

**Issue by jinyl777** [XQuartz/XQuartz#27]
I use Xquarte to open the linux ide, but the background is black and the font is blurred. I can barely see the font after changing the skin to high contrast. Gedit is normal, but matlab pycharm is abnormal.

**Comment by jinyl777** [comment]
![Uploading 截屏2021-01-15 上午10.26.16.png…]()

**Comment by jeremyhu** [comment]
I'm unable to see that image, but an issue like this doesn't seem to be an XQuartz bug.
