### ISSUE TITLE
gdk_gl_window_impl_x11_make_context_current crash

### ISSUE THREAD

**Issue by pdolmsted** [XQuartz/XQuartz#273]
Hello, 

I was trying to run this code a linux box over X-windows: http://www.oc.tu-bs.de/Grunenberg/compliance.html

It runs on the linux box, but when running it remotely through Xquartz it crashes with the following (when I open a file):

"(compliance:558416): GdkGLExt-CRITICAL **: 10:05:08.104: gdk_gl_window_impl_x11_make_context_current: assertion 'GDK_IS_GL_CONTEXT_IMPL_X11 (glcontext)' failed
The program 'compliance' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 8686 error_code 2 request_code 149 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)"

Am I out of luck? Is this a bug I should report to the developer? [I've also asked the developer].

Thanks, 

  - Peter

**Comment by jeremyhu** [comment]
#144

**Comment by pdolmsted** [comment]
So I guess this means I'm out of luck, based on what I read in that thread (I'm indeed on an M1 MacBook Pro, Mac OS X 12.4, XQuartz 2.8.2); is that right? Thanks for pointing this out. I'll make other arrangements.

**Comment by jeremyhu** [comment]
Yes, I would not count on IGLX working well for X11 in general (and especially not XQuartz).
