### ISSUE TITLE
Request to bring back ability to have a default system-wide xquartz application menu

### ISSUE THREAD

**Issue by verogers09** [XQuartz/XQuartz#274]
Hello,
Our team relies on customizing the xquartz application menu for launching the many applications we use.  It was very helpful in an earlier release to have a default xquartz plist file located in /opt/X11/lib/X11/xserver/ so that I could provide a single customized application menu, instead of needing to put a copy in every user's /Library/Preferences folder.  Would it be possible to bring that feature back?  
Many thanks for considering!

**Comment by jeremyhu** [comment]
Regressed in f40610e0b4f2b4ae54ef6bbff756cb4a60e17e3b
