### ISSUE TITLE
XQuartz 2.8.3_rc1 - X11.bin crashed with "pointer being freed was not allocated"

### ISSUE THREAD

**Issue by nbriggs** [XQuartz/XQuartz#275]
Crashed when dragging (lower right) corner to reshape application window, which has scroll-bar windows attached.

[crash1.txt](https://github.com/XQuartz/XQuartz/files/9255704/crash1.txt)

If I run it without the scroll-bar windows attached, and turn on XSync, it takes a SIGBUS instead:

[crash2.txt](https://github.com/XQuartz/XQuartz/files/9255710/crash2.txt)

**Comment by jeremyhu** [comment]
Do you have a way to reliably trigger these crashes?  Could you show me (eg: video) what you're doing to cause them?

**Comment by nbriggs** [comment]
Yes, crashes every time.  I'll figure out how to demo this and see if I can get a trace of what X11 operations it is doing.

**Comment by nbriggs** [comment]
It also crashes every time when I start the same program on another system with remote display back to the mac (ssh display forwarding) with 2.8.3_rc1 installed.  So... there I can run xtruss, for which I've attached the output.
[xtruss.txt](https://github.com/XQuartz/XQuartz/files/9426234/xtruss.txt)

The program that provokes this is open source, so with a bit of work it's possible that you can reproduce this locally.

**Comment by nbriggs** [comment]
Testing with 2.8.3_rc4 no longer gets this crash.  Thank you!
