### ISSUE TITLE
Can't revert to Xquartz 2.8.2 after installing 2.8.3_rc1 ?

### ISSUE THREAD

**Issue by nbriggs** [XQuartz/XQuartz#276]
Was on version 2.8.3, upgraded to 2.8.3_rc1 using the sparkle update.  When 2.8.3_rc1 was unusable, tried downloading the Xquartz 2.8.2 disk image and reinstalled, then rebooted my Mac.  The "About" message in Xquartz still says 2.8.3_rc1.   Tried deleting the defaults for org.xquartz.x11 and let it recreate -- same (2.8.3_rc1).  Did `rm -rf /opt/X11`, then reinstalled from the 2.8.2 disk image, and it *still* says it's 2.8.3_rc1 and it's still failing tests that used to work under 2.8.2 (so it probably *is* 2.8.3_rc1).

**Comment by nbriggs** [comment]
OK - solved this immediate problem, you have to `rm -rf /Applications/Utilities/XQuartz.app` as well before you can reinstall.
I don't think it should behave this way -- if you reinstall it should either do as its told or, if it's going to do something else, tell you what it has done.

**Comment by jeremyhu** [comment]
This is behaving correctly.  The Installer is ensuring that content is upgraded and not downgraded because downgrading is dangerous if we change how we launch.  Instructions for downgraded are in the FAQ.
