### ISSUE TITLE
failure of /opt/X11/bin/xclock  -digital -brief -twentyfour 

### ISSUE THREAD

**Issue by gbrxclock** [XQuartz/XQuartz#278]
using 2.8.2

/opt/X11/bin/xclock  -digital -brief -twentyfour 

the numbers showing hours are pushed too far to the right and the minutes overlap the least significant number of the two numbers representing hours

I have used this program with the same parameters in previous versions of XQuartz without issue

**Comment by jeremyhu** [comment]
I'm not seeing any issue with 2.8.3_rc4.  This might've been related to another issue that was fixed in the newer version.  Please verify this is now fixed.
