### ISSUE TITLE
Blurry bitmap fonts on HiDPI screens in XQuartz 2.8.2 on macOS 12.5 Monterey

### ISSUE THREAD

**Issue by lantz** [XQuartz/XQuartz#279]
Bitmap fonts are not being displayed sharply on HiDPI screens in XQuartz on macOS Monterey

For example, I tried the command:

    xterm -fg green -bg black -fn lucidasanstypewriter-14

In XQuartz 2.7.7  on macOS 10.14.6 Mojave, this yields sharp, pixel-perfect onscreen results (sharp HiDPI scaling)
In XQuartz 2.8.2 on macOS 12.5 Monterey, this yields ugly, blurry onscreen results (blurry HiDPI scaling)

The puzzling behavior is that it looks blurry onscreen in XQuartz, but if I take a screen shot and then zoom in on it in Preview it looks perfect. Yet at "actual size" in preview it looks blurry. What is going on here? Is HiDPI rendering messed up somehow? It looks like if we render the image at "actual size" in HiDPI it gets blurred rather than sharply scaled into 2x2 pixels. In fact if I drag the preview window onto a 1:1 display, then it looks fine!

Here are my display testing results:

MacBook Pro 2016 internal display HiDPI (2x in each direction): blurry
External LG 5K monitor HiDPI: blurry
External 4K monitor 1:1 (*not* HiDPi): sharp

It looks like we need some way to enable sharp HiDPI pixel scaling for XQuartz/X11 windows in macOS Monterey.

**Comment by jeremyhu** [comment]
#91
