### ISSUE TITLE
Experiments with arm

### ISSUE THREAD

**Issue by soulilya** [XQuartz/XQuartz#281]
Hallo! I just wanna to ask how i can compile this for ios arm for experiments? I should make any changes in code? Thanks.

**Comment by jeremyhu** [comment]
Not quite sure what benefit you'd get with an X server on ios... ?

**Comment by soulilya** [comment]
@jeremyhu thanks for reply. Im trying to learn compiling and cross compiling. So im started with that. Now i wanna make my own system from scratch. Right now im stuck with xorg-server 21.1.4. My target system is VM Ware MacOs Catalina. Im download and compile all dependencies, that meson asked for host archeticture armv7. From command line lm trying compile with meson:
`
meson build --prefix /usr/local/arm-apple-darwin -Ddefault_library=static -Dglx=false -Dxephyr=false -Dxnest=false -Dxwin=false -Dxquartz=false -Dsecure-rpc=false -Dipv6=false -Dinput_thread=false  -Dint10=false  -Dscreensaver=false -Dagp=false -Dxpbproxy=false --cross-file=../../darwin-cross-compile.txt
`
darwin-cross-compile.txt:
`
[binaries]
c = 'clang'
cpp = 'clang++'
objc = 'clang'
objcpp = 'clang++'
ar = 'ar'
strip = 'strip'
pkgconfig = 'pkg-config'

[built-in options]
c_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk']
cpp_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk']
c_link_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk']
cpp_link_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk']
objc_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk']
objcpp_args = ['-arch', 'armv7', '-miphoneos-version-min=8.4', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk']

[properties]
root = '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer'
has_function_printf = true
has_function_hfkerhisadf = false

[host_machine]
system = 'darwin'
cpu_family = 'arm'
cpu = 'arm'
endian = 'big'
`
After that command:
`ninja install`
 there is some missed symbols, but i resolve them adding libs in build.ninja file. There is some warnings. result is:
`[0/1] Installing files.
Installing hw/vfb/Xvfb to /usr/local/arm-apple-darwin/bin
Installing /Users/admin/source/xorg-server-21.1.4/build/hw/vfb/Xvfb.1 to /usr/local/arm-apple-darwin/share/man/man1
Installing /Users/admin/source/xorg-server-21.1.4/build/Xserver.1 to /usr/local/arm-apple-darwin/share/man/man1
Installing /Users/admin/source/xorg-server-21.1.4/dix/protocol.txt to /usr/local/arm-apple-darwin/lib/xorg`
And thats it. We can see, that xorg install not working and compiled files missing. After that im trying autotools:
`./configure --disable-static --enable-shared --prefix=$THEOS --host=arm --enable-glx=no --enable-xquartz=no --enable-xephyr=no --enable-input-thread=no --enable-secure-rpc=no --enable-ipv6=no --enable-xwin=no --enable-xnest=no --enable-standalone-xpbproxy=no --enable-int10-module=no --enable-screensaver=no --enable-pciaccess=no --enable-agp=no --enable-glamor=no --enable-vgahw=no`
There is some wargnings, but ok. When file Xorg start compiling i got a error message:
`CCLD     Xorg
Undefined symbols for architecture armv7:
  "_ddxInputThreadInit", referenced from:
      _xorg_symbols in sdksyms.o
  "_drmAuthMagic", referenced from:
      _DRI2ScreenInit in libdri2.a(dri2.o)
  "_drmFreeDevice", referenced from:
      _dri2_probe_driver_name in libdri2.a(dri2.o)
  "_drmFreeVersion", referenced from:
      _dri2_probe_driver_name in libdri2.a(dri2.o)
  "_drmGetDevice", referenced from:
      _dri2_probe_driver_name in libdri2.a(dri2.o)
  "_drmGetVersion", referenced from:
      _dri2_probe_driver_name in libdri2.a(dri2.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
In that case i dont know what to do. Its his own libs. How i can resolve that? Mutch appreciate any help. Stuck with 3 days with that.

**Comment by jeremyhu** [comment]
In that case, I suggest you look  through the compilation scripts in this repo to better understand how we build for macOS.  Porting to iOS would be a pretty significant undertaking.
