### ISSUE TITLE
Is it possible to create Metal surfaces out of XQuartz windows?

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [XQuartz/XQuartz#282]
(Sent from https://github.com/KhronosGroup/MoltenVK/issues/1694, could be seen as a follow up to https://github.com/XQuartz/XQuartz/issues/240)

Basically as the title says - is it possible to create a surface suitable as a Metal target from an XQuartz window? Since GLX works (?) I suppose XQ window surfaces can be the target of a swapchain so is it feasible to expose these surfaces for other APIs? Or are they emulated and as such unsuitable for it.

Sorry that this is sort of a duplicate! I didn't word it very well the first time.

Thanks!

**Comment by jeremyhu** [comment]
No, X11 uses xp_windows (libXplugin).  Ideally, we'd throw away Xplugin and all of that in XQuartz and instead use Xorg DDX with a compositing window manager.

**Comment by tnagorran** [comment]
Is there anything we can do to help you do this?
it is currently impossible to make x11 windows support Vulkan until it is fixed/implemented

**Comment by jeremyhu** [comment]
Yes, if you wanted to devote time to engineering and implementing this, I'd be happy to pick up those changes in the future.
