### ISSUE TITLE
Problem with EiffelStudio (XQuartz 2.8.2, MacOS Monterrey version 12.4, M1 Chip)

### ISSUE THREAD

**Issue by jvelilla** [XQuartz/XQuartz#284]
We have issues with EiffelStudio IDE.
When we execute the IDE we get a white screen (see the following image).
 
<img width="640" alt="EiffelStudio" src="https://user-images.githubusercontent.com/23418/187678713-6d16717b-0910-4d8f-be74-a7748a981dee.png">

We use GTK3.24 for our UI. Do you know if there are some known issues using Gtk3.24 with XQuartz on M1 chip? 
Maybe we are using some features that have some conflicts with XQuartz on M1. 

We note the following GTK warning `GtkSettings Cursor Theme: Unsupported GDK backend` that's not present when we try on MacOs Intel version using the same XQuartz library version. But it doesn't seem to be the root cause of the white screen.

Finally, we have tested EiffelStudio with XQuartz 2.8.2 ,  MacOS Monterrey version 12.4, Intel chip, and it works fine.

**Comment by raoultrines** [comment]
Any relationship with issue #31 ?

**Comment by jeremyhu** [comment]
So then closing this as resolved ?  ... not sure what might have cuased it or fixed it though =/

**Comment by jvelilla** [comment]
Well for me it's not resolved, it works better but with some issues and it's related to issue [#31](https://github.com/XQuartz/XQuartz/issues/31). 
We use GTK3 and we were able to reproduce the background color issue with [Gtk3 demo example](https://gitlab.gnome.org/GNOME/gtk/-/tree/gtk-3-24/demos/gtk-demo).
