### ISSUE TITLE
XQuartz Application menu customizations do not persist (or work)

### ISSUE THREAD

**Issue by jimklo** [XQuartz/XQuartz#285]
Trying to modify the `Terminal` menu such that is uses a specific set of options and uses `uxterm` instead of `xterm`.

First problem I have is that adding arguments to the command does not work.  i.e.

    xterm -u8 -fa 'Source Code Pro for Powerline' -fs 12

Can be added, however if I close and reopen the `X11 Application Menu` window, it appears to persist.  However when selecting the assigned option, it still executes the original command.

Quitting and Opening XQuartz and then opening the `Applications` > `Customize...` window shows the original unmodified default values.

**Comment by jimklo** [comment]
it seems like there are two Preferences files located in `~/Library/Preferences/`.

There is:

- org.macosforge.xquartz.X11.plist
- org.xquartz.X11.plist

Not sure if both need to be there or not... however it seems like the `Customize...` window seems to save to `org.xquartz.X11.plist` however it restores from `org.macosforge.xquartz.X11.plist`.  Additionally the menu launcher seems to use entries from `org.macosforge.xquartz.X11.plist`.

This seems to be a bug any way you look at this.

Expected behavior:
- choose one preferences file to use, don't alternate between two
- warning or error if there are two prefs files, prompt user to choose, remove, or exit.

**Comment by jeremyhu** [comment]
We changed to org.xquartz with 2.8.x.  The preferences are migrated but the older ones are left in case the user wants to downgrade.

**Comment by jeremyhu** [comment]
I'm definitely seeing us save to and reload from org.xquartz.X11.

Are you editing the plist directly?  That's not supported.

What version of XQuartz are you using?  It's possible you're seeing something related to [#267](https://github.com/XQuartz/XQuartz/issues/267)
