### ISSUE TITLE
How to add xhost entries permanently in Mac OS?

### ISSUE THREAD

**Issue by rnunezil** [XQuartz/XQuartz#287]
Every time I boot up my Mac,  I have to readd my localhost onto xhost.  I read this article on supposedly how to have the entry persistently: https://discussions.apple.com/thread/270453.   I followed this my adding my xhost entry in xinitrc and rebooted.  The xhost entries are still blank.  Any suggestions where else I need to add it?  Thanks.

**Comment by jeremyhu** [comment]
Using xhost is not very secure.  Please transition to using X11 tunneled over ssh.
