### ISSUE TITLE
Unusable GUI

### ISSUE THREAD

**Issue by JaceG** [XQuartz/XQuartz#288]
I'm having this issue every time I open filebot. I don't even know how to describe it, so I'll let the screenshots do that. The only way I can get it to go away is by rebooting.

<img width="1512" alt="Screen Shot 2022-10-23 at 9 47 36 AM" src="https://user-images.githubusercontent.com/4998857/197407798-86837f8a-416e-4805-8630-7a23f3999dac.png">

I originally posted this support question here:

[https://www.filebot.net/forums/viewtopic.php?f=11&t=13422&p=58476#p58476](url)

**These are my answers to the questions asked of me there:**

>:?: Are you using FileBot on a remote Linux machine via VNC or similar protocol?

Yes, I am using it on a remote Linux machine using x2go (and sometimes SSH) to connect to it.

>:?: Why not use the macOS version of FileBot on your macOS Desktop?

Unless I can use it to edit files remotely then I think I must use it on the Linux server with all my files. It is a seedbox with 40tb of storage, and over 10tb of files I need Filebot for.

>:?: How did you install FileBot? Which package did you use? What does filebot -script fn:sysinfo say?

I want to note that I do have a registration key, I just reinstalled Filebot the other day while troubleshooting and did not bother put it back in for what I believe may be obvious reasons right now.

<img width="1512" alt="Screen Shot 2022-10-23 at 1 37 35 PM" src="https://user-images.githubusercontent.com/4998857/197408120-a03a5c75-cd15-4e89-95af-864f874a9ab6.png">

>`Initialize AppData folder: /root/.filebot
Initialize Cache folder: /root/.filebot/cache
Initialize Logs folder: /root/.filebot/logs
Initialize TemporaryFiles folder: /root/.filebot/tmp
Initialize new disk cache: /root/.filebot/cache/0
Oct 23, 2022 7:40:56 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
FileBot 4.9.6 (r9125)
JNA Native: 5.2.2
MediaInfo: 18.12
Tools: fpcalc/1.4.3 7z/16.02 unrar/5.50
Extended Attributes: OK
Unicode Filesystem: OK
Script Bundle: 2022-08-15 (r836)
Groovy: 3.0.9
JRE: OpenJDK Runtime Environment 11.0.16
JVM: OpenJDK 64-Bit Server VM
CPU/MEM: 8 Core / 8 GB Max Memory / 62 MB Used Memory
OS: Linux (amd64)
HW: Linux Debian-105-buster-64-minimal 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux
CPU/MEM: Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz [MemTotal: 33 GB | MemFree: 20 GB | MemAvailable: 29 GB | SwapTotal: 68 GB | SwapFree: 68 GB]
STORAGE: ext4 [/] @ 5 TB
USER: root
DATA: /root/.filebot
Package: DEB
License: UNREGISTERED
Done ヾ(＠⌒ー⌒＠)ノ
alexandria@Debian-105-buster-64-minimal:~$ 
:?: `

>:?: You can try to enable / disable the OpenGL render pipeline [https://www.filebot.net/forums/viewtopic.php?t=3913](url) or install different graphics drivers, or generally try graphics related or VNC protocol settings and see if it makes a difference.

This is beyond my skill level to comprehend on my own at this time.

>:arrow: Please report the issue in the XQuartz community as well. They might be able to give you better debugging advice.

I'll do that immediately. Thanks for the tip!

**Comment by JaceG** [comment]
Solved!

[https://www.filebot.net/forums/viewtopic.php?f=11&t=13422&p=58476#p58476](https://github.com/XQuartz/XQuartz/issues/url)

**Comment by jeremyhu** [comment]
This is probably the same as #31
