### ISSUE TITLE
No title bar for Windows - Unable to move or minimize windows - Also very slow Xquartz start

### ISSUE THREAD

**Issue by moshix** [XQuartz/XQuartz#290]
Hello

I am running Xquartz 2.8.1 or 2.8.2 with the same behavior:

it takes Xquawrtz about 30 seconds to start and then the windws have not title bar, so it's impossible to move or minimize a window. This happens with all kinds of applicatons including xterm etc. 

thanks

M

**Comment by jeremyhu** [comment]
Can you take a sysdiagnose during startup?  It seems something is stalling quartz-wm from starting.

Do you have your own ~/.xinitrc or anything like that?

**Comment by jeremyhu** [comment]
Closing due to lack of response.  This is likely not an XQuartz issue.

**Comment by elialaz** [comment]
Hi @jeremyhu 

i encountered the same bug, seems that quartz-wm is not starting automatically and i need to manually start it to resolve this issue.
i do not have my own ~/.xinitrc or anything like that and even by reinstalling the application the issue is still present
