### ISSUE TITLE
Can't open display error on macos ventura

### ISSUE THREAD

**Issue by gaoDean** [XQuartz/XQuartz#295]
Basically when I type `xterm`, it gives this error:
```
xterm: Xt error: Can't open display: :0
```
 
Running the `sent` program, it gives this error:
```
sent: Unable to open display
```
looking into the source code, here is where the error originates:
```c
if (!(xw.dpy = XOpenDisplay(NULL)))
  die("sent: Unable to open display");
```
It seems that `XOpenDisplay(NULL)` returns `null`.

Programs like `xeyes` returns this as well:
```
Error: Can't open display: :0
```

Running `xquartz` seems to be fine though, and the app pops up and stays.

I'm on `macos ventura 13.0.1`, and `XQuartz 2.8.2 (xorg-server 1.20.14)`

Any help is greatly appreciated, thanks.

**Comment by raoultrines** [comment]
From the Terminal window on your Mac, what do you get when you type `printenv DISPLAY` ?

It should look something like this:
`/private/tmp/com.apple.launchd.klE4QqXw6D/org.macosforge.xquartz:0`

**Comment by gaoDean** [comment]
Its this: `/private/tmp/com.apple.launchd.Tek4jGvoH3/org.xquartz:0`, and now when I run xeyes or something I get an error message like `Error: Can't open display: /private/tmp/com.apple.launchd.Tek4jGvoH3/org.xquartz:0`. Its normally this value, but when I created the issue I think i followed some guy on some forum and set it to `:0`

**Comment by raoultrines** [comment]
Can you please send the output of `ls /private/tmp/com.apple.launchd.*` ?

**Comment by gaoDean** [comment]
just saying, I really appreciate you helping troubleshoot this.
```
/private/tmp/com.apple.launchd.Tek4jGvoH3:
org.xquartz:0=

/private/tmp/com.apple.launchd.ZniwXrGAUx:
ls: /private/tmp/com.apple.launchd.ZniwXrGAUx: Permission denied

/private/tmp/com.apple.launchd.ygb6F3cqm1:
Listeners=
```

**Comment by gaoDean** [comment]
whoops, using sudo:
```
/private/tmp/com.apple.launchd.Tek4jGvoH3:
org.xquartz:0

/private/tmp/com.apple.launchd.ZniwXrGAUx:
unix_domain_listener

/private/tmp/com.apple.launchd.ygb6F3cqm1:
Listeners
```

**Comment by raoultrines** [comment]
Strange. The display should exist, but you cannot open it somehow. Maybe an issues with permissions, could be related to #287. I would not know how to solve that, sorry.

I'm about to upgrade to Ventura myself. If I find anything similar on my machine, I'll let you know.

@jeremyhu Do you know of any permission changes on MacOS Ventura that may have caused this?

**Comment by gaoDean** [comment]
That’s alright, thanks for trying anyway

**Comment by jeremyhu** [comment]
I suspect you have multiple LaunchAgents (or generations of them) competing to set DISPLAY.

What's the output of:

`launchctl getnev DISPLAY`
`echo $DISPLAY`

If those are different, you probably didn't reboot after updating.

**Comment by gaoDean** [comment]
`launchctl getenv DISPLAY` prints nothing to the console, but `echo $DISPLAY` prints `/private/tmp/com.apple.launchd.Tek4jGvoH3/org.xquartz:0`. I've restarted multiple times, mostly fix problems with installing xcode 14.

**Comment by gaoDean** [comment]
this issue was here with xcode 13 as well when I just upgraded to ventura, but not with monterey

**Comment by jeremyhu** [comment]
If `launchctl getenv DISPLAY` prints nothing, then something is removing the LaunchAgent, and the DISPLAY in your environment is stale (from when the LaunchAgent was loaded when you logged in).

You should investigate what is causing the LaunchAgent to get unloaded and stop that.

Did you disable it in "Login Items" (in System Preferences)?

**Comment by gaoDean** [comment]
Oh crap, sorry for wasting your time, tysm

**Comment by piyush1104** [comment]
Hey, just came here to say thank you so much! I had also disabled it in the login items and had wasted 4 hrs debugging the cause

**Comment by stringfellow** [comment]
+1, had also disabled it! 🙏

**Comment by humanumbrella** [comment]
thank you @jeremyhu for helping us find this obvious self-inflicted foot-gun -- hah

**Comment by kevinhe5** [comment]
+1, thank you so much!

**Comment by syrusua-t** [comment]
> If `launchctl getenv DISPLAY` prints nothing, then something is removing the LaunchAgent, and the DISPLAY in your environment is stale (from when the LaunchAgent was loaded when you logged in).
> 
> You should investigate what is causing the LaunchAgent to get unloaded and stop that.
> 
> Did you disable it in "Login Items" (in System Preferences)?

+1, this is exactly my problem and I have been searching for the cause for sooo long. Thank you so much!

**Comment by LiPuze** [comment]
+1, thank you so much!!!

**Comment by zorchp** [comment]
> If `launchctl getenv DISPLAY` prints nothing, then something is removing the LaunchAgent, and the DISPLAY in your environment is stale (from when the LaunchAgent was loaded when you logged in).
> 
> You should investigate what is causing the LaunchAgent to get unloaded and stop that.
> 
> Did you disable it in "Login Items" (in System Preferences)?

and you need logout and relogin to make this solved.

**Comment by chengxiaocx** [comment]
> If `launchctl getenv DISPLAY` prints nothing, then something is removing the LaunchAgent, and the DISPLAY in your environment is stale (from when the LaunchAgent was loaded when you logged in).
> 
> You should investigate what is causing the LaunchAgent to get unloaded and stop that.
> 
> Did you disable it in "Login Items" (in System Preferences)?

I also have this issue and thank you so much for pointing out the solution!

**Comment by kvnandula04** [comment]
For anyone wondering how to enable the LaunchAgent in login items, (MacOS Sequoia) just select "+" in "Open at Login" and add the entire folder in `~Library/LaunchAgents` so you should have something like this:

![Image](https://github.com/user-attachments/assets/5fcb09b9-9987-4b2c-8cf4-37b2cc849acb)

Also, I realised I turned off XQuartz from running in the background, you should have this enabled. Hope it helps!
