### ISSUE TITLE
Potential issue MacOS Ventura (13.0.1) and Xquartz 2.8.2

### ISSUE THREAD

**Issue by Xavier-BZT** [XQuartz/XQuartz#297]
I am using the "coot" application that uses Xquartz and since my update to Ventura, I am facing strange behavior of the application window. When I call a specific function ("deletion" of residue, atoms, etc..) the application window disappears. There is no crash, the window is somehow minimized.
I've contacted the programmer of the coot application, but he's not aware of such bug (many not enough feedback yet).

The application terminal sends this message :
(delete-residue-by-atom-index 2 4280 1)
debug:: g.safe_scheme_command() with command post-manipulation-hook
Could it be related to any Xquartz feature that could be modified with the Ventura update?

**Comment by jeremyhu** [comment]
Please work with the coot developer to triage this.

**Comment by dpeterc** [comment]
Try  "Window > Bring All to Front", from XQuartz menu to see if the application is wrongly iconized or has crashed.
