### ISSUE TITLE
How to set DISPLAY

### ISSUE THREAD

**Issue by jacksparrow601** [XQuartz/XQuartz#299]
I type these commands in Mac terminal 
➜  ~ xeyes
Error: Can't open display:
➜  ~ xterm
xterm: Xt error: Can't open display:
xterm: DISPLAY is not set
➜  ~ echo $DISPLAY

➜  ~ printenv DISPLAY
➜  ~ 
---------
Hey guys. Thanks a lot for cliking into my issue. Actually, I have already published an issue, but my problem is still not solved.
my old issue
https://github.com/XQuartz/XQuartz/issues/235

**Comment by raoultrines** [comment]
Could be related to #295, maybe also #289.

**Comment by jeremyhu** [comment]
Please see my comment in your other issue.
