### ISSUE TITLE
XQuartz installer only allows bundle upgrade even though userspace is downgradeable

### ISSUE THREAD

**Issue by dpeterc** [XQuartz/XQuartz#300]
If you install for example XQuartz 2.8.3_rc3 and then downgrade it to 2.8.2_beta3, XQaurtz continues to display version 2.8.3_rc3, despite the fact that  2.8.2_beta3 is installed and some bugs induced in later version are no longer present.
Maybe this is caused by switching from .dmg to .pkg
It is not such a big issue, but can cause a lot of confusion when researching bugs specific to certain versions of XQuartz.

In order to get the display of correct XQuartz version after downgrade, you need to trash XQuartz (move it from Applications/Utilities to trash) before installing the older (downgrade) version.

**Comment by jeremyhu** [comment]
The man page states:

>  BundleOverwriteAction specifies how an existing version of the bundle on
>      disk should be handled when the version in the package is installed. If
>      you specify upgrade, the bundle in the package atomically replaces any
>      version on disk

And we have BundleOverwriteAction  set to upgrade...

**Comment by jeremyhu** [comment]
The issue was that the package is also configured with BundleIsVersionChecked=true.  The behavior of the package should be BundleIsVersionChecked=false.

**Comment by jeremyhu** [comment]
This is fixed in the [2.8.3_rc4](https://www.xquartz.org/releases/XQuartz-2.8.3_rc4.html) installer, meaning 2.8.3_rc4 and later will properly downgrade to those versions without deleting XQuartz.app first.
