### ISSUE TITLE
Bug in Xft library shipped with XQuartz 282_beta4 or later causes invisible text field in Motif applications

### ISSUE THREAD

**Issue by dpeterc** [XQuartz/XQuartz#301]
Starting with XQuartz 2.8.2_beta4, text rendering in Motif applications, which use XFT fonts is not working correctly.
The bug manifests itself on editing text fields, as you place the cursor, text disappears. Text is still there, but is rendered at the wrong place. It looks as if the calculation of text length and position is wrong.
Multi-line text editing works, single line does not. Technically, editing on XmTextFiled widget does not work, while XmText editing works.

XQuartz 2.8.2_beta3 used libXft 2.3.3, while XQuartz 2.8.2_beta4 has upgraded to using libXft 2.3.4, which triggers the bug.

Bug in XFT appears to be this
https://gitlab.freedesktop.org/xorg/lib/libxft/-/commit/95284856783b824a714b7506762f4adce3bb17ce
Fixed in libXFT 2.3.6
https://lists.x.org/archives/xorg-announce/2022-September/003211.html
Fix length check in XftTextExtents*.

Recent versions of XQuartz have not updated Xft library to the current version, so XQuartz 2.8.3_rc3 still uses the buggy libXft 2.3.4
Current version of libXft is 2.3.7, while the bug was corrected in 2.3.6

So I suggest to upgrade libXft in XQuartz to at least 2.3.6, in order to solve this problem.

Video with buggy behavior on XQuartz 2.8.3_beta4 or later, and correct behavior on earlier versions:
https://user-images.githubusercontent.com/15419249/204914995-21243545-46ba-402b-a27a-77ca8197558f.mp4
In the video, we only position the cursor in order to edit the text. Upon editing, cursor can move to strange positions, parts of texts become visible or invisible in an unpredictable way. But in order to demonstrate the bug, clicking on text field is enough.

**Comment by jeremyhu** [comment]
Thanks.  I had is update prepped for 2.8.4_beta.  I'll pull updating libXft into 2.8.3

**Comment by dpeterc** [comment]
Thank you very much.
I have tested XQuartz 2.8.2_beta3 with manually downgraded (copied the library) libXft from 2.3.4 to  2.3.3, and XFT font rendering then worked correctly. So either upgrade of libXft to 2.3.6 or downgrade to 2.3.3 should work fine.

**Comment by jeremyhu** [comment]
@dpeterc Could you please try out [2.8.3_rc4](https://www.xquartz.org/releases/XQuartz-2.8.3_rc4.html)?

**Comment by dpeterc** [comment]
I have tried 2.8.3_rc4 and it works correctly, thank you very much!
I appreciate the time you are putting into solving these issues.
