### ISSUE TITLE
Core font "misc-gb18030 bitmap" has invalid RESY value, crashing programs that try to use it

### ISSUE THREAD

**Issue by sgdoerfler** [XQuartz/XQuartz#304]
It looks like XQuartz ships with a core font with an invalid RESY value,  "misc-gb18030 bitmap". On Intel systems, the invalid RESY value  (vertical resolution in dots per inch) is negative, and programs seem to ignore the broken font, but it's a positive yet still bogus value on M1 systems, which makes programs crash if they try to open it. This can be seen on any program that uses X11 core fonts, such as xfontsel.

On M1 Mac mini (2020) running macOS 12.4, XQuartz 2.8.3:
```
$ xlsfonts | grep "gb18030 bitmap"
-misc-gb18030 bitmap-thin-r-ultracondensed--0-0-75-2147483647-c-0-cns11643-2
-misc-gb18030 bitmap-thin-r-ultracondensed--0-0-75-2147483647-c-0-iso10646-1
-misc-gb18030 bitmap-thin-r-ultracondensed--20-0-75-2147483647-c-60-cns11643-2
-misc-gb18030 bitmap-thin-r-ultracondensed--20-0-75-2147483647-c-60-iso10646-1
$ xfontsel -pattern "-misc-gb18030 bitmap-*"
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  45 (X_OpenFont)
  Value in failed request:  0xc00043
  Serial number of failed request:  196
  Current serial number in output stream:  197
$ xfontsel -font "-misc-gb18030 bitmap-*"
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  45 (X_OpenFont)
  Value in failed request:  0xc0000c
  Serial number of failed request:  22
  Current serial number in output stream:  23
```
Or run xfontsel with no parameters, and after font processing finishes, select 2147483647 from the "resy" menu, and xfontsel will crash.

On Intel Mac mini (2018) also running macOS 12.4, XQuartz 2.8.2 or 2.8.3:
```
$ xlsfonts | grep "gb18030 bitmap"
-misc-gb18030 bitmap-thin-r-ultracondensed--20-0-75--2147483648-c-60-cns11643-2
-misc-gb18030 bitmap-thin-r-ultracondensed--20-0-75--2147483648-c-60-iso10646-1
$ xfontsel -pattern "-misc-gb18030 bitmap-*"
gives "no names match"
$ xfontsel -font "-misc-gb18030 bitmap-*"
Warning: Cannot convert string "-misc-gb18030 bitmap-*" to type FontStruct

```
Notice the bogus RESY value for this font differs on Intel vs M1. On Intel, the font's RESY value is a negative value, -2147483648 dots per inch (-2^31, or -0x80000000), while on M1 it's 2147483647 dots per inch (2^31-1, or 0x7FFFFFFF). Looks like the negative RESY value on Intel (which results in an extra hyphen in its XLFD font name, making its name invalid) prevents this broken font from crashing xfontsel on Intel.

The defective core font "misc-gb18030 bitmap" should be either repaired or removed.

**Comment by jeremyhu** [comment]
We're just packaging the upstream fonts, unmodified.  Can you identify which font file is causing the issue?  If you could report the issue upstream at https://gitlab.freedesktop.org (and even better, provide a fix), that would be great.

**Comment by jeremyhu** [comment]
Oh... looks like it's an OSX font:

[1002] /opt/X11 $ grep -R 'gb18030 bitmap' .
./share/system_fonts/Supplemental/fonts.dir:NISC18030.ttf -misc-gb18030 bitmap-thin-r-ultracondensed--20-0-75-2147483647-c-60-cns11643-2
./share/system_fonts/Supplemental/fonts.dir:NISC18030.ttf -misc-gb18030 bitmap-thin-r-ultracondensed--20-0-75-2147483647-c-60-iso10646-1

**Comment by jeremyhu** [comment]
I'm going to update the script to ignore NISC18030.ttf.

**Comment by jeremyhu** [comment]
rdar://103687793
