### ISSUE TITLE
in version 2.8.4 - "C-z" does not iconify emacs

### ISSUE THREAD

**Issue by petermao** [XQuartz/XQuartz#310]
running OSX 12.6.1 on a 2020 13" MBP.
emacs 28.2

C-z runs `iconify-frame` in emacs.  Works on XQuartz 2.8.2 (and all earlier versions), but not on XQuartz 2.8.4.

I have not checked 2.8.3.

On 2.8.4, the only change is the cursor in the current buffer, which changes from solid rectangle to open rectangle.

**Comment by jeremyhu** [comment]
XQuartz doesn't ship emacs.  Can you reduce this a bit?  Maybe by using xev?  Do you see a difference in the events being delviered to X11 clients?

**Comment by petermao** [comment]
No difference in the events, and now magically, C-z works properly now under both 2.8.2 and 2.8.4.  I can't explain it...
