### ISSUE TITLE
failed installation on Mac M1 Ventura 13.0.1

### ISSUE THREAD

**Issue by yczhao7** [XQuartz/XQuartz#311]
Hi everyone, I tried to install different versions but all failed at the last step. Anyone knows why? This is a required software for my statistics class so I would really appreciate it if someone could help me! Thank you!!!
<img width="620" alt="image" src="https://user-images.githubusercontent.com/65551587/210929081-0e450a5c-93e8-44d6-9501-fbf5401b47c3.png">

**Comment by jeremyhu** [comment]
You'll need to check /var/log/install.log to determine why the isntallation failed.

**Comment by danecross** [comment]
Hello, I am having the same exact problem (I have the same operating system). Here is the part of install.log that relates to this install:
[install.log](https://github.com/XQuartz/XQuartz/files/10696733/install.log)

**Comment by jeremyhu** [comment]
```
Error Domain=PKXARArchiveErrorDomain Code=101 \"archive open failed\" UserInfo={NSURL=file:///Users/danecross/Library/CloudStorage/Dropbox/Mac/Downloads/XQuartz-2.8.5.pkg, NSFileOwnerAccountID=501, NSFileHFSTypeCode=0, NSFileSystemFileNumber=8596865, NSFileExtensionHidden=false, NSFileSystemNumber=16777233, NSFileSize=107523825, NSFileGroupOwnerAccountID=20, NSFileHFSCreatorCode=0, NSFileOwnerAccountName=danecross, NSFilePosixPermissions=420, NSFileCreationDate=2023-02-09 11:27:55 +0000, NSFileType=NSFileTypeRegular, NSFileProtectionKey=NSFileProtectionCompleteUntilFirstUserAuthentication, NSFileGroupOwnerAccountName=staff, NSFileReferenceCount=1, NSFileModificationDate=2023-02-09 11:28:05 +0000, NSLocalizedDescription=archive open failed}
```

I suggest you rule out DropBox as a reason the open failed.  Please copy the file out of dropbox.  If it persists, validate the checksum against the checksum files.
