### ISSUE TITLE
Will releases be .pkg from v2.8.3 onward?

### ISSUE THREAD

**Issue by 1-rphillips** [XQuartz/XQuartz#313]
Hi there,

just wanted to know if the change from .dmg to .pkg was a *temporary* fluke, or if it's how you'll be doing releases for the foreseeable future.

Cheers

**Comment by jeremyhu** [comment]
Please direct questions to the mailing list rather than as new bug reports.  There is no intention to make them .dmg any more now that Sparkle supports flag .pkg distribution.  You can find out more in https://github.com/XQuartz/XQuartz/issues/199
