### ISSUE TITLE
Using dash as default /bin/sh would cause `privileged_startx` fail

### ISSUE THREAD

**Issue by LdBeth** [XQuartz/XQuartz#316]
Symbol link `/bin/dash` to `/private/var/select/sh` to change default `/bin/sh` as dash shell (to reproduce the issue probably needs a reboot, since it may be related to some scripts that was run at boot) seems would cause a cryptic error message when `startx` or any time executing `/op/X11/libexec/privileged_startx`:
```
privileged_startx: client: (os/kern) failure
```

Although most people won't change the default setting of using `/bin/bash` as the `sh`, for people exploring the probability of reducing bashism on their systems this is a risk they should know.

---

This is tested with Monterey v12.6.2 (21G320) on Intel MacBook，affecting all recent release versions of XQuartz from 2.8.2 to 2.8.5-beta

**Comment by jeremyhu** [comment]
I'm glad to see folks making use of /private/var/select/sh to switch to dash.  I didn't really do much other than add the sh(1) man page to advertise it.  Thanks for helping to make scripts more portable.  

checkbashisms is a great tool if you haven't discovered it yet: https://salsa.debian.org/debian/devscripts.git
