### ISSUE TITLE
Xquartz 2.8.5 stopped starting, Ventura 13.2.1

### ISSUE THREAD

**Issue by Brassrat** [XQuartz/XQuartz#325]
Xquartz was working fine until today ... now it doesn't start. I think the only thing that changed on my system (M1 macos running Ventura 13.2.1) since yesterday is Xcode, which i updated to 14.2.
But when i click on the X icon, it bounces once and stops.
There is nothing in the system.log. 
the DISPLAY variable is being set (/private/tmp/com.apple.launchd.JQz5QhNTHd/org.xquartz:0)
if i run  bash -x /opt/X11/bin/startx -- /opt/X11/bin/Xquartz it seems to work and ends up invoking xinit which says its waiting for the Xserver and eventually times-out with unable to connect.

I don't know what other log files i should look at.
I've removed/reinstalled using both a dmg and via brew.
I've restarted my system multiple times (after doing the install)

**Comment by Brassrat** [comment]
Now i notice that every so often the X logo in the dock bounces once ... so it seems that something is still trying to start it. There are a bunch of processes, the .serverauth.XXXX file name keeps changing.
```

>     0 18177     1   0 11:56AM ??         0:00.25 /opt/X11/libexec/privileged_startx -d /opt/X11/etc/X11/xinit/privileged_startx.d
>   501 87625     1   0  1:32PM ??         0:00.01 /opt/X11/libexec/launchd_startx /opt/X11/bin/startx -- /opt/X11/bin/Xquartz
>   501 87626 87625   0  1:32PM ??         0:00.01 /bin/sh /opt/X11/bin/startx -- /opt/X11/bin/Xquartz
>   501 87791 87626   0  1:32PM ??         0:00.01 xinit /opt/X11/etc/X11/xinit/xinitrc -- /opt/X11/bin/Xquartz :0 -listen tcp -iglx -auth /Users/brassrat/.serverauth.XXXX
>   501 87792 87791   0  1:32PM ??         0:00.02 /opt/X11/bin/Xquartz :0 -listen tcp -iglx -auth /Users/brassrat/.serverauth.XXXX
```

but the /Users/brassrat/.serverauth.XXXX file is removed by the startx script when it fails ...

so is there some permissions missing somewhere preventing the Xquartz server from allowing connections ?

**Comment by jeremyhu** [comment]
Check the log file in ~/Library/Logs/X11 to see what's happening.

Most likely cause of this is that the client side (/opt/X11/etc/X11/xinit/xinitrc) is terminating because of a bug in your shell init scripts.  Folks usually move them all aside and then bisect to find the cause.

**Comment by Brassrat** [comment]
The org.xquartz.log file is empty. Which why I am at a loss as to what started going wrong.

Which shell init scripts are you talking about? Not my .bashrc or .bash_profile.

 

Are you talking about the scripts in /opt/X11/etc/X11/xinit/xinitrc.d ? or privileged_startx.d ?

I never touch these files or added anything to them

 

I know it’s not Xquartz itself as I have 2.8.5 running on 2 other systems. And it was working fine and then stopped working.

I did install a new Xcode that day …can’t see why that would cause problems (and I backed up xcode to previous version without any progress on this problem)

My company had me run a tool to uninstall the ‘atom’ editor … don’t know exactly what it might have done …

My company also installs security updates, etc automatically so some other files may have changed or security configurations may have changed

 

 

I appreciate your trying to help me … while I have been using xwindows and xquartz for years I am not really familiar with the implementation or startup of the server.

But not having it is definitely a problem for me

 

Thanks,

-jay

 

 

 

From: Jeremy Huddleston Sequoia ***@***.***>
Reply-To: XQuartz/XQuartz ***@***.***>
Date: Thursday, February 16, 2023 at 10:53 PM
To: XQuartz/XQuartz ***@***.***>
Cc: Brassrat ***@***.***>, Author ***@***.***>
Subject: Re: [XQuartz/XQuartz] Xquartz 2.8.5 stopped starting, Ventura 13.2.1 (Issue #325)
Resent-From: ***@***.***>
Resent-Date: Thursday, February 16, 2023 at 10:52 PM

 

Check the log file in ~/Library/Logs/X11 to see what's happening.

Most likely cause of this is that the client side (/opt/X11/etc/X11/xinit/xinitrc) is terminating because of a bug in your shell init scripts. Folks usually move them all aside and then bisect to find the cause.

**Comment by jeremyhu** [comment]
Yes, I am talking about ~/.profile, ~/.bash_profile, ~/.bashrc, etc.  And yes if you have ~/.xinitrc, move that aside as well.

**Comment by Brassrat** [comment]
Well, you are quite correct!  

There was an issue with my .bashrc … but I don’t understand why it is causing a problem for starting Xquartz.

That is, the .bashrc was source’ing other scripts which eventually did a ‘shift’ command (changes to these other scripts is why problem started happening, .bashrc had not changed which obscured the source of the problem)

 

After doing some testing, I have determined that adding the following to the beginning of my .bashrc will cause the problem:

shift

 

However, it does not cause a problem when creating an iTerm or Terminal window or an xterm window (after xquartz is running)

i.e., the presence of the shift command is sufficient to cause the problem for xquartz starting but not for any other apps

 

I’m not exactly sure how Xquartz is launched … I am using homebrew bash as my SHELL.

But, /Applications/Utilities/XQuartz.app/Contents/MacOS/X11 and /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.sh fail but /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin is ok.

 

Thanks again for pointing me in the right direction.

-jay

 

 

From: Jeremy Huddleston Sequoia ***@***.***>
Reply-To: XQuartz/XQuartz ***@***.***>
Date: Sunday, February 19, 2023 at 10:23 PM
To: XQuartz/XQuartz ***@***.***>
Cc: Brassrat ***@***.***>, Author ***@***.***>
Subject: Re: [XQuartz/XQuartz] Xquartz 2.8.5 stopped starting, Ventura 13.2.1 (Issue #325)
Resent-From: ***@***.***>
Resent-Date: Sunday, February 19, 2023 at 10:22 PM

 

Yes, I am talking about ~/.profile, ~/.bash_profile, ~/.bashrc, etc. And yes if you have ~/.xinitrc, move that aside as well.

**Comment by ilariagnd** [comment]
@Brassrat I'm having the same issue. Could you please report how you changed the .bashrc file to solve the issue? thank you in advance!

**Comment by Brassrat** [comment]
I really didn't solve the problem, I just made sure that no shift is done while executing the .bashrc or any script sourced by it. Note, my .bashrc didn't have the shift, I just tried to reduce the issue to the minimal change to demonstrate it. 
Obviously the issue is how the x11.sh launches the process. But that doesn't help much.

Sorry I can't be of more help.

--
  Jay Goldman
***@***.***

**Comment by jeremyhu** [comment]
No, that's definitely the solution.  You should not be doing a `shift` in .bashrc.
