### ISSUE TITLE
Menus on Motif programs are not drawn completely

### ISSUE THREAD

**Issue by dpeterc** [XQuartz/XQuartz#330]
This problem appeared on XQuartz 2.8.5beta3
On previous versions it worked correctly, but opening of menus was very slow, so it probably gets enough time to redraw on expose event.
The slowness was due to poor Motif implementation of XFT, which caused excessive X server round trips while checking the background color on each menu entry, in order to draw antialiased text. And related to some timing setting in XQuartz.
Now drawing is quick (even on unpatched Motif), but sometimes incomplete.

This is the incomplete drawing of menus on xnedit on Ventura 13.3 beta and Xquartz 2.8.5
https://user-images.githubusercontent.com/15419249/220484605-d45442e0-b7d5-4755-adce-bd4ecaafe9ae.mp4

And this is the correct behavior on Mojave and XQuartz 2.8.1
https://user-images.githubusercontent.com/15419249/220484748-9def3878-5e3a-4718-9742-2da2ee0fe244.mp4
The Motif in this case was patched, so drawing of menus is quick, since XQueryColor round trips are cached.
So opening of menus is quick, but the drawing of menus is also complete.

**Comment by jeremyhu** [comment]
#323
