### ISSUE TITLE
Xquartz problem

### ISSUE THREAD

**Issue by m77it** [XQuartz/XQuartz#331]
Dear all,
When I try using a software (POKY), XQuartz opens but the software does not start. XQuartz continues the jumping and cannot stop, so I need to restart the pc.
I'm using Ventura on the M1 laptop and the latest XQuartz version.
Any suggestion?
Thanks
Marco

**Comment by jeremyhu** [comment]
This is usually an issue with the user's startup scripts (~/.bashrc, ~/.profile, ~/.zshrs, ~/.profile, etc)
