### ISSUE TITLE
Cannot display xclock with xQuartz v2.8.5 on MacOS 12.6.3

### ISSUE THREAD

**Issue by wx0604** [XQuartz/XQuartz#334]
Hello,

My MacBook Pro was upgraded to MacOS 12.6.3. After that, xQuartz 2.8.5 was installed. Everything looks normal, but when run "xclock" or other x-window app, it will be hanging and does nothing, no new window prompt.
$ xclock

The DISPLAY seems correct:
$ echo $DISPLAY
/private/tmp/com.apple.launchd.hPuWECXro9/org.xquartz:0

$ which xclock
/opt/X11/bin/xclock

I have re-installed the XQuartz-2.8.5.pkg several times but no luck.

Could someone provide me some suggestion how I should troubleshoot such issue?

Thanks,
wangxn

**Comment by jeremyhu** [comment]
This is usually indicative of something wrong with your shell init scripts (eg: ~/.bashrc, ~/.profile, etc).  I'd move those aside and try again.

**Comment by wx0604** [comment]
Thank you, Jeremy,

I renamed .bashrc to B2bashrc and re-logged in the Mac, but it was the same issue. 

Is there something else I can check?

**Comment by wx0604** [comment]
Sorry, I accidentally closed the case. I still need to resolve this issue. Any help will be very appreciated.

**Comment by randcraw** [comment]
I'm having the exact same problem, also with 12.6.3.  I removed the existing XQuartz and /usr/X11, installed XQuartz 2.8.1 instead, but still no luck.  I see XQuartz running in Activity Monitor as well as the X app, but XQuartz doesn't appear in my dock.

**Comment by jeremyhu** [comment]
xclock launches fine for me (as do other clients). Can you try with a new user account and try to identify the cause of the failure?

**Comment by wx0604** [comment]
I tried to "su another-user" but I got the error:

$ xterm
xterm: Xt error: Can't open display: /private/tmp/com.apple.launchd.7OSCORmPqB/org.xquartz:0

with "su - another-user", display appears undefined:

$ xterm
xterm: Xt error: Can't open display: 
xterm: DISPLAY is not set

**Comment by jeremyhu** [comment]
No, that's not what I meant.

Create a new user account, then logout.  Then log in as that new user, and try again

**Comment by wx0604** [comment]
I tried to log in as a different user but saw no difference. The same problem: it was hanging.

Is there some log file I can check because it did not show any error message on the screen?

**Comment by jeremyhu** [comment]
You can check ~/Library/Logs/X11 and launchd's logs and the system logging to see what's happening.

**Comment by randcraw** [comment]
Thanks, but I have no folder called~/Library/Logs/X11.  When I launch XQuartz, a dot appears below the icon in my dock only for a second then disappears, so apparently it fails to launch.

So I did 'cd /Applications/Utilities/XQuartz.app/Contents/MacOS', then I ran X11.bin directly:
$ ./X11.bin

Then a white xterm appeared, and a dot appeared below the XQuartz icon in my dock which did NOT disappear.  Subsequently I could run the various X apps just fine (xeyes, xclock, etc).  I can also kill the xterm window (by clicking on the red dot in the upper left of the window's title bar), yet XQuartz continues to run (the dot below its icon remains in the dock).  Then when I check, now there *is* a file: ~/Library/Logs/X11/org.xquartz.log.

(I then killed XQuartz and tried again to launch it from the dock.  Again it failed and no info was written to the log file.)

It seems the script 'X11.sh' in the MacOS folder that launches X11.bin fails to run properly on my Mac (Monterey 12.6.5).  My shell is bash, but I couldn't run X11.sh from bash.  When I type './X11.sh' into a bash terminal the executable doesn't launch and the terminal prompt returns immediately.  And when I run it with a dot operator, '. X11.sh', It produces this error message:  

dirname: illegal option -- busage: dirname string [...]
reading .profile

[Process completed]

And the shell exits and freezes.  Sounds like there's a bug in X11.sh which causes it to fail before it launches the X11.bin executable.  Perhaps it expects CLI parameters that are absent when launched in bash?

**Comment by jeremyhu** [comment]
Nope, sounds consistent with a bug in your shell init scripts.  That script is there to get XQuartz's environment consistent with your login shell environment.  Check ~/.profile, ~/.bashrc, and ~/.bash_profile.  I suggest moving them aside (eg: backup / delete) to test.
