### ISSUE TITLE
control-S broken on nedit

### ISSUE THREAD

**Issue by alainhebert** [XQuartz/XQuartz#336]
control-S is broken with nedit. It produces <dc3> in text instead of saving. The solution is to add the following lines in the .xinitrc file:
  keycode  79 = KP_7
  keycode  80 = KP_8
  keycode  81 = KP_9
  keycode  83 = KP_4
  keycode  84 = KP_5
  keycode  85 = KP_6
  keycode  87 = KP_1
  keycode  88 = KP_2
  keycode  89 = KP_3
  keycode  90 = KP_0
  keycode  91 = KP_Decimal
However, file .xinitrc doesn't exist with XQuartz. How can I fix nedit?

**Comment by dpeterc** [comment]
If you use xquartz a lot, and run nedit from the command line, you can add to
.profile or .bashrc
xmodmap -e "keycode 79 = KP_7"
...

Alternatively, you can use xnedit (a modern fork of nedit), where Ctrl+S works correctly on MacOS.
https://sourceforge.net/projects/xnedit/

**Comment by jeremyhu** [comment]
You can add whatever you want as a script into ~/.xinitrc.d/.  That's reccomended over modifying ~/.xinitrc

You should not add it to ~/.profile or ~/.bashrc.

**Comment by jeremyhu** [comment]
The keyboard mapping is generated by querying macOS... what is the output of `xmodmap -pk` before your changes?

**Comment by alainhebert** [comment]
***@***.*** ~ % 
***@***.*** ~ % xmodmap -pk                               
There are 4 KeySyms per KeyCode; KeyCodes range from 8 to 255.

    KeyCode	Keysym (Keysym)	...
    Value  	Value   (Name) 	...

      8    	0x0061 (a)	0x0041 (A)	0x00e5 (aring)	0x00c5 (Aring)	
      9    	0x0073 (s)	0x0053 (S)	0x00df (ssharp)	0x00cd (Iacute)	
     10    	0x0064 (d)	0x0044 (D)	0x08ef (partialderivative)	0x00ce (Icircumflex)	
     11    	0x0066 (f)	0x0046 (F)	0x08f6 (function)	0x00cf (Idiaeresis)	
     12    	0x0068 (h)	0x0048 (H)	0x01ff (abovedot)	0x00d3 (Oacute)	
     13    	0x0067 (g)	0x0047 (G)	0x00a9 (copyright)	0x01bd (doubleacute)	
     14    	0x007a (z)	0x005a (Z)	0x07d9 (Greek_OMEGA)	0x00b8 (cedilla)	
     15    	0x0078 (x)	0x0058 (X)	0x1002248 (approxeq)	0x01b2 (ogonek)	
     16    	0x0063 (c)	0x0043 (C)	0x00e7 (ccedilla)	0x00c7 (Ccedilla)	
     17    	0x0076 (v)	0x0056 (V)	0x08d6 (radical)	0x10025ca (U25CA)	
     18    	0x00a7 (section)	0x00b1 (plusminus)	0x00a7 (section)	0x00b1 (plusminus)	
     19    	0x0062 (b)	0x0042 (B)	0x08bf (integral)	0x02b9 (idotless)	
     20    	0x0071 (q)	0x0051 (Q)	0x13bd (oe)	0x13bc (OE)	
     21    	0x0077 (w)	0x0057 (W)	0x1002211 (U2211)	0x0afe (doublelowquotemark)	
     22    	0x0065 (e)	0x0045 (E)	0xfe51 (dead_acute)	0x00b4 (acute)	
     23    	0x0072 (r)	0x0052 (R)	0x00ae (registered)	0x1002030 (U2030)	
     24    	0x0079 (y)	0x0059 (Y)	0x00a5 (yen)	0x00c1 (Aacute)	
     25    	0x0074 (t)	0x0054 (T)	0x0af1 (dagger)	0x01b7 (caron)	
     26    	0x0031 (1)	0x0021 (exclam)	0x00a1 (exclamdown)	0x1002044 (U2044)	
     27    	0x0032 (2)	0x0040 (at)	0x0ac9 (trademark)	0x20ac (EuroSign)	
     28    	0x0033 (3)	0x0023 (numbersign)	0x00a3 (sterling)	0x1002039 (U2039)	
     29    	0x0034 (4)	0x0024 (dollar)	0x00a2 (cent)	0x100203a (U203A)	
     30    	0x0036 (6)	0x005e (asciicircum)	0x00a7 (section)	0x100fb02 (UFB02)	
     31    	0x0035 (5)	0x0025 (percent)	0x08c2 (infinity)	0x100fb01 (UFB01)	
     32    	0x003d (equal)	0x002b (plus)	0x08bd (notequal)	0x00b1 (plusminus)	
     33    	0x0039 (9)	0x0028 (parenleft)	0x00aa (ordfeminine)	0x00b7 (periodcentered)	
     34    	0x0037 (7)	0x0026 (ampersand)	0x00b6 (paragraph)	0x0af2 (doubledagger)	
     35    	0x002d (minus)	0x005f (underscore)	0x0aaa (endash)	0x0aa9 (emdash)	
     36    	0x0038 (8)	0x002a (asterisk)	0x0ae6 (enfilledcircbullet)	0x00b0 (degree)	
     37    	0x0030 (0)	0x0029 (parenright)	0x00ba (masculine)	0x0afd (singlelowquotemark)	
     38    	0x005d (bracketright)	0x007d (braceright)	0x0ad0 (leftsinglequotemark)	0x0ad1 (rightsinglequotemark)	
     39    	0x006f (o)	0x004f (O)	0x00f8 (oslash)	0x00d8 (Oslash)	
     40    	0x0075 (u)	0x0055 (U)	0xfe57 (dead_diaeresis)	0x00a8 (diaeresis)	
     41    	0x005b (bracketleft)	0x007b (braceleft)	0x0ad2 (leftdoublequotemark)	0x0ad3 (rightdoublequotemark)	
     42    	0x0069 (i)	0x0049 (I)	0xfe52 (dead_circumflex)	0x10002c6 (U02C6)	
     43    	0x0070 (p)	0x0050 (P)	0x07f0 (Greek_pi)	0x100220f (U220F)	
     44    	0xff0d (Return)	0x0000 (NoSymbol)	0xff0d (Return)	
     45    	0x006c (l)	0x004c (L)	0x00ac (notsign)	0x00d2 (Ograve)	
     46    	0x006a (j)	0x004a (J)	0x1002206 (U2206)	0x00d4 (Ocircumflex)	
     47    	0x0027 (apostrophe)	0x0022 (quotedbl)	0x00e6 (ae)	0x00c6 (AE)	
     48    	0x006b (k)	0x004b (K)	0x10002da (U02DA)	0x100f8ff (UF8FF)	
     49    	0x003b (semicolon)	0x003a (colon)	0x0aae (ellipsis)	0x00da (Uacute)	
     50    	0x005c (backslash)	0x007c (bar)	0x00ab (guillemotleft)	0x00bb (guillemotright)	
     51    	0x002c (comma)	0x003c (less)	0x08bc (lessthanequal)	0x00af (macron)	
     52    	0x002f (slash)	0x003f (question)	0x00f7 (division)	0x00bf (questiondown)	
     53    	0x006e (n)	0x004e (N)	0xfe53 (dead_tilde)	0x10002dc (U02DC)	
     54    	0x006d (m)	0x004d (M)	0x00b5 (mu)	0x00c2 (Acircumflex)	
     55    	0x002e (period)	0x003e (greater)	0x08be (greaterthanequal)	0x01a2 (breve)	
     56    	0xff09 (Tab)	0x0000 (NoSymbol)	0xff09 (Tab)	
     57    	0x0020 (space)	0x0000 (NoSymbol)	0x00a0 (nobreakspace)	
     58    	0x0060 (grave)	0x007e (asciitilde)	0xfe50 (dead_grave)	0x0060 (grave)	
     59    	0xff08 (BackSpace)	0x0000 (NoSymbol)	0xff08 (BackSpace)	
     60    	0x1000003 (no name)	0x0000 (NoSymbol)	0x1000003 (no name)	
     61    	0xff1b (Escape)	0x0000 (NoSymbol)	0xff1b (Escape)	
     62    	
     63    	0xffe7 (Meta_L)	0x0000 (NoSymbol)	0xffe7 (Meta_L)	
     64    	0xffe1 (Shift_L)	0x0000 (NoSymbol)	0xffe1 (Shift_L)	
     65    	0xffe5 (Caps_Lock)	0x0000 (NoSymbol)	0xffe5 (Caps_Lock)	
     66    	0xff7e (Mode_switch)	0x0000 (NoSymbol)	0xff7e (Mode_switch)	
     67    	0xffe3 (Control_L)	0x0000 (NoSymbol)	0xffe3 (Control_L)	
     68    	0xffe2 (Shift_R)	0x0000 (NoSymbol)	0xffe2 (Shift_R)	
     69    	0xff7e (Mode_switch)	0x0000 (NoSymbol)	0xff7e (Mode_switch)	
     70    	0xffe4 (Control_R)	0x0000 (NoSymbol)	0xffe4 (Control_R)	
     71    	0xffe8 (Meta_R)	0x0000 (NoSymbol)	0xffe8 (Meta_R)	
     72    	0xffce (F17)	0x0000 (NoSymbol)	0xffce (F17)	
     73    	0xffae (KP_Decimal)	0x0000 (NoSymbol)	0xffae (KP_Decimal)	
     74    	
     75    	0xffaa (KP_Multiply)	0x0000 (NoSymbol)	0xffaa (KP_Multiply)	
     76    	
     77    	0xffab (KP_Add)	0x0000 (NoSymbol)	0xffab (KP_Add)	
     78    	
     79    	0xffb7 (KP_7)	0x0000 (NoSymbol)	0xffb7 (KP_7)	
     80    	0xffb8 (KP_8)	0x0000 (NoSymbol)	0xffb8 (KP_8)	
     81    	0xffb9 (KP_9)	0x0000 (NoSymbol)	0xffb9 (KP_9)	
     82    	
     83    	0xffb4 (KP_4)	0x0000 (NoSymbol)	0xffb4 (KP_4)	
     84    	0xffb5 (KP_5)	0x0000 (NoSymbol)	0xffb5 (KP_5)	
     85    	0xffb6 (KP_6)	0x0000 (NoSymbol)	0xffb6 (KP_6)	
     86    	0xffad (KP_Subtract)	0x0000 (NoSymbol)	0xffad (KP_Subtract)	
     87    	0xffb1 (KP_1)	0x0000 (NoSymbol)	0xffb1 (KP_1)	
     88    	0xffb2 (KP_2)	0x0000 (NoSymbol)	0xffb2 (KP_2)	
     89    	0xffb3 (KP_3)	0x0000 (NoSymbol)	0xffb3 (KP_3)	
     90    	0xffb0 (KP_0)	0x0000 (NoSymbol)	0xffb0 (KP_0)	
     91    	0xffae (KP_Decimal)	0x0000 (NoSymbol)	0xffae (KP_Decimal)	
     92    	0xffb2 (KP_2)	0x0000 (NoSymbol)	0xffb2 (KP_2)	
     93    	0xffb3 (KP_3)	0x0000 (NoSymbol)	0xffb3 (KP_3)	
     94    	0xffb4 (KP_4)	0x0000 (NoSymbol)	0xffb4 (KP_4)	
     95    	0xffb5 (KP_5)	0x0000 (NoSymbol)	0xffb5 (KP_5)	
     96    	0xffb6 (KP_6)	0x0000 (NoSymbol)	0xffb6 (KP_6)	
     97    	0xffb7 (KP_7)	0x0000 (NoSymbol)	0xffb7 (KP_7)	
     98    	0xffd1 (F20)	0x0000 (NoSymbol)	0xffd1 (F20)	
     99    	0xffb8 (KP_8)	0x0000 (NoSymbol)	0xffb8 (KP_8)	
    100    	0xffb9 (KP_9)	0x0000 (NoSymbol)	0xffb9 (KP_9)	
    101    	
    102    	
    103    	
    104    	0xffc2 (F5)	0x0000 (NoSymbol)	0xffc2 (F5)	
    105    	0xffc3 (F6)	0x0000 (NoSymbol)	0xffc3 (F6)	
    106    	0xffc4 (F7)	0x0000 (NoSymbol)	0xffc4 (F7)	
    107    	0xffc0 (F3)	0x0000 (NoSymbol)	0xffc0 (F3)	
    108    	0xffc5 (F8)	0x0000 (NoSymbol)	0xffc5 (F8)	
    109    	0xffc6 (F9)	0x0000 (NoSymbol)	0xffc6 (F9)	
    110    	
    111    	0xffc8 (F11)	0x0000 (NoSymbol)	0xffc8 (F11)	
    112    	
    113    	0xffca (F13)	0x0000 (NoSymbol)	0xffca (F13)	
    114    	0xffcd (F16)	0x0000 (NoSymbol)	0xffcd (F16)	
    115    	0xffcb (F14)	0x0000 (NoSymbol)	0xffcb (F14)	
    116    	
    117    	0xffc7 (F10)	0x0000 (NoSymbol)	0xffc7 (F10)	
    118    	0xff67 (Menu)	0x0000 (NoSymbol)	0xff67 (Menu)	
    119    	0xffc9 (F12)	0x0000 (NoSymbol)	0xffc9 (F12)	
    120    	
    121    	0xffcc (F15)	0x0000 (NoSymbol)	0xffcc (F15)	
    122    	0xff6a (Help)	0x0000 (NoSymbol)	0xff6a (Help)	
    123    	0xff50 (Home)	0x0000 (NoSymbol)	0xff50 (Home)	
    124    	0xff55 (Prior)	0x0000 (NoSymbol)	0xff55 (Prior)	
    125    	0xffff (Delete)	0x0000 (NoSymbol)	0xffff (Delete)	
    126    	0xffc1 (F4)	0x0000 (NoSymbol)	0xffc1 (F4)	
    127    	0xff57 (End)	0x0000 (NoSymbol)	0xff57 (End)	
    128    	0xffbf (F2)	0x0000 (NoSymbol)	0xffbf (F2)	
    129    	0xff56 (Next)	0x0000 (NoSymbol)	0xff56 (Next)	
    130    	0xffbe (F1)	0x0000 (NoSymbol)	0xffbe (F1)	
    131    	0xff51 (Left)	0x0000 (NoSymbol)	0xff51 (Left)	
    132    	0xff53 (Right)	0x0000 (NoSymbol)	0xff53 (Right)	
    133    	0xff54 (Down)	0x0000 (NoSymbol)	0xff54 (Down)	
    134    	0xff52 (Up)	0x0000 (NoSymbol)	0xff52 (Up)	
    135    	
    136    	
    137    	
    138    	
    139    	
    140    	
    141    	
    142    	
    143    	
    144    	
    145    	
    146    	
    147    	
    148    	
    149    	
    150    	
    151    	
    152    	
    153    	
    154    	
    155    	
    156    	
    157    	
    158    	
    159    	
    160    	
    161    	
    162    	
    163    	
    164    	
    165    	
    166    	
    167    	
    168    	
    169    	
    170    	
    171    	
    172    	
    173    	
    174    	
    175    	
    176    	
    177    	
    178    	
    179    	
    180    	
    181    	
    182    	
    183    	
    184    	
    185    	
    186    	
    187    	
    188    	
    189    	
    190    	
    191    	
    192    	
    193    	
    194    	
    195    	
    196    	
    197    	
    198    	
    199    	
    200    	
    201    	
    202    	
    203    	
    204    	
    205    	
    206    	
    207    	
    208    	
    209    	
    210    	
    211    	
    212    	
    213    	
    214    	
    215    	
    216    	
    217    	
    218    	
    219    	
    220    	
    221    	
    222    	
    223    	
    224    	
    225    	
    226    	
    227    	
    228    	
    229    	
    230    	
    231    	
    232    	
    233    	
    234    	
    235    	
    236    	
    237    	
    238    	
    239    	
    240    	
    241    	
    242    	
    243    	
    244    	
    245    	
    246    	
    247    	
    248    	
    249    	
    250    	
    251    	
    252    	
    253    	
    254    	
    255    	
***@***.*** ~ %

**Comment by alainhebert** [comment]
There is no .xintrc or .xintrc.d file on OSX. The issue can be reproduced by anyone installing edit on OSX. Just install it using

brew install nedit

And you will observe the strange behaviour. This is sad because nedit is my favourite editor.

**Comment by jeremyhu** [comment]
> There is no .xintrc or .xintrc.d file on OSX

You would need to *create* them.  They are definitely honored.  I was the one who made the change to introduce ~/.xinitrc.d support into xinit years ago.  Trust me, it's supported.

Your output shows that you already have those keycodes set by the system.

I opened nedit, wrote something, and hit ctrl-s, and the save dialog appeared.  This seems to be working...

**Comment by alainhebert** [comment]
Hi Jeremy

Maybe I was not clear in the issue description. If a do File/Save from the window menu, everything works correctly. If I do control-S, the problem appears. The file is not saved and a <dc3> character is written in the file I want to save:



I am using OSX 12.6.3 (Monterey) on a M2 Mac. The xintrc.d file was present.

Sorry for the confusion and thank you for your help.

Alain

**Comment by jeremyhu** [comment]
Ok, well my point is that ctrl-s brings up the save window.  If saving the file results in a bad file being saved, that doesn't seem at all related to the window server.  That would be a bug in nedit.
