### ISSUE TITLE
black background on XQuartz-2.8.5 and older when using Matlab and dragging windows

### ISSUE THREAD

**Issue by RobbieTheK** [XQuartz/XQuartz#338]
What kind of debug can I provide for a user who is experiencing this effect when moving windows within Matlab? This happens on many Matlab versions from 2018b - 2022b when launching from ssh -X to a Red Hat 7 cluster. He has tried setting Preferences -> MATLAB -> General -> Desktop -> uncheck "Use hardware acceleration if available" as well as opening Matlab with  `-noopengl.`

Note the Mac has a M1 processor which seems to be the main reason for this.

![figure3](https://user-images.githubusercontent.com/21204619/227033622-198d7cb0-a47f-4690-a959-95620571201f.jpg)

**Comment by raoultrines** [comment]
#31 ?

**Comment by RobbieTheK** [comment]
Bug still persists which suggestion in that thread should we try?

**Comment by jeremyhu** [comment]
This is a duplicate of that bug.  There is no fix for you to try.
