### ISSUE TITLE
Certificate error when installing XQuartz with brew cask

### ISSUE THREAD

**Issue by rvplan** [XQuartz/XQuartz#348]
Hi,
Tried to install XQuartz with option brew & cask, as stated in https://www.xquartz.org/releases/index.html
`brew install --cask xquartz`
`==> Downloading https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg`
`==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/201858552/619d0c12-2b10-4965-8ac3-62058ea775f1?X-Amz-Algo`
`==> Installing Cask xquartz`
`==> Running installer for xquartz; your password may be necessary.`
`Package installers may write to any location; options such as '--appdir' are ignored.`
`Password:`
`installer: Package name is`
`installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.`
`==> Purging files for version 2.8.5 of Cask xquartz`
**`Error: Failure while executing; '/usr/bin/sudo -u root -E LOGNAME=xxx -- /usr/sbin/installer -pkg /usr/local/Caskroom/xquartz/2.8.5/XQuartz-2.8.5.pkg -target /' exited with 1.`**

Advice is given to retry install with `-allowUntrusted`, don't know where to insert this option, since I've no hand on the chain: brew -> cask -> xquartz install -> Mac installer, etc.

But by following the command line that issue the error while being root, install went ok:
`mkdir -p /usr/local/Caskroom/xquartz/2.8.5`
`cd /usr/local/Caskroom/xquartz/2.8.5`
`wget https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg`
`installer -allowUntrusted -pkg /usr/local/Caskroom/xquartz/2.8.5/XQuartz-2.8.5.pkg -target /`

**Comment by jeremyhu** [comment]
Does it go ok if you *DON'T* specify `-allowUntrusted`?

**Comment by jeremyhu** [comment]
Worked for me...

```
[105] ~/Downloads $ curl -LO https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  102M  100  102M    0     0  28.1M      0  0:00:03  0:00:03 --:--:-- 34.3M

[106] ~/Downloads $ sudo installer -pkg XQuartz-2.8.5.pkg -target /
Password:
installer: Package name is 
installer: Installing at base path /
installer: The install was successful.
installer: The install requires logging out now.
```

**Comment by rvplan** [comment]
@jeremyhu Hello, thanks for the reply.
As mentionned before, I didn't encounter problem while doing the install manually on command line. With or without -allowUntrusted ("while being root, install went ok").

I was raising a concern about the fully automated install through brew and cask, which failed.
