### ISSUE TITLE
Strange visual artifacts on RHEL9, but RHEL6 is fine

### ISSUE THREAD

**Issue by gordonj7** [XQuartz/XQuartz#351]
Some coworkers of mine are having trouble using an Xwindows application hosted on a RHEL9 box, where lots of small vertical bars appear on the screen seemingly randomly.

Sometimes in a text entry area:

![xwindows_bars_black](https://github.com/XQuartz/XQuartz/assets/8886244/614dd00b-2466-4e07-915f-ca7e8ec7e350)

And sometimes overlaid on the app GUI:

![xwindows_bars_black2](https://github.com/XQuartz/XQuartz/assets/8886244/e50d8df0-9597-488f-9c40-b6947537e160)

They are both using new Macs, with XQuartz 2.8.5.  I am using an older Mac with XQuartz 2.7.11, and the issue does not appear for me.  Nor does it appear on my Windows 10 PC using XMing.

This issue does not appear at all when using the same app on a RHEL6 platform.

The sysadmins on the RHEL9 box thought the issue might have something to do with fonts.

One really weird part is that when they are screensharing on Zoom, the audience does not see the vertical bars; they are only on the person's local screen. They had to send me these screenshots so that I could even see the problem.

**Comment by dpeterc** [comment]
It could be that XQuartz is rendering the window at 32 bit depth (RGBA), while Zoom screensharing only takes 24 bits (RGB) to reduce the quantity of data it needs to transfer. If the error is in drawing the transparency component (alpha channel), that could disappear on Zoom. Just a wild guess.

**Comment by jeremyhu** [comment]
This si probably https://github.com/XQuartz/XQuartz/issues/323

**Comment by jstadni2** [comment]
This issue is still present when using 2.8.4, so it seems unrelated to #323.
