### ISSUE TITLE
XQuartz on mac0S ventura 13.4.1 - screen appears perfectly - when cursor over it goes black

### ISSUE THREAD

**Issue by bren139** [XQuartz/XQuartz#354]
I do my x11 forwarding using XQuartz 2.8.5 (xorg-server 21.1.6)
ssh -X user@machine ....../SASManagementConsole/9.4/sasmc

on mac0S ventura 13.4.1 

- the screen appears perfectly on the moment it comes up and I'm happy

then I try to use my cursor to work on it and the pop-up screen goes black in key places

all the button options are hidden then behind a sheer black in key sections of the screen

other sections are white

**Comment by raoultrines** [comment]
Are you using an Intel Mac or an M1 Mac? See also #31

**Comment by bren139** [comment]
M1 (Apple M1 pro)

**Comment by twanvanderschoot** [comment]
Same phenomenon here. On MBP 2023 with Apple M2 Max.  Tried it with XQ 2.8.5 and 2.8.6-beta. 

The case is very easy to reproduce: just start xterm from the menu, move cursor and the whole background becomes black.

**Comment by Yarden92** [comment]
same on macbook air m, ventura 13.4.1

**Comment by dtpoirot** [comment]
For all of us who are continuing to have the "screen goes black" issue... I get the same trying to run ZAP on a Ubuntu VM.

I ran `defaults write org.xquartz.X11 enable_render_extension 0` from the macOS shell. The command executed.
I then installed XQuartz 2.8.5 again and this time my apps look correct. 

I was just about to try the beta XQuartz releases. Now I am afraid to touch anything! :-/

**Comment by jeremyhu** [comment]
https://github.com/XQuartz/XQuartz/issues/31
