### ISSUE TITLE
Xquartz 2.8.5 crashes immediately after update to Venture 13.5

### ISSUE THREAD

**Issue by hugovaningen** [XQuartz/XQuartz#355]
I recently updated to Ventura 13.5 and now found Xquartz unfortunately does not work properly, it crashes immediatetely. I tried reinstalling Xquartz, reboot , all to no avail.
The console shows the log below.
Any advice greatly appreciated,

```
X11.app: main(): argc=1
	argv[0] = /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
Waiting for startup parameters via Mach IPC.
X11.app: No launchd socket handed off, unsetting DISPLAY
X11.app: do_start_x11_server(): argc=7
	argv[0] = /opt/X11/bin/Xquartz
	argv[1] = :0
	argv[2] = -nolisten
	argv[3] = tcp
	argv[4] = -iglx
	argv[5] = -auth
	argv[6] = /Users/hugo/.serverauth.773
[3047307.223] Xquartz starting:
[3047307.223] X.Org X Server 21.1.6
[3047307.223] _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[3047307.223] _XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
[3047307.223] _XSERVTransMakeAllCOTSServerListeners: failed to create listener for local
[3047307.223] (EE) 
Fatal server error:
[3047307.223] (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
[3047307.224] (EE) Server terminated with error (1). Closing log file.
```

**Comment by kprussing** [comment]
I just started having the same problem.

I tried:

1.  Completely uninstalling XQuartz following the [FAQ](https://www.xquartz.org/FAQs.html) and reinstalling from scratch. This did resolve the discrepancy between `echo $DISPLAY` and `launchctl getenv DISPLAY` mentioned in [295](https://github.com/XQuartz/XQuartz/issues/295#issuecomment-1325962004), but still no luck. 
2.  Hiding my login scripts to prevent XQuartz from loading them with no success.

Now, after trying to launch XQuartz using `open -a XQuartz`, it starts to bounce in the dock, closes immediately, and then starts to launch again (over and over again).

According to our IT, they have seen similar issues with our VPN client. They noticed that Apple now actively removes write permissions for users. They managed to get something working by changing the permissions of `/private/tmp` to 1777, but when I tried that it still didn't let me launch an xterm.

This isn't a solution, but hopefully it helps shed light on what may be going on.

**Comment by winstonstp** [comment]
It seems that XQuartz team has not solved the problem. I experienced the same problem that impacts greatly my work as Matlab requires XQuartz (2.8.5) to work properly remotely from Linux machine to iMac (Ventura 13.5.1) display. 
I am, therefore, hoping that the XQuartz team will find a solution pretty quickly. I would like for sure to known when and what to try in the meantime as all the posted semi-solutions do not work.

**Comment by kprussing** [comment]
It appears the fixing of the "bug" via an Apple security update is a bit of a luck game. I just updated to 13.5.2 and XQuartz is working again, but a coworker mentioned updating to 13.5.1 got XQuartz to work.

**Comment by ah73** [comment]
@kprussing confirming that the /private/tmp thing fix a user for us as well. We have been wrestling with the /private/tmp thing for a while now. Chrome updates, AnyConnect connections. But its really intermittent.

**Comment by ashill** [comment]
I have a similar issue on one machine, but the `/private/tmp` fix does not work and some other details are different. Same issue both with my user and a newly-created user.

I reinstall XQuartz, and it works for all users until a reboot. It stops working after a reboot: when I launch it (as any user), XQuartz bounces once in the dock and then stops. A reinstall fixes it for all users until the next boot.

I have this issue on a MacBook Air (M1) used primarily by a student (non-admin user) in both their account and mine (admin). I do not have this issue on my main work machine, a M1 Pro MacBook Pro (I'm the only user, and an admin). Both are running macOS 13.5.2.

`/private/tmp` already has `drwxrwxrwt` permissions, and running `sudo chmod 1777 /private/tmp` does not fix anything. I don't see any change to those permissions after a reboot either.

**Comment by winstonstp** [comment]
Ashill, I had the same problem and I was finally able to fix it after many tries and errors. That problem indicated to me that something wrong was happening at the reboot as it was working without rebooting. For me It started to happen when the network had problems at the university. I then looked at what was running at the reboot time. Microsoft Defender is running at the boot and it is unfortunately required by our university (Oregon State University) as they will not let us have a computer on the network with Microsoft Defender. .I found out that the filter&proxy (under setting system/network) had com.microsoft.wadv from Microsoft Defender enable. I disabled it and the problem was fixed. This had to be enable in my case. I remove it and it enables it by default. Problem is still fixed. Xquartz works after many reboots. Ashill, it is tedious to figure out but you might one to look at what runs at the reboots, something might have been corrupted for some reason that does not impact other softwares, so hard to guess.

**Comment by jeremyhu** [comment]
> Apple now actively removes write permissions for users.

That is not the case.

>  They managed to get something working by changing the permissions of /private/tmp to 1777,

Yes, I've seen reports of users haveing incorrect permissions on /private/tmp.  That is not something that Apple modifies.  Please investigate what on your system is breaking permissions on /private/tmp as that will have detrimental impacts on many software.

**Comment by subha-dash** [comment]
use this below script to open xquartz . it is working
================================================= 
#!/bin/bash

echo <password> | sudo -S rm -rf /tmp/.X11-unix 
mkdir -m 1777 /tmp/.X11-unix 
echo <password> | sudo -S chown root:wheel /tmp/.X11-unix
open /Applications/Utilities/XQuartz.app
=================================================
