### ISSUE TITLE
Incorrect screen size on Macbook Pro Retina (2023)

### ISSUE THREAD

**Issue by AntoineGautier** [XQuartz/XQuartz#357]
XQuartz 2.8.5 on Ventura 13.5.1 displays X windows in low resolution.
Running `xrandr` yields:
```
Screen 0: minimum 800 x 576, current 1920 x 1056, maximum 3840 x 2160
```
which shows that the current screen size is incorrect. 
I believe this is because macOS emulates a lower screen resolution by default: for instance 1920 x 1080 on a 3840 x 2160 monitor.
The following workarounds were tested but did not solve the issue.

- Changing XQuartz dpi setting as suggested in https://www.xquartz.org/FAQs.html: this has no effect.
- Changing the screen size with `xrandr --output default --mode 3840x2160`: this switches to black fullscreen mode w/o access to Mac desktop anymore (I need to type cmd+H to exit).

I would be happy if I could properly set the screen size in XQuartz (to match the one of my monitor) and deal with scaling X apps from the server side with `xrdb` and the variable `Xft.dpi` (which is what I do with WSLg on Windows).

**Comment by jeremyhu** [comment]
#350
