### ISSUE TITLE
How can I see a list of keymaps (bindings, shortcuts)?

### ISSUE THREAD

**Issue by kdraeder** [XQuartz/XQuartz#358]
I'm trying to identify available keys for use as shortcuts in the Applications menu.
I've looked extensively through the X11 Preferences menu and online at XQuartz.org, X.org, and dozens of other links, but haven't found a way.
I'm working on a Mac, which has a menu dealing with shortcuts, but XQuartz is not in the list of Apps whose shortcuts can be changed.  Maybe because it's in Utilities.
I could open each menu and manually extract the shortcuts, but that seems primitive and probably ineffective.
Opening this issue is my last resort before doing that.
Please point me to any relevant documentation, or reveal the magic words.
XQuartz 2.8.5
macOS 12.6 (the latest I'm allowed to have)

**Comment by jeremyhu** [comment]
Can you elaborate?  Probably best to ask for help on the mailing list rather than filing a bug report.
