### ISSUE TITLE
XQuartz 2.8.5 does not work with  Ventura 13.5.1 

### ISSUE THREAD

**Issue by winstonstp** [XQuartz/XQuartz#359]
It seems that the XQuartz team has not solved the problem. I experienced the smentioned problem that XQuartz bounces but does not open.  That impacts greatly my work as Matlab requires XQuartz (2.8.5) to work properly remotely from Linux machine to iMac (Ventura 13.5.1) display.
I am, therefore, hoping that the XQuartz team will find a solution pretty quickly. I would like for sure to known when and what to try in the meantime as all the posted semi-solutions do not work.

**Comment by dtpoirot** [comment]
For all of us who are continuing to have the "screen goes black" issue... I get the same trying to run ZAP on a Ubuntu VM.

I ran defaults write org.xquartz.X11 enable_render_extension 0 from the macOS shell. The command executed.
I then installed XQuartz 2.8.5 again and this time my apps look correct.

I was just about to try the beta XQuartz releases. Now I am afraid to touch anything! :-/

**Comment by jeremyhu** [comment]
Bouncing icon usually means the X11 client side quickly terminated, so the server was torn down.  This is almost always an issue with the user's shell init files.  Try moving aside ~/.bashrc, ~/.bash_profile, ~/.zshrc, ~/.profile, ~/.xinitrc, etc and trying with a clean environment.  Then work to figure out what was the issue.
