### ISSUE TITLE
Minor typo in the post install script 

### ISSUE THREAD

**Issue by bgvoisin** [XQuartz/XQuartz#36]
First, thanks a lot for doing this. Your work is very welcome, there are a number of us out there needing a working X11 on the Mac.

Installing 2.8.0 alpha 5 over an existing 2.7.11, I noticed a minor typo in postinstall, which contains

if [[ -f /Library/LaunchAgents/org.macosforge.xquartz.startx.plist ]] ; then
    rm /Library/LaunchDaemons/org.macosforge.xquartz.privileged_startx.plist
fi

I assume the second line was meant to erase org.macosforge.xquartz.startx.plist, superseded by the new  org.xquartz.startx.plist, not org.macosforge.xquartz.privileged_startx.plist already erased a couple of lines earlier. (Of course, that's harmless.)

The only issue I faced may not be specific to version 2.8.0. When XQuartz was launched by a GUI app (for example x2goclient), all was fine, but when attempting to launch it from Terminal, for example by running xdvi (from TeX), all I got was

Error: Can't open display: :0

This was caused by a previous MacPorts install, specifically ~/.zprofile which contained

# MacPorts Installer addition on 2021-01-08_at_20:47:27: adding an appropriate DISPLAY variable for use with MacPorts.
export DISPLAY=:0
# Finished adapting your DISPLAY environment variable for use with MacPorts.

Commenting out that part, all works fine. (All the above on a M1 MacBook Pro 13".)

**Comment by jeremyhu** [comment]
Doh, I noticed this issue just after uploading beta1. ><

I'll get this fixed for the next release and call this out in the email.

**Comment by jeremyhu** [comment]
The "MacPorts" thing there is actually a MacPorts installer bug.  They had issue with the "11.0" version number and added that.  Please just delete it.
