### ISSUE TITLE
XQuartz 2.8.5 seems to lose connection through ssh -X

### ISSUE THREAD

**Issue by reinauer** [XQuartz/XQuartz#369]
I am ssh -X'ing from my MacBook Air M2, 2022 into my Ubuntu Linux workstation and am running a few X clients over there.
On the Mac side I am running XQuartz 2.8.5. This works great for the first couple of invocations of my X clients. But after a while, newly started clients on the ssh connection can't talk to the X server anymore. The ssh connection seems healthy though.

In that case I will get an error message like:

``` 
$ git gui
application-specific initialization failed: couldn't connect to display "localhost:10.0"
Error in startup script: invalid command name "tk_messageBox"
    while executing
"tk_messageBox  -icon error  -type ok  -title "git-gui: fatal error"  -message $err"
    invoked from within
"if {[catch {package require Tcl 8.5} err]
 || [catch {package require Tk  8.5} err]
} {
	catch {wm withdraw .}
	tk_messageBox \
		-icon error \
		-typ..."
    (file "/usr/lib/git-core/git-gui" line 33)
$ 
```

**Comment by raoultrines** [comment]
What value do you use for the ssh configuration variable ForwardX11Timeout ? If you don't set this variable, then X11 connections forwarded over ssh drop out after 20 minutes. See `man ssh_config` for details.
