### ISSUE TITLE
XQuarrtz failes to start on Sonoma (at times)

### ISSUE THREAD

**Issue by oxoocoffee** [XQuartz/XQuartz#371]
I installed XQuartz unsign homebrew 
```bash
$ ~ brew info xquartz
==> xquartz: 2.8.5 (auto_updates)
https://www.xquartz.org/
/opt/homebrew/Caskroom/xquartz/2.8.5 (102.5MB)
```

Since I am using it once in a while, I noticed that when I try to start XQuartz, from Finder or Spotlight, I see XQuartz ison pop in Dock and go away with out any messages. If I try to start it from Terminal, I dod not see any errors or warnings.

Each this happens, the only remedy I have found is 

```bash
brew reinstall xquartz
```

And this works right away after reinstalling. Are there any logs, or anything that can be suggested to do/run when this happens again to attach it here?

I only add that ```brew doctor``` before reinstalling does not report any issues except that my file system is case sensitive, which is fine since I always reinstall new Mac to case sensitive systems for c/c++ development.

```bash
$ ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

I also just found a OLD log file from such a run

$  cat ~/Library/Logs/X11/org.xquartz.log.old

``` bash
X11.app: main(): argc=1
	argv[0] = /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
Waiting for startup parameters via Mach IPC.
X11.app: No launchd socket handed off, unsetting DISPLAY
X11.app: do_start_x11_server(): argc=7
	argv[0] = /opt/X11/bin/Xquartz
	argv[1] = :0
	argv[2] = -nolisten
	argv[3] = tcp
	argv[4] = -iglx
	argv[5] = -auth
	argv[6] = /Users/oxoocoffee/.serverauth.16433
[418255.429] Xquartz starting:
[418255.429] X.Org X Server 21.1.6
[418255.429] _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[418255.429] _XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
[418255.429] _XSERVTransMakeAllCOTSServerListeners: failed to create listener for local
[418255.429] (EE) 
Fatal server error:
[418255.429] (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
[418255.429] (EE) Server terminated with error (1). Closing log file.
```

After reinstalling and starting CURRENT (no system reboot)

$  cat ~/Library/Logs/X11/org.xquartz.log

```bash
X11.app: main(): argc=1
	argv[0] = /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
Waiting for startup parameters via Mach IPC.
X11.app: No launchd socket handed off, unsetting DISPLAY
X11.app: do_start_x11_server(): argc=7
	argv[0] = /opt/X11/bin/Xquartz
	argv[1] = :0
	argv[2] = -nolisten
	argv[3] = tcp
	argv[4] = -iglx
	argv[5] = -auth
	argv[6] = /Users/oxoocoffee/.serverauth.19152
[420734.470] Xquartz starting:
[420734.470] X.Org X Server 21.1.6
[420734.472] x: 2560, y: 0, w: 2560, h: 1416
[420734.472] x: 0, y: 0, w: 2560, h: 1416
[420734.473] (II) Initializing extension Generic Event Extension
[420734.473] (II) Initializing extension SHAPE
[420734.473] (II) Initializing extension MIT-SHM
[420734.474] (II) Initializing extension XInputExtension
[420734.474] (II) Initializing extension BIG-REQUESTS
[420734.474] (II) Initializing extension SYNC
[420734.474] (II) Initializing extension XKEYBOARD
[420734.474] (II) Initializing extension XC-MISC
[420734.474] (II) Initializing extension SECURITY
[420734.474] (II) Initializing extension XFIXES
[420734.474] (II) Initializing extension RENDER
[420734.474] (II) Initializing extension RANDR
[420734.474] (II) Initializing extension DAMAGE
[420734.474] (II) Initializing extension MIT-SCREEN-SAVER
[420734.475] (II) Initializing extension DOUBLE-BUFFER
[420734.475] (II) Initializing extension Present
[420734.475] (II) Initializing extension X-Resource
[420734.475] (II) Initializing extension XVideo
[420734.475] (II) Initializing extension XVideo-MotionCompensation
[420734.475] (II) Initializing extension GLX
[420734.487] (II) GLX: Initialized Core OpenGL GL provider for screen 0
[420734.690] [mi] mieq: warning: overriding existing handler 0x0 with 0x10273e07c for event 28
[420734.690] X11.app: DarwinProcessFDAdditionQueue_thread: Sleeping to allow xinitrc to catchup.
[420734.701] (EE) Error loading keymap /tmp/server-0.xkm
[420734.702] (EE) XKB: Failed to load keymap. Loading default keymap instead.
[420736.765] noPseudoramiXExtension=0, pseudoramiXNumScreens=2
[420935.907] (II) Server terminated successfully (0). Closing log file.
```

I only do every week is run my brew_check scripts which does

```bash
brew update
brew upgrade
```

Followed by checking each installed cask app in the array (which is also used when setting up a new machine)

```bash
    # for every cask_app in script array
    brew upgrade --cask "${cask_app}"
```

I am pretty sure there were no quartz updates that were issued. So, I  would like to know what the issue is so I do not have to "reinstall to fix it"

BTW: before reinstalling, I did check ```otool -L``` for X11 and X11.bin in ```/Applications/Utilities/XQuartz.app/Contents/MacOS``` and I did not miss any libraries.

**Comment by xbb** [comment]
If you launch it from terminal `/Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin` does it always work?

It never started for me when launched from the `.sh` file (or the .app). This was because something in my `.zprofile` (using ZSH) was breaking it, specifically I was setting arguments with `set -- …`.

**Comment by jeremyhu** [comment]
This would be consistent with our LaunchDaemon not getting loaded.  Did you disable it in Login Items in System Preferencs?   What do you see when you run `launchctl print system | grep startx`?

**Comment by topher800** [comment]
I am having similar issues.  I have a fresh install of Sonoma (nothing was restored from TimeMachine).  This is on an x86 Mac.  I also have Homebrew installed, and /usr/local/bin/bash is my default shell.

Double clicking the Icon in Apps/Utilities consistently fails to start, doesn't even leave a Log file.  Running from the terminal as xbb above suggests, consistently works.

Jeremy requests:
535% launchctl print system | grep startx
		       0      0 	org.xquartz.privileged_startx
		 0xd934b    M   D   org.xquartz.privileged_startx
		"org.xquartz.privileged_startx" => enabled

**Comment by topher800** [comment]
I have found my issue and a way to fix it.  Don't change default shell in System Settings->User&Groups, but rather just in the Terminal settings.  The latter being all I required.

**Comment by BethLong06** [comment]
I'm having a similar problem on Sonoma 14.2.1: XQuartz always fails to start from launchpad/finder/spotlight. From the terminal it does open but regardless I can't open an X forwarding session from ssh -XY, I get 
```
connect /private/tmp/com.apple.launchd.hcrfaBOVhq/org.xquartz:0: Connection refused
Display localhost:13.0 unavailable
```
This didn't happen until I updated my macOS to Sonoma

**Comment by topher800** [comment]
Have you changed your default shell (from zsh or whatever)?  If so, did you
do it in the Terminal->Settings or via /etc/password?  The latter causes
XQuartz to fail.

**Comment by ndevenish** [comment]
I had this same issue on Ventura.

I had also disabled the login item, restoring this fixed.

**Comment by subha-dash** [comment]
use this below script to open xquartz . it is working

```
#!/bin/bash

echo root-passwd | sudo -S rm -rf /tmp/.X11-unix 
mkdir -m 1777 /tmp/.X11-unix 
echo root-passwd | sudo -S chown root:wheel /tmp/.X11-unix
open /Applications/Utilities/XQuartz.app
```

**Comment by Elfara77** [comment]
> > use this below script to open xquartz . it is working
> 
> I tried that script (with trepidation because putting root-pw in a script is unwise) but it did not work for me. I am running Sonoma 14.4. X11 worked fine for me in previous version of Sonoma. Something broke with 14.4!
> 
> The script yields the same problem as trying to launch with the icon in the toolbar. The X icon bounces up and down a couple times, like it is trying to start, but then the block dot disappears and it just keeps repeating that over and over.
> 
> I am not using brew. I use macports for many things, but the X11 app I got from the official website. Should I open a new issue because this is not brew related? This is still unresolved!
> 
> Edit: Problem was my bad `.xinitrc` file. Resolved by removing it.

Hi, where I can find that '.xinitrc' file ? because I don't see it in my Home dir :-( (macOS Sonoma 14.4.1)

**Comment by JeffFessler** [comment]
If you have your own `.xinitrc` file (and probably you should not) then it would be in your home directory.    To see files like that, use `/bin/ls -aF` because the `-a` option shows all files.  Normally `ls` does not show the `.xyz` files.
