### ISSUE TITLE
Ask for confirmation before closing Window (feature request)

### ISSUE THREAD

**Issue by hmakmur** [XQuartz/XQuartz#373]
XQuartz does not ask for confirmation if I really want to close the window when the red (X) (top/left)  icon is click.
I often accidentally click the (X) (top/left) window on XQuartz. It immediately closes the window and everything as child window.
I dont see this option but could this feature be added?

thanks.
-h

**Comment by jeremyhu** [comment]
That needs to be handled by the X11 client.
