### ISSUE TITLE
segfault on intel macbook, works on apple silicon

### ISSUE THREAD

**Issue by dvdsnchzIT** [XQuartz/XQuartz#375]
Hello,

I have a fresh hpc cluster with apps.

One of them, molden (gmolden for the windowed version) crash when I try to launch it from my old 2015 intel macbook, macOS monterey 12.7.2, on each XQuartz versions : 2.8.6_beta2, 2.8.5, 2.7.10.
On newer intel macbook pro/air with macOS 13.2 / XQuartz  2.8.5, 2.7.10, same symptoms.

On my 2020 apple silicon macbook with macOS Sonoma 14.2 and XQuartz 2.8.5, no problem.

This is the output on my intel macbook : 

```txt
$ ssh -Y mycluster
$ gmolden
no context
X error code BadValue (integer parameter out of range for operation)
X error code BadMatch (invalid parameter attributes)

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f513501d640 in ???
#1  0x7f513501c873 in ???
#2  0x7f5134cc1dbf in ???
#3  0x7f5134df5828 in ???
#4  0x7f5134d1970e in ???
#5  0x5ca7be in ???
#6  0x417694 in ???
#7  0x425364 in ???
#8  0x7f5134cac24c in ???
#9  0x407349 in _start
	at ../sysdeps/x86_64/start.S:120
#10  0xffffffffffffffff in ???
Segmentation fault (core dumped)
```

If you need information, I'm available.

Regards,

D.S.

**Comment by jeremyhu** [comment]
It looks like this is the client process crashing, on another system.  None of our code is in that process.  It could be that data being sent by the server is triggering the crash, but that is still a bug in the client as it needs to be robust against possibly bad data.
