### ISSUE TITLE
XQuartz and Apple M1

### ISSUE THREAD

**Issue by m77it** [XQuartz/XQuartz#379]
ar all,
I installed XQuartz, the latest version, on a laptop M1, Sonoma 14.2, but the software that needs XQuartz does not start (Poky and Pymol). Furthermore, the Quartz blocks the system, and I need to restart the laptop to stop it. I'm not an experienced user; how can I solve this problem?
Thanks
Marco

**Comment by jowodo** [comment]
what errors do you get?

**Comment by m77it** [comment]
When I start a program that uses XQuartz the program does not start and the XQuartz icon bounces continuously. Any other program stops during the bouncing and you are unable to stop XQuartz so I have to turn off the laptop to restore the system

**Comment by jowodo** [comment]
try to start Poky/Pymol from the command line and post the errors you get in the terminal here. This will help to understand the error better.

**Comment by jeremyhu** [comment]
This type of issue is usually a bug in your shell init scripts.  Move aside ~/.profile, ~/.xinitrc et al and see it if it reproduces with a more default config.
