### ISSUE TITLE
2.8.0 beta error with R rgl

### ISSUE THREAD

**Issue by tonikazic** [XQuartz/XQuartz#38]
Thanks for XQuartz!  It's been a reliable friend for many years.

I downloaded the new beta as a dmg and found a bug:  when I try to plot with rgl, I get the following errors (which do not appear with 2.7.11, to which I rolled back):

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGL.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rgl/libs/rgl.so
  Reason: Incompatible library version: rgl.so requires version 4.0.0 or later, but libGL.1.dylib provides version 1.0.0
Error: package or namespace load failed for ‘rgl’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error: 	Loading rgl's DLL failed. 
	On MacOS, rgl depends on XQuartz, which you can download from xquartz.org.

I'm running:

        MacOS Catalina 10.15.7
        2.4 GHz 8 core i9

        R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
        Platform: x86_64-apple-darwin17.0 (64-bit)

thanks and cheers,

Toni

**Comment by jeremyhu** [comment]
Ah yes.  I filed that with mesa and intended to fix it before using the newer builds of mesa, but I forgot about it when I was working through the last of the issues here.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/4113

**Comment by rb643** [comment]
Performed the same update to the beta version today but have the same issue..  (running the same setup as Toni). Should I update/upgrade in a diffent way than from within XQuartz?

**Comment by rb643** [comment]
ps: I already tried updating/reinstalling mesa with homebrew, but that didn't seem to make much difference

**Comment by tonikazic** [comment]
oh, I hate it when I forget junk like that ;-) --- thanks!
