### ISSUE TITLE
xquartz not stable when launch java application

### ISSUE THREAD

**Issue by quantrpeter** [XQuartz/XQuartz#382]
hi all
   I am use xquartz to run netbeans, it is good. Then I use netbeans to launch other java app, usually after 15 mins, it will fail to launch any java app. I think it is crashed or bug, i have to restart the ssh. thanks

<img width="1670" alt="Screenshot 2024-01-21 at 3 59 21 PM" src="https://github.com/XQuartz/XQuartz/assets/50471577/d811420f-d2e7-4fef-ae37-e29c0f2f2198">

**Comment by jeremyhu** [comment]
This is probably the ssh X11 forwarding timeout.  You need to adjust ssh settings.
