### ISSUE TITLE
Ominous error message on simple X programs: malloc: nano zone abandoned due to inability to reserve vm space.

### ISSUE THREAD

**Issue by dpeterc** [XQuartz/XQuartz#385]
On MacOS Ventura and XQuartz 2.8.5, if you run even a simple X11 program like
`xmessage test`
you get a scary looking error message
`malloc: nano zone abandoned due to inability to reserve vm space.`
This might confuse users. According to this Stackoverflow post, it is harmless
https://stackoverflow.com/questions/64126942/malloc-nano-zone-abandoned-due-to-inability-to-preallocate-reserved-vm-space
and you can solve it by setting such environment variable
`export MallocNanoZone='0'`
but it would be nicer, if it was not necessary in the first place.

**Comment by jeremyhu** [comment]
Please report the issue at bugreport.apple.com

**Comment by dpeterc** [comment]
Thanks, reported as FB13598502
