### ISSUE TITLE
Middle click paste adds 00~ and 01~ (pre and post pasted string)

### ISSUE THREAD

**Issue by BenSG24** [XQuartz/XQuartz#386]
Following up on https://github.com/XQuartz/XQuartz/issues/123

@jeremyhu : Problem replicated

<img width="299" alt="image" src="https://github.com/XQuartz/XQuartz/assets/158307987/91822ee0-d4a8-414d-a188-879403bfe04a">

Version. XQuartz 2.8.5 (xorg-server 21.1.6)
OS: MacOS 14.2.1 (23C71)

Solving this would be fantastic ! 

I suspect it's trying to paste rich text and XQuartz does't understand the formatting "tags"

**Comment by jeremyhu** [comment]
It is the client's responsibility to interpret the paste buffer.  What terminal is that?  Please report to the maintainer of that terminal

**Comment by BenSG24** [comment]
xterm running bash

**Comment by jeremyhu** [comment]
Then I suggest reporting it to Thomas Dickey.  He's very responsive.
