### ISSUE TITLE
XQuartz 2.8.5 problem with utf-8 resources names

### ISSUE THREAD

**Issue by dazuelos** [XQuartz/XQuartz#387]
I just upgraded from XQuartz version 2.8.1 to version 2.8.5.
I discovered a new problem with xterm resources names.

I am using resources having utf-8 names ( i.e. utf-8 outside of iso8859-1 ).    
Here is an example from my ~/.Xresources:
                                                                                                                    
    |       pétrole*Background:     #377                                            
    |       pétrole*Foreground:     #ff7 

All these resources names were working with version 2.8.1.                      
They aren't with 2.8.5, the class ressources are used instead:                  
                                                                                
    |       XTerm*background:       #654
    |       XTerm*foreground:       yellow                                          
                                                                                
If I enter the command line:                                                    
                                                                                
        xterm -name pétrole                                                     
                                                                                
then Background and Foreground colors are correctly set.                        
If I fire the same command from the XQuartz menu entry which                    
should fork the exact same command, then the specific colors                    
are not used.   

Since there was 3 evident suspects:         
                                   
        xterm
        quartz-wm
        XQuartz.app

I tried within the global tree of binaries and libraries from 2.8.1             
their versions from version 2.8.5.                                              
Results:

        xterm           I had to also copy libfreetype*.dylib                   
                        OK                                                      
        quartz-wm       OK                                                      
        XQuartz.app     KO                                                      
                                                                                
I continue my own investigation.

**Comment by jeremyhu** [comment]
This doesn't seem XQuartz specific.  Can you maybe ask on the xorg mailing list?

**Comment by dazuelos** [comment]
Further investigation:

I installed XQuartz version 2.8.2.

The problem is the same.
If I bring back only the application `XQuartz.app` from 2.8.1,
then the problem isn't there.

Then my actual conclusion, is that the problem is within the application
`XQuartz.app` version 2.8.2 **only** and **only** due to modifications from version 2.8.1 to 2.8.2.
