### ISSUE TITLE
Xquartz went extremely slow after update to Sonoma 14.4

### ISSUE THREAD

**Issue by c-hoeger** [XQuartz/XQuartz#389]
### How to reproduce

Use ssh without compression to connect to a system with some X11 applications. Problem arose with eclipse, version does not matter. Also tried different other applications like xemacs or kate. After I updated to Sonoma 14.4, all those apps became extremely slow. Can watch the content being painted. Currently running XQuartz 2.8.6_beta2, but same problem with the latest release 2.8.5.

Also reported the problem to Apple. ID: FB13683994

**Comment by raoultrines** [comment]
Can confirm this with XQuartz 2.7.11 and `ssh -X -C` (with compression). However, if I run a local X11 application on my Mac, it is not slow. This could be an ssh bug rather than an XQuartz bug. The file /usr/bin/ssh has a new date stamp, so it was probably upgraded together with MacOS Sonoma.

**Comment by c-hoeger** [comment]
Compression slows down ssh connections, don't use it. What if you try without compression? When I enable compression, it gets even worse.

I don't think that it is the fault of ssh, but I am not sure, though.

**Comment by c-hoeger** [comment]
Well, whatever the cause is, it was introduced with the 14.4 update.

**Comment by gson1703** [comment]
I tracked down the cause: https://bugzilla.mindrot.org/show_bug.cgi?id=3655

**Comment by c-hoeger** [comment]
@gson1703 nice, thanks. Setting `ObscureKeystrokeTiming=no` solved the issue for me.

**Comment by henrikbrixandersen** [comment]
> @gson1703 nice, thanks. Setting `ObscureKeystrokeTiming=no` solved the issue for me.

Thanks, same here.

**Comment by raoultrines** [comment]
@gson1703 Yes, works for me too, thanks.

@jeremyhu I included this setting in my ~/.ssh/config file. Do you think it is worthwhile doing that for all users via the XQuartz configuration?

**Comment by jeremyhu** [comment]
Thanks.  XQuartz installer could make that change to the user's ssh config (like we do for xhost), but I'd rather see that fixed in the OS.

**Comment by c-hoeger** [comment]
I'd agree. The default ssh configuration should not be like that.

**Comment by chiwwong** [comment]
> @gson1703 Yes, works for me too, thanks.
> 
> @jeremyhu I included this setting in my ~/.ssh/config file. Do you think it is worthwhile doing that for all users via the XQuartz configuration?

Would you mind explicitly telling me how to include the `ObscureKeystrokeTiming=no` setting? I got an error message after adding the line:

> line 2: Bad configuration option: obscurekeystroketiming
> .ssh/config: terminating, 1 bad configuration options

**Comment by c-hoeger** [comment]
You obviously don't have an ssh client with that option installed and thus you cannot turn it off.
That also means you don't have the problem.

**Comment by chiwwong** [comment]
@c-hoeger Sorry, I am new. May I know whether using ssh command in the terminal means that I have had ssh client installed? Or do you mean there is a dedicated client to be installed in addition to the natively shipped terminal? (I use iTerm).

**Comment by xczhang123** [comment]
> [@c-hoeger](https://github.com/c-hoeger) Sorry, I am new. May I know whether using ssh command in the terminal means that I have had ssh client installed? Or do you mean there is a dedicated client to be installed in addition to the natively shipped terminal? (I use iTerm).

As @c-hoeger mentioned, it's most likely due to the OpenSSH version you’re using. I could also verify that `ObscureKeystrokeTiming=no` works on OpenSSH_9.7p1 but not on OpenSSH_8.2p1.

**Comment by jeremyhu** [comment]
The issue was addressed in OpenSSH 10.0 via https://bugzilla.mindrot.org/show_bug.cgi?id=3655

The latest versions of macOS have this version.  If you're on older versions of macOS and need it, I'd suggest using MacPorts or Homebrew.
