### ISSUE TITLE
Xquartz 2.8.5 stopped starting, Ventura 13.6.3

### ISSUE THREAD

**Issue by arifsazal** [XQuartz/XQuartz#390]
I work with **Macbook Pro M2 Pro, Ventura 13.6.3**
-------------------------------------------------
I complied SAC from the source file and everything worked fine. And I **had no problem** with Xquartz. Plotting was alright. 
Then I **compiled gfortran** in my machine and there was no problem too. 
After that, I **tried to install Seismic Unix but it didn't work properly**. Then, yesterday, **I compiled Seismic Unix according to the instructions** given in the [wiki link](https://wiki.seismic-unix.org/sudoc:su_installation). The **only issue** was that I didn't find the makefile for Ventura in the /cwp/src/config folder. So, I used the version available for Monterey and compiled it according to the instructions. Every command works perfectly except it cannot plot anything with the help of Xquartz anymore. And, also the same problem happening to the SAC plotting now.

**Error message for Seismic Unix Plotting:** /usr/local/cwp/bin/ximage: Cannot connect to display /private/tmp/com.apple.launchd.Tlf0s9nYRi/org.xquartz:0!
**Error message for SAC Plotting:** ERROR  203: Can't create X window. Check DISPLAY environmental.

I have reinstalled the Xquartz many times since then and restarted my computer but the problem is not fixed.
Can anyone help please? Specially  @junegunn @jeremyhu 

I use cshell and this is my **.cshrc file below**: 
          # SU PATH Set #
          setenv CWPROOT /usr/local/cwp
          set path=( $path $CWPROOT/bin . )
          
          # SAC PATH Set #
          setenv SACHOME /usr/local/sac
          alias sac '"${SACHOME}/bin/sac" "${SACHOME}/macros/init.m"'
          source ${SACHOME}/bin/sacinit.csh
          
          # shortening csh prompt 
          set prompt = "[%c3] %# "
          
          # travelt PATH Set #
          setenv PATH ${PATH}://Users/smarifulislam/bin 
          
          # PATH for macport#
          setenv PATH ${PATH}://opt/local/bin
          
          # PATH for seg2segy #
          setenv PATH ${PATH}://Users/smarifulislam/Research/matlab/seg2segy

**Comment by arifsazal** [comment]
These are the environments: 
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/9p/89jcmr39025c2gq9hzdlw13m0000gn/T/
XPC_FLAGS=0x0
LaunchInstanceID=1742848E-3024-45DB-A553-A2D004A0AD7A
TERM=xterm-256color
LANG=en_US.UTF-8
DISPLAY=/private/tmp/com.apple.launchd.4A6s2rAsOS/org.xquartz:0
SECURITYSESSIONID=186b1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.8trB2scMjs/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=447
TERM_SESSION_ID=2F384C77-0D7E-4C1B-B969-5CA0E8BAFBEA
SHELL=/bin/zsh
HOME=/Users/smarifulislam
LOGNAME=smarifulislam
USER=smarifulislam
PATH=/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:opt/local/bin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/cwp/bin:.:/usr/local/sac/bin://Users/smarifulislam/bin://opt/local/bin://Users/smarifulislam/Research/matlab/seg2segy
HOSTTYPE=unknown
VENDOR=apple
OSTYPE=darwin
MACHTYPE=unknown
SHLVL=1
PWD=/Users/smarifulislam
GROUP=staff
HOST=ss-macbook-pro.uom.memphis.edu
CWPROOT=/usr/local/cwp
SACHOME=/usr/local/sac
SACAUX=/usr/local/sac/aux
SAC_DISPLAY_COPYRIGHT=1
SAC_USE_DATABASE=1
SAC_PPK_LARGE_CROSSHAIRS=0
SAC_TRAVELTIME_PHASES=all
CONDA_EXE=/Users/smarifulislam/anaconda3/bin/conda
_CONDA_ROOT=/Users/smarifulislam/anaconda3
_CONDA_EXE=/Users/smarifulislam/anaconda3/bin/conda
CONDA_PYTHON_EXE=/Users/smarifulislam/anaconda3/bin/python
CONDA_SHLVL=0

**Comment by arifsazal** [comment]
This is the report from ~/Library/Logs/X11/org.xquartz.log 
------------------------------------------------------------
X11.app: main(): argc=1
	argv[0] = /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
Waiting for startup parameters via Mach IPC.
X11.app: No launchd socket handed off, unsetting DISPLAY
X11.app: do_start_x11_server(): argc=7
	argv[0] = /opt/X11/bin/Xquartz
	argv[1] = :0
	argv[2] = -nolisten
	argv[3] = tcp
	argv[4] = -iglx
	argv[5] = -auth
	argv[6] = /Users/smarifulislam/.serverauth.4200
[ 45515.574] Xquartz starting:
[ 45515.574] X.Org X Server 21.1.6
[ 45515.574] _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[ 45515.574] _XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
[ 45515.575] _XSERVTransMakeAllCOTSServerListeners: failed to create listener for local
[ 45515.575] (EE) 
Fatal server error:
[ 45515.575] (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
[ 45515.575] (EE) Server terminated with error (1). Closing log file.

**Comment by jeremyhu** [comment]
You have permissions issues with /tmp/.X11-unix (or maybe even /tmp/.X11-unix).  Please check the ownership and persmisisons on that directory.  The system should create it for you:

```
$ ls -adl /tmp/.X11-unix
drwxrwxrwt 3 root wheel 96 Mar 19 15:27 /tmp/.X11-unix
```

**Comment by arifsazal** [comment]
Thank you, Jeremy! That's very helpful.
