### ISSUE TITLE
OSX 14.4.1: Ctrl-enter no longer works

### ISSUE THREAD

**Issue by sirainen** [XQuartz/XQuartz#394]
Xquartz can no longer generate an event when pressing ctrl-enter. It simply makes a beeping sound. I'm pretty sure this happened after upgrading OSX, since Xquartz is still v2.8.5 which worked before.

Steps to reproduce:
 * start xev
 * press ctrl-enter
 * Notice how no event is written by xev
 * Notice how shift/option/command-enter does generate an event

Ctrl-enter works elsewhere though, for example TextEdit.

**Comment by jeremyhu** [comment]
rdar://126288179

**Comment by jeremyhu** [comment]
Sorry, I should have circled back sooner.  Please verify that this is addressed in the latest beta versions of macOS 14.5.

**Comment by sirainen** [comment]
Works again, thank you!

**Comment by raoultrines** [comment]
Indeed: works again after installing macOS 14.5.
