### ISSUE TITLE
XQuartz 2.8.5 Not Opening

### ISSUE THREAD

**Issue by roosmajustin** [XQuartz/XQuartz#395]
I am using a 2015 MacBook pro with macOS Big Sur Version 11.4.

I am trying to open XQuartz 2.8.5.

When I open XQuartz it bounces up and down on the apps dock, then closes, then bounces, then closes and repeats this ad infinitum.

I have tried giving XQuarts full permissions, I have tried reinstalling it multiple times, and I have tried installing other versions.

I would appreciate any advice anyone could give me.

Cheers

**Comment by roosmajustin** [comment]
I already gave the app full disc access so I'm not sure if this could be the issue?

Could you provide more detail about how you manually investigated your issue? I am new to this.

Thank you for your response.

**Comment by raoultrines** [comment]
Could this be related to #295 ?

**Comment by jeremyhu** [comment]
This is usually cUse by a problem in your shell or X11 init scripts.  Please move those aside and try again then bisect through them to discover the cause.
