### ISSUE TITLE
XQuzrtz is not working properly

### ISSUE THREAD

**Issue by koalabrain** [XQuartz/XQuartz#396]
Local system: Mac Sonoma 14.4.1
Remote server: ubuntu 20.04.5 LTS
XQuartz: latest version

The situation is described as follows
1. During a recent remote development using pycharm, with the XQuartz app open, run the following code
        img_path = 'mypath/xxx.jpg'
        image = Image.open(img_path)
        image.show()

This will give you the following error:
        / home/ubuntu/anaconda3 / envs/pytorch -t/bin/python3.9 / home/ubuntu/project/DeepLearningZoo/test/test. The py
        Unable to init server: Unable to init server
        (eog:13751): Gtk-WARNING **: 14:04:33.991: cannot open display:
        Process has terminated, exit code 0

2. And something very strange happened. In xterm, use the command ssh-X MyUserName@MyIP_add to connect to the ubuntu server. First run the above code in xterm, and it will display the picture window normally. Under the premise of not closing the pop-up window, and then run the program in pycharm, you can normally pop-up image window. If you close the window that pops up when you run the program in xterm, pycharm will get the same error message. 

3. In addition, if you run the above code on a Mac console and connect to the ubuntu server with ssh-X MyUserName@MyIP_add, the image window will pop up normally. Similarly, under the premise of not closing the pop-up image window, running the code in pycharm can normally pop-up image window, otherwise the above error will be reported.

Q: Why does this happen and how can I fix it?

**Comment by jeremyhu** [comment]
It sounds like you are having issues with X11 over ssh.  Perhaps your X11 tunnel over ssh was past its timeout?

Can you explain more?
