### ISSUE TITLE
XQuartz 2.8.5 doesn’t open terminal directly on macOS Sonoma 14.5

### ISSUE THREAD

**Issue by Rishi-Sudhakar** [XQuartz/XQuartz#398]
Details:

Device: MacBook Pro (13", 2020, M1)
Operating System: macOS Sonoma 14.5
XQuartz Version: 2.8.5

Issue:
Terminal doesn’t seem to open directly while launching the app. Workarounds are to directly use terminal>cli or open the app(It's blank), then check the menu bar>Applications>Terminal. 

Steps Taken to Resolve:

- Granted XQuartz full permissions in the System Preferences.
- Reinstalled XQuartz multiple times.
- Verified that all relevant permissions and security settings are correctly configured. ( It has sudo access, even tried safemode booting)

**Comment by AwlsomeAlex** [comment]
Same deal.

```
-> % defaults read org.macosforge.xquartz.X11 app_to_run
2024-06-12 00:29:29.168 defaults[12830:751895] 
The domain/default pair of (org.macosforge.xquartz.X11, app_to_run) does not exist
```

**Comment by raoultrines** [comment]
Can you quit XQuartz, then try to correct that setting with this command:

`defaults write org.macosforge.xquartz.X11 app_to_run '/opt/X11/bin/xterm'`

Then start XQuartz again.

**Comment by Rishi-Sudhakar** [comment]
> Can you quit XQuartz, then try to correct that setting with this command:
> 
> `defaults write org.macosforge.xquartz.X11 app_to_run '/opt/X11/bin/xterm'`
> 
> Then start XQuartz again.

Finally the shell opens, (Also, can confirm working well in MacOS 15)
