### ISSUE TITLE
XQuartz launching and closing on Mac (for use with MGLTools)

### ISSUE THREAD

**Issue by terrilvallikalam** [XQuartz/XQuartz#399]
Hi! 
I am a Mac user (macOS Sonoma 14.5) and I want to use MGLTools as part of my research. The softwares in this suite require the use of XQuartz. When I initially did this install in April, I was able to successfully launch the softwares in the suite!! Unfortunately, they are unable to launch anymore and XQuartz keeps opening and closing; I am unable to quit XQuartz so I've had to shut down my computer to close the application. 

I thought it may be an issue with XQuartz so I deleted it and used the [MacPorts install option](https://www.xquartz.org/releases/index.html) and I was able to download X11, but when I tried to run the code to launch the MGLTools software, it said that it was unable to find an application called XQuartz. I tried the Homebrew option to install XQuartz and ran the code to launch MGLTools and now XQuartz keeps opening and closing.

I've already checked out #272

Any help would be appreciated! Thanks in advance!

**Comment by terrilvallikalam** [comment]
I gave XQuartz full permission so I don't think it has anything to do with #395 

As per #295, when I type in xterm it opens XQuartz and closes it and it just keeps repeatedly opening and closing and bouncing on my dock. 
When I type printenv DISPLAY, I get /private/tmp/com.apple.launchd.ihXYhfV6cr/org.xquartz:0
When I type ls /private/tmp/com.apple.launchd.* it returns:
/private/tmp/com.apple.launchd.Ti0NpN8iQb:
Listeners

/private/tmp/com.apple.launchd.TsLGuVcD9P:
org.macports:0

/private/tmp/com.apple.launchd.ihXYhfV6cr:
org.xquartz:0

launchctl getenv DISPLAY and echo $DISPLAY both give me: /private/tmp/com.apple.launchd.ihXYhfV6cr/org.xquartz:0

Not sure what the issue is and XQuartz is already turned on as a login item. Based off of this and the other threads, it seems like it should be working, but it's not..

**Comment by jeremyhu** [comment]
This is usually because of problems with your shell or X11 init scripts.  Move them aside, confirm XQuartz launches, then bisect through them to determine the problem.
