### ISSUE TITLE
Focus being stolen from XQuartz windows

### ISSUE THREAD

**Issue by corwin** [XQuartz/XQuartz#4]
I'm running XQuartz version XQuartz 2.7.11 (xorg-server 1.18.4) on OS X 10.13.2.

I spend most of time in emacs windows which are X forwarded over ssh connections to linux VMs also running on my mac. Frequently, the focus gets stolen from my emacs window and I end up typing at nothing for a moment before I realize I have to go find the mouse cursor and bring the focus back to my X window.

Having searched the web for previous issues, I came across and started running watchActivations.py.

Unfortunately, there does not to be a single culprit. Most often, the focus loss happens due an activation of Keychain Circle Notification (com.apple.security.Keychain-Circle-Notification), com.apple.WebKit.Plugin.32 (com.apple.WebKit.Plugin.32), or much less often, Google Chrome (com.google.Chrome).

Any suggestions most welcome (upgrading to Catalina will happen sometime early in the new year, but due to various constraints, can't happen before then). Knowing that that would fix my problem would be sufficient, but I fear it is not that simple since I've had this problem since before I upgraded to High Sierra.

**Comment by marcopeereboom** [comment]
This drives me insane too.

**Comment by mauran** [comment]
Been living with this for 2 years now..

**Comment by walls00000** [comment]
Thanks for reporting this.  I've been hitting this for a couple of years as well.

**Comment by jeremyhu** [comment]
This was fixed a few years back in xorg-server, but there hasn't been an XQuartz package release because I had kids and nobody stood up to drive releases when I asked for help... =/  I'm currently working on a new build script to maybe put out a beta, but I get maybe 5 hours a year to work on it... so here's hoping I can squeeze it in before I go back to work next week...
