### ISSUE TITLE
Gdk-error with Homebank

### ISSUE THREAD

**Issue by Tchecker67** [XQuartz/XQuartz#400]
Hi,

I use Xquartz for the first time, to run the app "Homebank".

First, I'm surprise that when I close a window, the entire program shut down... Is it possible to deal with this behaviour ?

Then, when it happens, the Xqiartz terminal show this error :

(homebank:36172): Gdk-ERROR **: 23:48:30.655: The program 'homebank' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadLength (poly request too large or internal Xlib length erro'.
  (Details: serial 1477 error_code 16 request_code 72 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
zsh: trace trap  homebank

What do this mean ?

Thank you

**Comment by dpeterc** [comment]
The message you got is quite clear to a programmer.
It is a bug in the program you are using, not in XQuartz.
It means that the application did not check the maximum supported size of data transmission of parameters in drawing operations.
It should be done by the macro XMaxRequestSize
https://linux.die.net/man/3/xmaxrequestsize
If you are not a programmer, you should report the bug the the authors of the program.

As for the window closing, if you close XQuartz, all the X11 based programs will also close. That is just the way it works. It is like a shutdown of graphics system for all X11 applications.
