### ISSUE TITLE
How to link with XQuartz?

### ISSUE THREAD

**Issue by P-Kaempf** [XQuartz/XQuartz#401]
Hi,
I just tried to compile some freeware written for Unix which tries to link to X11 header files. Of course, with only the executable of XQuartz on my system (MBP with M1 chip, MacOS 14.5), none of them can be found. How do I link to
X11/Xlib.h
X11/Xutil.h
X11/cursorfont.h?

**Comment by raoultrines** [comment]
Header files 'should' be in /opt/X11/include . You can tell your compiler that by adding the option `-I/opt/X11/include` to the command line. Similarly, libraries should be in /opt/X11/lib , add option `-L/opt/X11/lib` .

**Comment by P-Kaempf** [comment]
Thank you - I will give it a try. Great to see that even arcane topics get a quick response!
