### ISSUE TITLE
xquartz keep bounching in the menu bar

### ISSUE THREAD

**Issue by gmrandazzo** [XQuartz/XQuartz#403]
XQuartz version: 2.8.5
Installation manager: homebrew (brew install xquartz)
Device: Apple Macbook pro M2
OSX: 14.5

installed and uninstalled multiple time.
removed all files in /opt/X11 etc... removed also the sshd_config line.

```
launchctl getenv DISPLAY 
/private/tmp/com.apple.launchd.YtJdvP0Hk3/org.xquartz:0

echo $DISPLAY
/private/tmp/com.apple.launchd.YtJdvP0Hk3/org.xquartz:0
```

Disable all login items in background and left only XQuartz. 

Keep bounching and not opening anything. Moreover mac become inusable.

**Comment by jeremyhu** [comment]
This is usually because of problems with your shell or X11 init scripts.  Move them aside, confirm XQuartz launches, then bisect through them to determine the problem.

**Comment by jeremyhu** [comment]
This is usually because of problems with your shell or X11 init scripts.  Move them aside, confirm XQuartz launches, then bisect through them to determine the problem.

**Comment by gmrandazzo** [comment]
@jeremyhu, thanks! You were right!! Inside my home ~/.xinitrc, there was a suspicious line that was deleting .xinitrc itself from my home! I'm not sure how and why it was there, but now it works! The solution was eventually to look at the .xinitrc script inside my home! Thanks appreciated!
