### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by allydewey11** [XQuartz/XQuartz#405]
I need to open jupyter notebook from remote server so I must use terminal to open. Every time I type "jupyter notebook" command into terminal, it uses xquarts on my mac to open the notebook. Xquartz then takes 3 hours to open the notebook. How can I fix this?

**Comment by jeremyhu** [comment]
I don't know what jupyter is, but it sounds like this application is not optimized well for remote execution.  You're probably better off using a differnet solution, sorry.
