### ISSUE TITLE
ERROR: OpenGL version 1.5 or higher required

### ISSUE THREAD

**Issue by qingzew** [XQuartz/XQuartz#408]
I want to run a mujoco container on remote linux server, then on my mac m1, through xqaurtz to visualize

but has problem like this:
```
./mujoco/bin/simulate
MuJoCo version 3.2.2
Plugins registered by library 'libactuator.so':
    mujoco.pid
Plugins registered by library 'libsdf.so':
    mujoco.sdf.bolt
    mujoco.sdf.bowl
    mujoco.sdf.gear
    mujoco.sdf.nut
    mujoco.sdf.torus
    mujoco.sdf.sdflib
Plugins registered by library 'libelasticity.so':
    mujoco.elasticity.cable
    mujoco.elasticity.membrane
    mujoco.elasticity.shell
    mujoco.elasticity.solid
Plugins registered by library 'libsensor.so':
    mujoco.sensor.touch_grid
ERROR: OpenGL version 1.5 or higher required
```

I know it means low version opengl on my mac with m1 cpu, but how to solve it

**Comment by mc-cat-tty** [comment]
You can view your current OpenGL version with the `glxinfo` command. Run it in a terminal on your host system and you'll see some useful data in the first lines of the output.

As of now it looks like the GLX version deployed with XQuartz is V1.4 (macOS Sonoma @ M2 MacBook Air).

About _how to solve_... no idea, I'm looking for a solution too.

**Comment by jeremyhu** [comment]
#335
