### ISSUE TITLE
El capitan could not mount dmg.

### ISSUE THREAD

**Issue by hamada2029** [XQuartz/XQuartz#41]
El capitan (10.11.6) could not mount dmg since alpha 1 to beta 1.
(Because it is APFS?)
Please consider another type package, too.

**Comment by nbriggs** [comment]
Same system, same problem here.  If it's targeted at 10.9 or later then perhaps it should remain an HFS image?

**Comment by tehcog** [comment]
Same issue on Mavericks (10.9) here.
