### ISSUE TITLE
XQuartz not working on Sequoia

### ISSUE THREAD

**Issue by paolobeltrame3** [XQuartz/XQuartz#410]
I'm trying to run XQuartz on my Mac, having upgraded it to Sequoia, but it doesn't work... 
This also prevents me from launching several programs that require X11.

**Comment by c-hoeger** [comment]
Had the same issue. Solved by reinstalling it.

**Comment by RenatoEsposito1999** [comment]
Hi everyone, I have the same problem, but uninstalling and reinstalling it does not solve the problem.
When I open the XQuarz application, the logo appears in the dock but then it closes immediately.

**Comment by 7k8m** [comment]
Same issue of me.

Here is some of logs of commands.
````
tomohitonakayama@toyger ~ % xeyes
Error: Can't open display: /private/tmp/com.apple.launchd.Twx9ezZwMY/org.xquartz:0
tomohitonakayama@toyger ~ % Xorg 
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
_XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for local
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/Users/tomohitonakayama/.local/share/xorg/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
````

Might be a port conflict of listening socket ...

**Comment by 7k8m** [comment]
Not sure what is the port XQuarz is configured with default, but default 6000 of X Window was not in use on my environment ... 🫤 
`````
tomohitonakayama@toyger ~ % lsof -i :6000
tomohitonakayama@toyger ~ %   
`````

**Comment by jeremyhu** [comment]
I suspect it got disabled in System Preferences -> General -> Login Items.
