### ISSUE TITLE
Como posso utilizar o comando Crtl-X no mac?

### ISSUE THREAD

**Issue by ohudsonsilva** [XQuartz/XQuartz#412]
![Captura de Tela 2024-09-26 às 01 37 10](https://github.com/user-attachments/assets/81661c81-165d-4831-9900-ac6e2d6caf23)

Preciso executar essa função de exit, mas não faço ideia do que apertar. Cmd X, não funciona.

**Comment by jeremyhu** [comment]
^ is control.
