### ISSUE TITLE
Weird permissions dialog during install of 2.8.0_beta1

### ISSUE THREAD

**Issue by tglsfdc** [XQuartz/XQuartz#42]
I just installed beta1 on a Big Sur (11.1) Intel Macbook.  Nearly at the end of the install, I got a dialog box saying

"Installer" wants access to control "System Events".  Allowing control will provide access to documents and data in "System Events", and to perform actions within that app.

I hit the "Don't Allow" button and installation seemed to complete successfully anyway.  I've been using the resulting installation for a few minutes without obvious issues.

**Comment by larb0b** [comment]
I believe this is from here: 

https://github.com/XQuartz/XQuartz/blob/c3ecc48c4081a74552c6c4bfaf306bddc103391e/pkg/scripts/postinstall#L67

There's nothing wrong with XQuartz, macOS is just really tight with allowing things like this without explicit permission from the user as of around Mojave or so.

**Comment by jeremyhu** [comment]
Yeah.  I need to look into whether or not there is a new way to do that...

**Comment by larb0b** [comment]
> 
> 
> This does not ask for permissions when run from Terminal.app on Big Sur (11.1):
> 
> ```shell
> message="You will need to log out and log back in to make XQuartz your default X11 server."
> osascript -e "display dialog \"$message\" buttons {\"OK\"} with icon caution"
> ```

You might've already given Terminal Full Disk Access or the System Events permission already.

**Comment by jeremyhu** [comment]
That's because Terminal is special...

**Comment by jeremyhu** [comment]
We need to replace all that with an installer plugin.  Here's an example starting point:

https://gist.github.com/xorrior/86948fb6782efe87f26a704e81dbf0fc

**Comment by tlk** [comment]
Okay, just for clarity here is a comparison of the two approaches run from the same Terminal.app process:
```bash
$ osascript -e 'tell application "System Events" to display dialog "Foo"'
36:59: execution error: Not authorized to send Apple events to System Events. (-1743)
$ osascript -e 'display dialog "Foo"'
button returned:OK
$
```

Notice the first command is similar to what is being used in the `postinstall` script. It spawned a dialog asking for permission which I declined. The second command immediately displayed the "Foo" message in a dialog, without asking for permissions.

**Comment by jeremyhu** [comment]
I'm pretty certain the second does't work from the post-install script because the installation script is run in the system bootstrap.

Either way, moving to Installer plugins is the reccomended approach, so that's what we should do.
