### ISSUE TITLE
XQuartz autostarting and integration with X2GO failure

### ISSUE THREAD

**Issue by kamentsvetanov** [XQuartz/XQuartz#43]
Hello,

I have been using XQuartz to facilliate X11 forwarding for X2Go remote server session on Catalina and BigSur for a while now. After updating XQuartz (prompted to update today) I can no longer open a display on the remote server, despite the fact that X2GO establishes connection. 

In addition, every time I close XQuarz (and X2Go), it relaunches automatically, unless I log out and log in.

Any help and advise would be greatly appreciated.

Many thanks!

**Comment by nrclark** [comment]
I see the same auto-relaunch bug. Every time I quit XQuartz, it auto relaunches. There's effectively no way to shut it down other than a reboot.

**Comment by jeremyhu** [comment]
That is almost certainly because DISPLAY is still pointing to org.macosforge.xquartz.startx.  That should be adddressed by deleting the LaunchAgent as I mentioned in the release notes or grabbing beta2's installer which will do so.

See https://github.com/XQuartz/XQuartz/issues/36
