### ISSUE TITLE
command-backtick doesn't work to move between windows in XQuartz 2.8.0_beta1

### ISSUE THREAD

**Issue by icktharus** [XQuartz/XQuartz#46]
command-backtick, which I use to switch between X windows in the release version of XQuartz, doesn't work to switch between windows anymore.  The option is checked in my System Preferences > Keyboard > Shortcuts > Keyboard > "Move focus to next window" setting:

![image](https://user-images.githubusercontent.com/7990799/106512705-d06afd80-6486-11eb-8c7d-44b45139a804.png)

macos version: 10.15.7 (19H512)
xquartz version: XQuartz 2.8.0_beta1 (xorg-server 1.19.7)

Let me know if there's any more information you may need.

**Comment by icktharus** [comment]
Never mind, I didn't notice that the preferences had been reset with the update.

**Comment by bzbarsky** [comment]
@icktharus I'm seeing this exact problem with both 2.7.11 and with 2.8.0_beta1.  Which preference did you set to make this work that got reset with the update?

**Comment by icktharus** [comment]
I had to uncheck: X11 Preferences > Input > Enable key equivalents under X11

**Comment by bzbarsky** [comment]
Huh, interesting.  That seems backwards: I would expect unchecking this to _not_ do normal window management stuff on ``Cmd+` ``.  So I guess I get to choose between having `Cmd+N` and `Cmd+Q` work and having ``Cmd+` `` work...

**Comment by icktharus** [comment]
That does seem counter-intuitive to me, too, since it's a macos key equivalent that is enabled when you uncheck it.  I'm sure it's an unintended side-effect of something having to do with window + keyboard management, and maybe it would be better to have another preference for just those options, `Cmd+N`, `Cmd+Q` and ``Cmd+` ``?

**Comment by bzbarsky** [comment]
I filed https://github.com/XQuartz/XQuartz/issues/56
