### ISSUE TITLE
XQuartz with Big Sur 11.1 for Mac

### ISSUE THREAD

**Issue by maiihn** [XQuartz/XQuartz#47]
Hi,
I updated my iMac on Sunday from Catalina to Big Sur 11.1 and I received a notification to update XQuartz to the beta 2.8.0. After I updated XQuartz to the beta 2.8, I cannot use XQuartz anymore. I then uninstalled the 2.8.0 and installed the 2.7.7 again but cannot use it as well. So I don't know if it is because of the Big Sur update.
Do you have any suggestion to fix this error?

Thank you!

**Comment by jeremyhu** [comment]
You have not provided any details here regarding what your issue is, so there isn't really a way for me to help.  Can you please be specific abou the problem you are having?  Did you logout and log in after installing 2.8.0_beta2?

**Comment by wy2136** [comment]
I got similar problem for Big Sur 11.2. XQuartz 2.8.0_beta2 can not be opened. After downgrading to 2.7.11, I was not able to use "ssh -X", which always led to freezing.  It looks XQuartz 2.8.0_beta3 solved this problem.
