### ISSUE TITLE
XQuartz-2.8.0 should migrate preferneces from the previous preference domain

### ISSUE THREAD

**Issue by matsm** [XQuartz/XQuartz#49]
1) Application->customize   don´t show any characters when Mac is in dark mode
I run macos v11.2

2) Configuration (application->customize) made in previous version did not show up after upgrading to Xquartz 2.8.0_beta3

**Comment by jeremyhu** [comment]
#32

**Comment by jeremyhu** [comment]
Note that this change will only help folks that haven't launched 2.8.x previously.  Unfortunaltey, 2.7.11 was set to use the beta sparkle feed, so that's not going to help some folks who mistakenly got the update.

If that's you, you can handle this yourself with:

    cp "${HOME}/Library/Preferences/org.macosforge.xquartz.X11.plist" "${HOME}/Library/Preferences/org.xquartz.X11.plist"
    killall -9 cfprefsd
