### ISSUE TITLE
Is XQartz my solution?

### ISSUE THREAD

**Issue by Elmit2015** [XQuartz/XQuartz#5]
I have a Linux server, which i want to reach with ssh -X ... (actually I use a config file)
From my other Linux machines it works fine, but not from Catalina.

Would XQartz help in that case?

**Comment by sydney0zq** [comment]
Yes I have the same issue.

**Comment by tammojan** [comment]
Yes, XQuartz is what you need here.

**Comment by tammojan** [comment]
For installation instructions, see https://www.xquartz.org/

**Comment by sydney0zq** [comment]
I have tried the dmg installation file, however XQuartz is not working on MacOS Catalina.
