### ISSUE TITLE
2.8.0_beta3 installer reports digital signature verification error on 10.11 and earlier

### ISSUE THREAD

**Issue by jeremyhu** [XQuartz/XQuartz#50]
The 2.8.0_beta3 installer reports that the package's digital signature is invalid.  It works on 10.12 and later.

![OS X 10.11](https://user-images.githubusercontent.com/1258676/106649648-bd1f6700-6546-11eb-876b-3d8bda4ea437.png)
![macOS 11](https://user-images.githubusercontent.com/1258676/106649660-c0b2ee00-6546-11eb-82aa-8f2c0c73bc2a.png)

**Comment by jeremyhu** [comment]
<rdar://problem/73888463>

**Comment by jeremyhu** [comment]
This is a bug in macOS Big Sur impacting signing packages for 10.11 and earlier.  The issue is understood, and Apple will hace a fix for this issue in a future version of macOS.

One workaround is to re-sign the package on Catalina.

**Comment by nickcounts** [comment]
Some possibly useful info here: [](https://developer.apple.com/forums/thread/664842)

**Comment by jeremyhu** [comment]
This is fixed in 2.8.0_beta4 which will be released shortly.
