### ISSUE TITLE
XQuartz-2.7.11 (latest release) pulls updates from the beta channel

### ISSUE THREAD

**Issue by tlk** [XQuartz/XQuartz#51]
The latest (non-alpha, non-beta) release is checking the beta channel for updates. This means that users are being offered updates from the beta channel unless they have actively chosen to subscribe to the (non-beta) release channel like this:

```
defaults write org.macosforge.xquartz.X11 SUFeedURL https://www.xquartz.org/releases/sparkle/release.xml
```

Please see https://github.com/XQuartz/XQuartz/issues/44#issuecomment-771846389 for details.

**Comment by jeremyhu** [comment]
Ugh.  It looks like 2.7.11 incorrectly referenced the beta channel for updates.  =(

Had I known that I'd've been even more cautious about transitioning 2.8.0 to the beta channel.  As it is, however, there's not much I can do to change 2.7.11 now.

I'm going to use this to harden our build script to have the URL based on the version string rather than changing both.

**Comment by wesgarland** [comment]
Hey, I am a user who was probably affected by this and am pleased as punch that I got the notification.  2.7.11 has serious issues with emacs that were fixed on linux Xorg years ago (crashing on window resizing).  2.8 is working great for me tonight!!! :) :) :) 

That said, my SUFeedURL currently says `beta.xml` - maybe installing the beta changed it?  If not -- the GUI must have offered me the beta channel at some point. I am certain that I never changed it with `defaults`

**Comment by jeremyhu** [comment]
@wesgarland Yeah, the feed URL is set in the app bundle's Info.plist and can be overwritten with the defaults write.  It looks like 2.7.11 had the wrong value in the Info.plist.  At-least 2.8.0_beta3 is mostly stable enough for folks (well at least the ones on new-enough macOS that can install it)

**Comment by pentiumoverdrive** [comment]
yeah, apparently I updated to "XQuartz 2.8.0_beta3 (xorg-server 1.19.7)" and none of my xforwarding works anymore (nothing happens) and my old bookmarks in xquartz disapeared. This is on Big Sur.

Bookmarks came back after reinstall of 2.7.11 and everything started working again.

**Comment by jeremyhu** [comment]
What do you mean by "bookmarks"?  If you mean your Applications menu and other preferences, please see #49.

What do you mean by "none of my xforwarding"?
