### ISSUE TITLE
XQuartz should better handle the case of upgrading from 2.7.x without logging out

### ISSUE THREAD

**Issue by dershow** [XQuartz/XQuartz#52]
I just upgraded to 2.8.0_beta3 from 2.7.11.  XQuartz immediately launched.  If I quit it just immediately relaunches.  I don't have anything currently displaying with X11.
How can I get it to stop relaunching?

**Comment by jeremyhu** [comment]
What does `echo $DISPLAY` report?

Did you logout and login?  The installer should have told you to if that reports the old macosforge DISPLAY string.

**Comment by dershow** [comment]
I hadn't tried to logout.  I did now and the problem has gone away.
As a related note, when I first tried to restart, I got an issue about XQuartz being opened so, I quit it again, and then the restart continued fine.  
Thank you,

**Comment by jeremyhu** [comment]
Ok.  I'm going to leave this open, so others can find it, and I'll see if I can better detect this case.
