### ISSUE TITLE
the "active x11 window losing focus" issue

### ISSUE THREAD

**Issue by giardiacorp** [XQuartz/XQuartz#53]
does anyone know if the xQuartz 2.8.0 version fixes the issue where the active window loses focus, seemingly at random? when this happens, no window has focus. so whatever you were typing at the time was lost.

i have had this issue for years and never seen any post where the cause was well established. i have never seen a good fix described. the cause may be the calendar for one person, or the location menu for another. i have tried many of the fixes proposed, with no effect. here are a few links to this type of issue over the years:

https://github.com/XQuartz/xquartz-old-tickets/blob/master/ticket/58.md
https://apple.stackexchange.com/questions/83972/x11-periodically-losing-focus
https://discussions.apple.com/thread/7964085
https://superuser.com/questions/213185/x11-application-losing-focus-after-1-2-secs

**Comment by jeremyhu** [comment]
Yes, it does.  That was fixed upstream a while ago.  Give 2.8.0_beta3 a try.
