### ISSUE TITLE
Indirect GLX no longer working?

### ISSUE THREAD

**Issue by alexzielenski** [XQuartz/XQuartz#54]
Updated to 2.8 today and my old config which relied on using the GLX extension over SSH is no longer working. 

Steps followed:

1. Update to 2.8
2. Log out and in
3. Run `defaults write org.xquartz.X11 enable_iglx -bool true`
4. Run `xquartz +extension GLX`
5. `ssh -X host.local`
6. `glxinfo`
7. glxinfo either hangs forever or reports `X_GLXIsDirect` failed

**Comment by vgribov** [comment]
For me it doesn't hang and seems to work, but with a bit of a hack. I've modified a bit line 117 in `/opt/X11/bin/startx`:

```
    defaultserverargs="$defaultserverargs +iglx +extension GLX"
```

and issued then `defaults write org.xquartz.X11 enable_iglx -bool true`. But performance is, unfortunately, awful.

**Comment by jeremyhu** [comment]
`+extension GLX` shouldn't be needed.  I see it enabled by default.  Is there something I'm missing here?

**Comment by jeremyhu** [comment]
(also some of the perf hit might be because the beta builds enable ASan which will surely take a hit here)

**Comment by jeremyhu** [comment]
I didn't need to edit startx, and it seems to work fine for me.

I have 2.8.0_beta3 running on an M1 MacBook Air.  I instlaled Parallels Preview 2 for Apple Silicon and put Ubuntu 20.04 on it.

I ran `ssh -Y <ip of the VM>`

I then ran `xterm` on the VM, to confirm X11 forwarding worked in general.

I then ran `glxinfo` and `glxgears` from that xterm fine.

**Comment by jeremyhu** [comment]
"+extension GLX" should not be needed because noGlxExtension defaults to FALSE, so it's already on by default...
