### ISSUE TITLE
Can't switch XQuartz windows with Cmd+` (command+backtick) unless "Enable key equivalents under X11" is disabled

### ISSUE THREAD

**Issue by bzbarsky** [XQuartz/XQuartz#56]
Version: 2.7.11 and 2.8.0_beta1

There's a weird inconsistency in the way ``Cmd+` `` is handled compared to other shortcuts (Cmd+C, Cmd+N, Cmd+Q, etc).  Those shortcuts do their special function (copy, open an xterm, quit XQuartz) if "Enable key equivalents under X11" is enabled, but not otherwise.  But Cmd+backtick is the other way around: it switches X windows if that option is _disabled_ and stops doing it when the option is enabled.  This seems backwards.

**Comment by jeremyhu** [comment]
Cmd+` is handled by quartz-wm in the case where "Enable key equivalents under X11" is disabled.  In the case where it is enabled, that keystroke is handled by the macOS Window Server.

It sounds like this is a regression in macOS. Can you please file this issue with Feedback Assistant and report the FB number here, so I can followup with it internally?

**Comment by bzbarsky** [comment]
@jeremyhu FB8992230 submitted.

**Comment by jeremyhu** [comment]
<rdar://problem/74038002>

**Comment by jeremyhu** [comment]
Looks like this regressed in Catalina.

**Comment by alsuchanek** [comment]
Hey Jeremy,
Was this issue with command+backtick resolved and implemented in the latest Xquartz update or is this something I need to manually fix?
thanks

**Comment by jeremyhu** [comment]
It was fixed in 2.8.0
