### ISSUE TITLE
XQuartz 2.8.0 Beta

### ISSUE THREAD

**Issue by VictorPoreeFr** [XQuartz/XQuartz#57]
Dear all,

I am a Mac user (Big Sur) and I updated my XQuartz to the 2.8.0 version as suggested by XQuartz, followed by a restart of the laptop. However it is not working at all. I cannot start apps which depend on XQuartz and I cannot use ssh neither. I tried downgrading but without success. For the Apps they say that they cannot find XQuartz on the computer. For ssh, it does not answer for a few minutes and then times out.
The XQuartz app it there, I can start it but it is not responding and keeps launching itself from time to time.

Best,

Victor

**Comment by eacmen** [comment]
> Dear all,
> 
> I am a Mac user (Big Sur) and I updated my XQuartz to the 2.8.0 version as suggested by XQuartz, followed by a restart of the laptop. However it is not working at all. I cannot start apps which depend on XQuartz and I cannot use ssh neither. I tried downgrading but without success. For the Apps they say that they cannot find XQuartz on the computer. For ssh, it does not answer for a few minutes and then times out.
> The XQuartz app it there, I can start it but it is not responding and keeps launching itself from time to time.
> 
> Best,
> 
> Victor

I am also experiencing this same issue. I cannot ssh to any hosts that have X11Forwarding enabled. This update was pushed out during automatic update process (I do not have beta updates enabled), so I foresee many other users having this same issue. The process that seems stuck is `xauth`. This is the process listing that I get when ssh hangs trying to connect to any host with X11 enabled:

```
  501 13987 13986   0  1:02PM ttys000    0:00.00 sh -c /opt/X11/bin/xauth -f /var/folders/93/qcw0854x2yqbc9qt2j90yy780000gn/T//ssh-lst0whyjisyV/xauthfile generate /private/tmp/com.apple.launchd.1FdEdFP50w/org.macosforge.xquartz:0 MIT-MAGIC-COOKIE-1 untrusted timeout 1260 2>/dev/null
  501 13988 13987   0  1:02PM ttys000    0:00.00 /opt/X11/bin/xauth -f /var/folders/93/qcw0854x2yqbc9qt2j90yy780000gn/T//ssh-lst0whyjisyV/xauthfile generate /private/tmp/com.apple.launchd.1FdEdFP50w/org.macosforge.xquartz:0 MIT-MAGIC-COOKIE-1 untrusted timeout 1260
  ```

**Comment by eacmen** [comment]
Sorry devs, should have researched it more. Simple logout/login fixed it for me. Anyone else with this issue just logout and log back into your MacOS account, or just reboot your machine.

**Comment by VictorPoreeFr** [comment]
I tried the log out log in or as well as restarting the computer but it did not solve anything. I tried removing my X11 environment and restart from scratch, installing the previous XQuartz version but still won't ssh anywhere and apps depending on it won't launch.
There is no error message at all, it just does not do anything. I could use some help to pin point the problem.

**Comment by wrobelda** [comment]
Same exact problem here:

```
me@Daves-Macbook-Air: xhost +                                                                                                                   
access control disabled, clients can connect from any host

me@Daves-Macbook-Air: telnet localhost 6000  
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```

**Comment by jeremyhu** [comment]
@wrobelda 2.7.11 and 2.8.0 have different preference domains.  I suspect you have nolisten_tcp disabled in 2.7.11.  That is tracked in #49.

**Comment by VictorPoreeFr** [comment]
Downgrading did not work for me.

**Comment by wrobelda** [comment]
@jeremyhu I think it's more convoluted than just that. I restarted my system and 2.7.11 stopped working now, too. `xhost +` just hangs indefinitely. I cannot telnet to 6000 on localhost. No combination of `no_auth` and `no_listen` has any effect on it. 

I also noticed that Xquartz restarts automatically after quitting. Even if I kill all the X processes, they'll all come back up instantly. I have never witnessed such behavior before. Purging Xquartz and its settings domain, uninstalling, installing again – none of that helps. Everything worked flawlessly before 2.8.0 installation. 

I think at this point it is reasonable to assume that 2.8.0 permanently changes something in the system that affects even the downgraded versions?

**Comment by VictorPoreeFr** [comment]
It appears that my /tmp/ .X11-unix/ folder is completely empty. 
Another colleague has the same problem, running Sierra I think.

**Comment by jeremyhu** [comment]
/tmp/ .X11-unix/ is expected to be empty when no server is running.

**Comment by VictorPoreeFr** [comment]
It complains about it when the terminal is trying to call it. Unticking and ticking the two boxes in the security preferences of xquartz followed by a restart solve the problem for some software depending on xquartz apparently. But not with the terminal.

**Comment by VictorPoreeFr** [comment]
I am trying multiple things including macports and I get this message way to often:
Error: Port xorg-server not found
Any idea how I can solve this step?
