### ISSUE TITLE
XQuartz 2.8.0 Beta constantly restarting ... downgrade to 2.7.11 now does same

### ISSUE THREAD

**Issue by matthewvon** [XQuartz/XQuartz#58]
I clicked the upgrade box for 2.8.0.Beta.  2.8.0.Beta launched with "XQuartz quit unexpectedly".  A downgrade to 2.7.11 now does the same.  I was happily using XQuartz for years with emacs.  Now mostly dead in the water as a programmer.

Is there a resource file or something that I need to erase to get 2.7.11 back to operating reliably?

**Comment by matthewvon** [comment]
Hmm, install of Beta3 appears to have corrected the problem.

**Comment by wrobelda** [comment]
It shouldn't be closed. I have the same issue after downgrading to 2.7.11. Uninstalling 2.8.0 clearly leaves some leftover files behind.
