### ISSUE TITLE
"Operation not permitted" errors when accessing Desktop, external volumes, and other restricted paths

### ISSUE THREAD

**Issue by ffm-fg** [XQuartz/XQuartz#6]
After installing Catalina I find a strange problem with XQuartz

1) If I go to Desktop and type "ls" it says "operation not permitted"
2) If I put the XQuartz app in the Security & Privacy app to give privilege to XQuartz, I have the 
same result: type "ls" inside the Desktop and get "operation not permitted"
3) If however I gave the priorities to Terminal.app of mac, and inside terminal-app I type 
"xterm", this launch XQuartz and then from xterm (from XQuartz) I can see with "ls" all files 
in Desktop. 

It seems that XQuartz and the new security of Catalina do not fit

**Comment by lucl13** [comment]
Same thing for me

**Comment by mellery451** [comment]
xquartz won't launch at all for me (after reinstalling even). I try starting the xserver manually, but it fails consistently.

**Comment by ffm-fg** [comment]
I found the following solution that works for me:

1) do not start xquartz
2) launch the application Terminal
3) from Terminal type xterm. The will launch xquartz with the privileges of Terminal
4) now xquartz is on, and if you open xterm from xquartz there are no problems. 

This solution is not elegant but it works

**Comment by mellery451** [comment]
trying to launch `xterm` from terminal just gives me the error:
    
    xterm: Xt error: Can't open display: :0.0

I also tried manually launching `Xquartz from the same command line and it emitted the message:

    -: line 0: exec: keymap: not found

and then exited a few seconds later.

**Comment by kiwiroy** [comment]
Same observations as @ffm-fg and noting the process trees of the shell are as follows.

Starting XQuartz from Spotlight.
```
-+= 00001 root /sbin/launchd
 \-+- 08022 kiwiroy /opt/X11/bin/xterm
   \-+= 08173 kiwiroy bash
     \-+= 08700 kiwiroy pstree -p 8173
       \--- 08701 root ps -axwwo user,pid,ppid,pgid,command
```

Launching via Terminal
```
-+= 00001 root /sbin/launchd
 \-+= 08614 kiwiroy /System/Applications/Utilities/Terminal.app/Contents/MacOS/T
   \-+= 08615 root login -pf kiwiroy
     \-+= 08616 kiwiroy -bash
       \-+= 08628 kiwiroy xterm
         \-+= 08629 kiwiroy bash
           \-+= 08698 kiwiroy pstree -p 8629
             \--- 08699 root ps -axwwo user,pid,ppid,pgid,command
```

**Comment by kiwiroy** [comment]
> 2. If I put the XQuartz app in the Security & Privacy app to give privilege to XQuartz, I have the
same result: type "ls" inside the Desktop and get "operation not permitted"

The trick appears to be to add `/bin/bash` to the *Full Disk Access* privilege if that's your `$SHELL`

**Comment by 1-rphillips** [comment]
@kiwiroy 's trick works, but _not for accessing external and/or network volumes_. The behavior is the same as the original (Feb 1 2020) issue comment.

Steps to reproduce:
- mount an external volume (e.g., external drive of some sort, network volume, etc.)
- open xterm (Xquartz > Applications > Terminal)
- cd to external volume
- ls -la

Expected behavior:
Directory listing occurs

Actual behavior:
"ls: .: Operation not permitted"

Cheers-

**Comment by IComplainInComments** [comment]
> @kiwiroy 's trick works, but _not for accessing external and/or network volumes_. The behavior is the same as the original (Feb 1 2020) issue comment.
> 
> Steps to reproduce:
> 
>     * mount an external volume (e.g., external drive of some sort, network volume, etc.)
> 
>     * open xterm (Xquartz > Applications > Terminal)
> 
>     * cd to external volume
> 
>     * ls -la
> 
> 
> Expected behavior:
> Directory listing occurs
> 
> Actual behavior:
> "ls: .: Operation not permitted"
> 
> Cheers-

This I think is due to how macOS now handles certain directories, as a lot of "user" owned directories are sub-owned by the system. This is why when you launching xterm from Terminal allows for modifying the process with new permissions. 

It has to do with the process hierarchy, maybe modifying the launchd plists for xQuarts might do the trick? Maybe specifying what "rights" the process requires, or changing how the 'login' system for the shell works in xterm?

Have you tried `sudo xterm` and see if that will give you what you need?

**Comment by ffm-fg** [comment]
This is how it works for me: 

security& Privacy —>  
a) Full Disk Access; 
b) Files and Folders: XQuartz

Launch  Terminal and from Terminal launch XQuartz. 
Now you can quit Terminal, but XQuartz keep running

If I open xterminal in XQuartz it behaves well also with external  Volumes

**Comment by 1-rphillips** [comment]
@IComplainInComments `sudo xterm` _does_ work (though without any _user's_ default shell interpreter, but with presumably _root's_ default shell interpreter, `sh` - so whatever `sh` happens to point to on the system). Good point.

@ffm-fg I'd love to just add XQuartz to any of the Privacy sidebar options, that would be an acceptable (if still not correct) way forward, but _that's not actually an option_ when I attempt to do so for Files and Folders.

**Comment by jeremyhu** [comment]
Sorry for not getting around to looking at this sooner.  Has anyone filed a bug report about this with Apple?  I just did now in case it hasn't been filed yet (<rdar://problem/74379852>).  If you have filed it, please report back your ticket number, so I can relate.  Thanks.

**Comment by jeremyhu** [comment]
If you rename XQuartz.app/Contents/MacOS/X11 to XQuartz.app/Contents/MacOS/X11.sh and rename XQuartz.app/Contents/MacOS/X11.bin to XQuartz.app/Contents/MacOS/X11 (such that launching XQuartz.app bypasses the shell script), that seems to address the issue for me.  The shell script is messing up the system's notion of responsibility here.

**Comment by kiwiroy** [comment]
@jeremyhu, All looks good with the changes running version 2.7.11. Thanks
