### ISSUE TITLE
Unable to quit after downgrading to 2.7.11 – keeps restarting

### ISSUE THREAD

**Issue by wrobelda** [XQuartz/XQuartz#62]
It is impossible to permanently quit Xquartz 2.7.11 after downgrading from 2.8.0 – it, and the corresponding services, will automatically restart immediately after quitting. I do not see any mentioning in the changelog about this being an intended behavior and I do not recall it ever behaving like this, so it looks like 2.8.0 leaves some files/scripts/settings behind.

**Comment by jeremyhu** [comment]
#52
