### ISSUE TITLE
XQuartz 2.8.0b3 has small font families

### ISSUE THREAD

**Issue by pokynmr** [XQuartz/XQuartz#63]
Hello-

Thanks or pushing this project forward.
I've accidentally upgraded from 2.7.11 to 2.8.0.b3.
After that I have much less number of fonts in X11 programs.
fc-list shows full list of available fonts in the system. However, xfontsel only shows font families in /opt/X11/share/fonts. Apps are complaining "Fontconfig error: Cannot load default config file"
I tried to go back to 2.7.11 but it does not work. On 2.7.11, apps hang forever when launched.
I am using MBP16 with macOS Catalina 10.15.7.

Thanks,
Woonghee

**Comment by pokynmr** [comment]
It seems it is due to tangled libraries from the software side. It is okay now. Thank you!

**Comment by pokynmr** [comment]
This may be helpful to find the cause. I tested two fresh Catalina 10.15.7 with 2.7.11 and 2.8.0b3 respectively.
With Python 3.7.7 + Tcl/Tk 8.6.8, XQuartz 2.7.11 works as expected. With 2.8.0b3, it crashes right away with this error:

failed to allocate font due to internal system font engine problem.

**Comment by jeremyhu** [comment]
Ok, then closing since the issue is with another libX11 and not ours.
