### ISSUE TITLE
Copy/paste from X11 to macOS doesn't work in 2.8.0_beta3

### ISSUE THREAD

**Issue by tglsfdc** [XQuartz/XQuartz#64]
AFAICT, Xquartz doesn't update the macOS Pasteboard anymore, neither from just selecting text nor with an explicit command-C.

I'm not entirely sure if this broke in beta3, or due to updating to Big Sur 11.2, which I did at about the same time.  I think it was working OK in beta1 + 11.1, though.

Copy/paste in the other direction still works, as does copy/paste between X11 windows.

**Comment by tglsfdc** [comment]
After reverting to XQuartz 2.7.11, copy/paste works again.  So it's not the fault of the new Big Sur version.

**Comment by mladen5000** [comment]
I was able to change X11 preferences to solve this. Under pasteboard, 3rd option

**Comment by jeremyhu** [comment]
#49

**Comment by tglsfdc** [comment]
Hmmm ... I'm not convinced this is a dup of #49, because I absolutely did have those prefs turned on (I had done so manually after noting that beta1 failed to import my old prefs).  I reinstalled beta3 to check that, and they were indeed on.

However ... now I can't reproduce the misbehavior.  So I don't know what to think, except that there might be some contributing condition I haven't identified.

**Comment by tglsfdc** [comment]
I've just seen this happen again with beta4.  Copy-and-paste was working fine, and then it stopped working.  I can report that restarting XQuartz makes it work again.  I still don't know what the trigger is that makes it stop working ... but there absolutely is a bug here, it's not "you got the preferences wrong".

See also issue #90, which I bet is the same thing.

**Comment by tglsfdc** [comment]
Still happens with rc2.  I experimented with toggling Xquartz's Pasteboard-related preferences off and back on, but that was not enough to get it working again; full Xquartz restart seems necessary once it's gone south.  I continue to lack a theory as to the triggering condition, but this bug is plenty real.

**Comment by jeremyhu** [comment]
Yeah, the proxying has had problems as long as it's been around.  Nobody's really invested in improving it.  It's fairly self-contained code and could use some love if you want to dig into it or know someone who could.
