### ISSUE TITLE
After install Xquartz keeps launching on its own MacOS 11.2

### ISSUE THREAD

**Issue by StephPeriquet** [XQuartz/XQuartz#69]
For the past 3 days now (I have no idea what triggered the change, I didn't do anything nor any upgrade...), Xquartz 2.7.11 launches on its own even I quit it multiple times. I installed and reinstalled multiple times as well, and the only way to stop the process is to log off and log back in on my Account.
XQuartz doesn't crashed it keeps launching itself over and over...
Since then, the X11() command on R (4.0.3) also stopped working and basically crashes R with nothing on Xquartz happening.
I'm on MacOS 11.2.
Any idea what is happening?

**Comment by jeremyhu** [comment]
#52.  Logout and log back in.

**Comment by StephPeriquet** [comment]
Hi @jeremyhu, 

Thanks for your reply but I did that several times without any effects.
I finally decided to installed the beta version and things seem to be back to normal....
