### ISSUE TITLE
The application "XQuartz" can't be opened on macOS Catalina

### ISSUE THREAD

**Issue by AndreaCogliati** [XQuartz/XQuartz#70]
I haven't used XQuartz in a while and when I tried to run it today I got an error dialog: The application "XQuartz" can't be opened. I tried reinstalling it from the image `XQuartz-2.7.11` to no avail. The only relevant log entry I could find is in `system.log`:

`Feb 12 13:26:42 MacBook-Pro-i9 com.apple.xpc.launchd[1] (org.macosforge.xquartz.X11.66776[6541]): Service exited with abnormal code: 127`

I'm running macOS Catalina 10.15.7 on an Intel MacBook Pro.

**Comment by jeremyhu** [comment]
#52.  Logout and log back in.

**Comment by AndreaCogliati** [comment]
That’s the first thing I tried and it didn’t fix the issue. Reboot didn’t work either. Any other suggestions?

**Comment by jeremyhu** [comment]
Sorry, I missed the followup since it was closed.  Please try 2.8.0_rc4 and re-open if you still have issues.

**Comment by AndreaCogliati** [comment]
Actually the issue was my `.zprofile` file. I recently installed Intel oneAPI and I had the initialization script in the `.zprofile` file. I moved the script to the `.zshrc` file, and now everything works properly.
