### ISSUE TITLE
2.8.0_beta3 missing freetype-config

### ISSUE THREAD

**Issue by tamisen** [XQuartz/XQuartz#73]
I installed XQuartz 2.8.0_beta3 on my M1 MacBook Air. Building SDL_ttf from source is failing because it can't find freetype-config in the expected location /opt/X11/bin/freetype-config. That script is present on another machine where I have XQuartz 2.7.11 installed.

**Comment by jeremyhu** [comment]
Looks like it was made optional.

commit a7833f26c4ac45cafe1dffdcd7f7dcfd6493161c
Author: Hugh McMaster <hugh.mcmaster@outlook.com>
Date:   Wed Mar 7 22:23:54 2018 +1100

    Make installation of `freetype-config' optional (#53093).
    
    Signed-off-by: Hugh McMaster <hugh.mcmaster@outlook.com>
