### ISSUE TITLE
XQuartz keeps restarted when terminated

### ISSUE THREAD

**Issue by tommythorn** [XQuartz/XQuartz#74]
This is a behavior change in the new 2.8.0 beta 3 and it's bloody frustrating.  There doesn't appear to be a way to configure away this policy so I have to uninstall it every time I'm done using it.

**Comment by pentiumoverdrive** [comment]
Even happening on XQuartz 2.7.11 after removing the 2.8 beta...

**Comment by ljexplore** [comment]
I'm encountering the same issue with XQuartz 2.7.11 under Catalina 10.15.7. I once absentmindedly clicked through the installer wizard popup, but the thing is I don't have admin on the system, so I don't see how that could change things. Unless there are user preference files that are modified prior to admin authorization that cause this behavior?

**Comment by jeremyhu** [comment]
I suspect you didn't logout after installing 2.8.  #52.

**Comment by tommythorn** [comment]
Yes, sorry about that.
