### ISSUE TITLE
install clears custom application menu/not saving changes

### ISSUE THREAD

**Issue by joshuawinsor** [XQuartz/XQuartz#75]
I customized my "application menu" in 2.7.11 such that Terminal launches uxterm -sb
When beta installed, all custom menu items were gone.  Any time I have customized or added menu items relaunching clears the menu back to default
![Screen Shot 2021-02-15 at 11 32 27 AM](https://user-images.githubusercontent.com/47792681/107986766-98cd7c80-6f81-11eb-9892-e7bc3e595146.png)
![Screen Shot 2021-02-15 at 11 32 51 AM](https://user-images.githubusercontent.com/47792681/107986773-9b2fd680-6f81-11eb-97ee-b112c450a02c.png)

**Comment by jeremyhu** [comment]
#49
