### ISSUE TITLE
XQuartz 2.7.11 says it works “for OS X 10.6.3 or later”, but doesn’t work on 10.7.5

### ISSUE THREAD

**Issue by acli** [XQuartz/XQuartz#8]
On 10.7.5, opening XQuartz 2.7.11 through /Applications/Utilities does nothing. If I start it by hand with /opt/X11/bin/Xquartz it crashes on startup

Note: The installer seems to have touch(1)’d /usr/X11 for some reason, even though nothing under /usr/X11 has apparently been changed. Something seems to be seriously wrong with this release.

**Comment by macmeister1967** [comment]
I have had XQuartz running on ever release since Mavericks 10.9

Is there any known reason why you are still using 10.7.5? Are you still on PPC?

**Comment by acli** [comment]
It’s just inertia... or the fear of breaking things. It’s not PPC but it’s still a very underpowered system. Last time I upgraded the OS (on a different Mac) the system immediately slowed down so much I couldn’t even run a browser. I’ve been burned.

If there’s no intention to fix it maybe the documentation should be updated?

**Comment by mackyle** [comment]
I experienced a similar issue and tracked it down to a problem with fontconfig.  I was able to solve the problem by installing the XQuartz 2.7.4 release (the last version that had an older fontconfig that still worked properly).

I suggest you try installing XQuartz version 2.7.4.

All the XQuartz release installers are available from:

   https://www.xquartz.org/releases/archive.html
