### ISSUE TITLE
After install XQuartz my forticlient can not connect

### ISSUE THREAD

**Issue by rcarrascoz** [XQuartz/XQuartz#81]
Hello, I have MacMini Chip M1, and after install XQuartz, now I can use forticlient vpn. It can connect :( if you know what I can do. Thank you

I need to uninstall XQuartz, do you know how?

Regards,
Rafa.

**Comment by jeremyhu** [comment]
You probably just need to logout and log back in.  See #52.

If you have an issue other than that, please reopen with specific details about the bug.

If you just want help, please use the mailing list.

If you want to uninstall, please see the FAQ on the website which provides instructions.
