### ISSUE TITLE
XQuartz 2.7.11 window customizations dont work after trying 2.8 Beta on Mojave 10.14.x

### ISSUE THREAD

**Issue by Starman535** [XQuartz/XQuartz#82]
If restarting solved this issue, I wouldn't be leaving a message here. I tried 2.8.1 and 2.8.3 Betas, and had numerous problems. I reverted to 2.7.11. Now, the window customization (-sb -sl 20000 -bg LightBlue) etc no longer work. I removed the LaunchAgents as recommended, and that fixed some problems, but not this one. I am on a laptop that gets restarted every day. A suggestion would be appreciated.

**Comment by jeremyhu** [comment]
I suggest reaching out on the x11-users mailing list for help.  It's not clear here what you are reporting, and there are more people on the list who can help you figure out your issue.
