### ISSUE TITLE
XQuartz 2.8 and problems in FSLeyes 

### ISSUE THREAD

**Issue by chiaracarbone26** [XQuartz/XQuartz#83]
I have downloaded XQuartz beta version 2.8 on MacOS BigSur 11.2.1. When I try to change visualization in the program FSLeyes, this error appears:

The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadCurrentWindow'.
(Details: serial 86720 error_code 166 request_code 149 minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Could you help me?

**Comment by jeremyhu** [comment]
Please report this issue to the developers of fsleyes.  They should work with GTK / GDK folks to determine where in the stack this error is.  If the issue is in mesa or xserver and a patch is available to address it, I can bring it in at that time.
