### ISSUE TITLE
Beta3 and beta4 self-upgrades fail silently

### ISSUE THREAD

**Issue by sckendall2** [XQuartz/XQuartz#88]
When XQuartz 2.8.0_beta3 came out, I was running beta2. My attempt to upgrade: I get the ‘Software Update’ window. I click 'Install Update'. Pop-up ‘Updating XQuartz’ shows Downloading... or something like that and eventually shows 'Ready to Install'. I click ‘Install and Relaunch’. XQuartz quits and that's it; no relaunch. I wait a few minutes; nothing. I restart XQuartz and check the version. Still beta2. Eventually the 'Software Update' window reappears. If I again click 'Install Update', everything repeats like before, even the download.

The only way I found to upgrade to beta3 was to download the .dmg file using a web browser and double-clock on it.

Now that beta4 has come out, I get exactly the same behavior from the 'Software Update' window. I poked around in the console app but could find no logs that illuminated the failed upgrade.

**Comment by moyman** [comment]
This happens to me as well. Just as you describe. I have to download the dmg and install that way.

**Comment by sckendall2** [comment]
Forgot to add: this is on an x86 mac with macOS 11.2.1 (Big Sur).

**Comment by Chasapple4** [comment]
Can confirm with beta 3 and beta 4, have to manually grab the installer from GitHub to update.

> When XQuartz 2.8.0_beta3 came out, I was running beta2. My attempt to upgrade: I get the ‘Software Update’ window. I click 'Install Update'. Pop-up ‘Updating XQuartz’ shows Downloading... or something like that and eventually shows 'Ready to Install'. I click ‘Install and Relaunch’. XQuartz quits and that's it; no relaunch. I wait a few minutes; nothing. I restart XQuartz and check the version. Still beta2. Eventually the 'Software Update' window reappears. If I again click 'Install Update', everything repeats like before, even the download.
> 
> The only way I found to upgrade to beta3 was to download the .dmg file using a web browser and double-clock on it.
> 
> Now that beta4 has come out, I get exactly the same behavior from the 'Software Update' window. I poked around in the console app but could find no logs that illuminated the failed upgrade.

**Comment by jeremyhu** [comment]
Sounds like a bug in Sparkle.  I'll try to reproduce and file an upstream bug report if needed.

**Comment by jeremyhu** [comment]
Reproduced here.  2.7.11 updates just fine, but going from beta to beta with the new version of Sparkle is failing.

Sparkle downloads and extracts the update and presents the "Install and Relaunch" button but then doesn't actually do the install.

**Comment by sckendall2** [comment]
I just auto-updated from rc1 to rc2. The procedure was shaky and I had to do it twice. The first time, it restarted but didn't update. The second time, it updated but didn't restart. Below are details.

First try: as before, I used the 'Install Update' button. Clicking 'Install and Relaunch' downloaded and apparently installed. In fact I got prompted for my password, something I don't remember happening in earlier failures. And XQuartz was running after I finished the procedure, so either it restarted or it had never quit. But XQuartz > About X11 still said rc1.

The second try was the same, except that after I finished the procedure, XQuartz wasn't running -- it didn't restart. And when I started it, it was rc2.

**Comment by sckendall2** [comment]
The auto-update from rc2 to rc3 went smoothly.

My trouble with auto-updating from rc1 to rc2 probably involved pilot error (not noticing the pop-up window asking for my password).

**Comment by sckendall2** [comment]
There are still glitches. The 'Install Update' from rc3 to rc4 seemed to go smoothly, but XQuartz > About X11 still showed rc3. The second time was the charm. Both times, IIRC, I got the pop-up prompting me for my (administrator) password.

The first 'Install Update' from rc4 to the actual 2.8.0 release went the same as above -- I was prompted for my password, but after it was all over, the About X11 menu item still showed rc4. But this time, instead of trying to update again, I just quit and restarted. Success.

**Comment by jeremyhu** [comment]
I suspect that might be some issue with Sparkle quit / restart.  Maybe XQuartz was restart in the middle of the install (?).

Given that we're using sparkle 1.25 and they are in the process of a large refactor (sparkle 2.0), let's see how things are with 2.0 when we adopt it and then work with upstream if an issue remains.
