### ISSUE TITLE
Big Sur 11.2.1 - Lose windows with energy settings

### ISSUE THREAD

**Issue by moyman** [XQuartz/XQuartz#89]
I normally have 5-8 xterms running over SSH. After my machine goes to sleep my windows are gone when I wake back up. Even if I leave stuff running in the xterm. I don't think it has anything to do with SSH keepalive settings or network access. My secureCRT terminal windows over SSH remain open indefinately over weeks with the same energy settings. Both running at the same time my SecureCRT windows remain and my xterms are gone. 

I have seen this with 2.8.0 beta 2 & 3. Not done 4 yet. I never had this problem with 2.7.11 although it was with a different MacOS.

**Comment by moyman** [comment]
Not that I am not running a local xterm (although I shoud test that). I am using ssh to launch the xterm back to my machine:

ssh -Y <remote host> "/usr/bin/xterm  -geometry  80x24+2+2 -j -vb -cu -ls -s -bg DarkSeaGreen -sb -sl 5000 -name <remote host>"

**Comment by jeremyhu** [comment]
Yes, when your machine goes to sleep, those sockets start timing out and eventually the remote side will close the connection.
