### ISSUE TITLE
CMD-c and CMD-V for cut and paste don't work

### ISSUE THREAD

**Issue by moyman** [XQuartz/XQuartz#90]
I can't seem to find a setting that will let the standard MacOS cut and paste key sequence work. I think I have tried every interation. Its been a while but I would swear this used to work.

Big Sur 11.2.1 with 2.8.0 beta 3

**Comment by tglsfdc** [comment]
Is this specifically for copying from X11 windows to macOS windows?

If so, I think you are seeing the same issue I reported at
https://github.com/XQuartz/XQuartz/issues/64

So far it seems that restarting XQuartz makes it go away for awhile.  I don't know exactly what the trigger is that makes it stop working.

**Comment by jeremyhu** [comment]
Closing based on above.  This seems to be working for me.  The interaction between NSPaseboard and X11's PRIMARY and CLIPBOARD is sub-optimal but works for most common cases.
