### ISSUE TITLE
Re-add support for i386 clients

### ISSUE THREAD

**Issue by nbriggs** [XQuartz/XQuartz#93]
32-bit applications on macOS 10.11.6 fail with
```
dyld: Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Users/briggs/Projects/xxxxx
  Reason: no suitable image found.  Did find:
	/opt/X11/lib/libX11.6.dylib: no matching architecture in universal wrapper
```
There are only x86_64 and arm64 binaries in the libX11.6.dylib.   While I am in a position to rebuild this particular application, it's possible that there are others who could not.  If it's not possible to distribute the x86 32-bit code the installation instructions should mention that this functionality is being removed.

**Comment by kencu** [comment]
If you are interested, it is not unlikely that a fat i386/x86_64 version might be created.

You would clone the Xquartz repo, edit ```compile.sh``` to change the ```arm64``` references to ```i386``` in the ```archs``` in a couple of locations, and add an ```i386``` cross file that looks something like this:

in:
```
/meson_support/meson/cross/i386-darwin-xquartz
```

```
[host_machine]
system = 'darwin'
cpu_family = 'x86'
cpu = 'i386'
endian = 'little'

[binaries]
pkgconfig = '/opt/local/bin/pkg-config'
cmake = '/opt/local/bin/cmake'
strip = '/usr/bin/strip'
```

And then build it on 10.13.

I have not tried it, but there is a fighting chance it would "just work".

**Comment by kencu** [comment]
Oh -- perhaps not https://github.com/XQuartz/xorg-server/commit/59f22341a8b4cd468d6f37fb17dd7fde347e430b

**Comment by jeremyhu** [comment]
That change only drops support in the server.  We could add support for the client-side libraries, but it would require grabbing the latest SDK that supports building for i386 (10.13?), compiling i386 binaries against that SDK, and then lipoing them together with the arm64+x86_64 binaries.

**Comment by kencu** [comment]
10.13 was the last i386-inclusive SDK, indeed.

**Comment by mrbatchelor** [comment]
Yes please to this! An old piece of software has stopped working and I'm having trouble reinstalling an old version of Xquartz (on 10.13) that will work for everything.

dyld: Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Applications/nmrpipe/nmrbin.mac11_64/nmrdraw.app
  Reason: no suitable image found.  Did find:
       /opt/X11/lib/libX11.6.dylib: no matching architecture in universal wrapper
       /opt/X11/lib/libX11.6.dylib: no matching architecture in universal wrapper
Abort

**Comment by 21tesla** [comment]
I am an NMR spectroscopist, too (@mrbatchelor !), and NMRDraw is an essential app. You can make a i386 specific version for your 10.3 MacOS box. Put an original libX11.6.dylib for i386 somewhere in the NMRdraw app and then use **install_name_tool** to change the location of that library from /opt/X11 to the new location.

For a while, I have been trying to build libxview so NMRDraw.app can be ran on x86_64 and arm64 machines. The libraries build now, but work still needs to be done. If there is an X11 pro on the board who would like to tackle it, the xview library source can be found at 

https://github.com/21tesla/libxview-macos

**Comment by mrbatchelor** [comment]
Thanks @21tesla . This simple-sounding workaround, is beyond my limited skill, so I'll just have to wait (and use NMRbox in the interim!)

**Comment by jeremyhu** [comment]
@mrbatchelor You can see uninstallation instructions on https://www.xquartz.org/FAQs.html

Make sure you logout after re-installing 2.7.11

**Comment by jeremyhu** [comment]
With some minor tweaks in 1a04904, I'm able to build fat intel (x86_64 + i386) libraries with currnet Xcode and the older SDK.

I just need some time to massage that to build arm64+x86_64 and then x86_64+i386 and lipo the dylibs together.

**Comment by kencu** [comment]
very nice customer support! Gold star :>

**Comment by nbriggs** [comment]
@jeremyhu Thanks for this!
