### ISSUE TITLE
Do a better job cleaning up when upgrading from older (macosforge.org) XQuartz

### ISSUE THREAD

**Issue by nbriggs** [XQuartz/XQuartz#97]
I upgraded from 2.7.11 on a system running OS X 10.11.6 to 2.8.0_rc2, and while my graphics only applications are fine (thanks for fixing the 386 client issue), attempting to start "xterm" results in
```
% xterm
X Error of failed request:  BadName (named color or font does not exist)
  Major opcode of failed request:  45 (X_OpenFont)
  Serial number of failed request:  13
  Current serial number in output stream:  25
```
I have no resources set up that would override any of the default font/color settings, and I have neither installed nor removed any fonts.

**Comment by nbriggs** [comment]
`xclock` provides an extra hint --
```
% /opt/X11/bin/xclock
Warning: Unable to load any usable ISO8859 font
Warning: Missing charsets in String to FontSet conversion
Warning: Unable to load any usable fontset
```

**Comment by jeremyhu** [comment]
xterm, xclock, xeyes all work for me... odd...

What does xlsfonts report for you?

**Comment by nbriggs** [comment]
This -- [xlsfonts.txt](https://github.com/XQuartz/XQuartz/files/6056351/xlsfonts.txt)

**Comment by nbriggs** [comment]
OK -- I deleted (actually, moved it aside) the `/opt/X11` and reinstalled XQuartz 2.8.0_rc2 and now things work.  Perhaps the installation instructions should mention that it's a good idea to uninstall the old release before installing the new one (or do they already and I'm just blind!)

I'm not sure what in the collection that was created from installing the new release over the old release caused the problem, but I've got the directory in case you have any interest (yeah, right!) in looking at what went wrong.

**Comment by nbriggs** [comment]
Looking at the old `/opt/X11` I see this oddity, in `/opt/X11/share/fonts` is
```
% ls -l
total 8
drwxr-xr-x  1901 root  wheel  64634 Feb 27 15:04 100dpi
drwxr-xr-x  1901 root  wheel  64634 Feb 27 15:04 75dpi
drwxr-xr-x    29 root  wheel    986 Feb 27 15:04 OTF
drwxr-xr-x    14 root  wheel    476 Feb 27 15:04 Speedo
drwxr-xr-x    29 root  wheel    986 Feb 27 15:04 TTF
drwxr-xr-x    63 root  wheel   2142 Feb 27 15:04 Type1
drwxr-xr-x    89 root  wheel   3026 Feb 27 15:04 cyrillic
drwxr-xr-x    37 root  wheel   1258 Feb 27 15:04 encodings
lrwxr-xr-x     1 root  wheel     20 Feb 27 23:01 fonts -> /opt/X11/share/fonts
drwxr-xr-x   416 root  wheel  14144 Feb 27 15:04 misc
drwxr-xr-x    23 root  wheel    782 Feb 27 15:04 util
```
and this seems to have resulted in things like `fc-list` producing names like `/opt/X11/share/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/fonts/100dpi/charBI08.pcf.gz: Charter:style=Bold Italic` whereas after flushing everything and reinstalling, it's producing a sane name: `/opt/X11/share/fonts/100dpi/charBI08.pcf.gz: Charter:style=Bold Italic`

**Comment by nbriggs** [comment]
... and now `xlsfonts` produces 11357 fonts instead of 3174 fonts.

**Comment by jeremyhu** [comment]
Odd.  Why the heck is that symlink there.  Thanks for the triage, I'll dig into that.

FWIW, the instructions do NOT mention that you need to uninstall the old one first because I expect that you should not need to uninstall first.

**Comment by nbriggs** [comment]
In case it helps, the previous installation was:
```
  "InstallDate" => 2017-04-27 15:15:12 +0000
  "PackageIdentifier" => "org.macosforge.xquartz.pkg"
  "PackageVersion" => "2.7.112"
  "InstallProcessName" => "Installer"
```
In the BOM from that we see
```
./opt/X11/lib/X11/fonts	120755	501/0	17	2784093359	../../share/fonts
```
but that shouldn't have caused this because the new installation is into `/opt/X11/share/fonts` and doesn't try to construct this link anymore.   If installing the old package and then installing 2.8.0 betas and then the rc2 doesn't result in this problem I would call it user error and see if it shows up anywhere else.

**Comment by mikaeleiman** [comment]
> OK -- I deleted (actually, moved it aside) the `/opt/X11` and reinstalled XQuartz 2.8.0_rc2 and now things work. Perhaps the installation instructions should mention that it's a good idea to uninstall the old release before installing the new one (or do they already and I'm just blind!)

I had the same problem, and the same workaround fixed things for me too. I didn't have the fonts symlink in share/fonts, though.

**Comment by jwise** [comment]
Yes, I reproduced this upgrading from an old version to 2.8.0_beta3 to 2.8.0_rc2 (on Mojave).  2.8.0_beta3 was fine; 2.8.0_rc2 broke.  I also moved `/opt/X11` aside, and saved it in case you have any triage that you'd like me to do on that tree.

**Comment by jeremyhu** [comment]
Thanks.  I'll try 2.7.11 -> 2.8.0_beta3 -> 2.8.0_rc2 to see if I can reproduce this hopefully later this week but more likely this weekend.

**Comment by jj1bdx** [comment]
Upgrading from 2.8.0_beta4 to 2.8.0_rc2 caused the same font error, on Catalina 10.15.7.
Removing /opt/X11 altogether and reinstalling the rc2 package revived the fonts normally.
2.8.0_beta4 was fine.

**Comment by jeremyhu** [comment]
I had 2.7.11 installed on a 10.14.6 system.  I then installed 2.8.0_beta4, logged out and back in and verified I could launch an xterm.  I then upgraded to 2.8.0_rc2, and again I could launch an xterm.

**Comment by jeremyhu** [comment]
@mikaeleiman @jwise @jj1bdx Can you identify what about your broken /opt/X11 is causing the failure?

**Comment by jeremyhu** [comment]
Ping.

Can each of you please identify what is differnet about your /opt/X11 in the bad state when upgrading to 2.8.0_rc2 vs when installing 2.8.0_rc2 cleanly?

Can anyone here provide me with concrete steps to reproduce this from a vanilla state?

**Comment by nbriggs** [comment]
I'm attaching first the summary of the difference in files present between the upgrade path and the fresh install, and then the "diff -r X11-old X11" -- which, in the fonts area, mostly shows up differences in the contents of the fonts.dir files. 
 [files-diff.txt](https://github.com/XQuartz/XQuartz/files/6113597/files-diff.txt)
[x11-diffs.txt](https://github.com/XQuartz/XQuartz/files/6113611/x11-diffs.txt)

I have not attempted to reproduce the failing upgrade (I may still have time) or to swap back to the old installation to see if it is still failing.  These were the symlinks present in the old installation relating to fonts --
```
lrwxr-xr-x  1 kristy  wheel  17 Apr 27  2017 ./X11-old/lib/X11/fonts -> ../../share/fonts
lrwxr-xr-x  1 root    wheel  20 Feb 27 23:01 ./X11-old/share/fonts/fonts -> /opt/X11/share/fonts
```
(at the time of the failure, X11-old was /opt/X11)

**Comment by jeremyhu** [comment]
If you could figure out what made /opt/X11/lib/X11/fonts  and /opt/X11/share/fonts/fonts, that would certainly help.

I'm also a bit concerned about the other reports (@jj1bdx @mikaeleiman @jwise) as at least one of them indicated that they didn't have a fonts/fonts symlink, so I'm trying to see if there are multiple issues here and figure out what might be causing them / how to fix them in the postinstall script.

**Comment by jwise** [comment]
I did not have `X11-old/share/fonts/fonts`, but I did have `X11-old/lib/X11/fonts -> ../../share/fonts`.  I can try to splice together an `X11` directory to see what component, exactly, causes the font subsystem to break, but it may take me a few days; I currently have a live session that I'm using for other stuff :)

**Comment by jeremyhu** [comment]
The `X11-old/lib/X11/fonts -> ../../share/fonts` shouldn't break anything.  The '/opt/X11/share/fonts/fonts -> /opt/X11/share/fonts' one definitely will though ... so I really want to understand what is broken about everyone else's cases and idenfity what might have caused this problem in the first place.

**Comment by mikaeleiman** [comment]
I did a diff, although I know far too little about how X11 works to have any opinion on the results. See attached.

If there are any specific commands I should run I can do that, but I don't think I'll be able to figure out what the cause is on my own.

```
mikaeleiman@Ester /opt [1]> ls -l /opt/X11-old/share/fonts
total 0
drwxr-xr-x  1901 root  wheel  60832  3 Mar 08:58 100dpi/
drwxr-xr-x  1901 root  wheel  60832  3 Mar 08:58 75dpi/
drwxr-xr-x    29 root  wheel    928  3 Mar 08:58 OTF/
drwxr-xr-x    14 root  wheel    448  3 Mar 08:58 Speedo/
drwxr-xr-x    29 root  wheel    928  3 Mar 08:58 TTF/
drwxr-xr-x    63 root  wheel   2016  3 Mar 08:58 Type1/
drwxr-xr-x    89 root  wheel   2848  3 Mar 08:58 cyrillic/
drwxr-xr-x    37 root  wheel   1184  3 Mar 08:58 encodings/
drwxr-xr-x   416 root  wheel  13312  3 Mar 08:58 misc/
drwxr-xr-x    23 root  wheel    736  3 Mar 08:58 util/
```

[mikaeleiman-diffs-X11-vs-X11-old.txt](https://github.com/XQuartz/XQuartz/files/6114143/mikaeleiman-diffs-X11-vs-X11-old.txt)

**Comment by jeremyhu** [comment]
Ok, nothing looks suspicious there, but I'm going to use this to do a better job cleaning up from an older (macosforge) XQuartz during pre-installation.

**Comment by efosler** [comment]
I have exactly this problem as well, will track what happens if I move /usr/X11 out of the way and reinstall.  I'm on Catalina (10.15.7), have had XQuartz a *long* time, installed 2.8.0_rc1 no problem; 2.8.0_rc2 will not allow me to open xterm with exactly the same error as the OP has.

**Comment by efosler** [comment]
OK, using the following command, I filtered my X11 diffs against @mikaeleiman's to help cut down on possible sources, if it helps.  X11 working now for me as well.

`diff -W 200 -y /tmp/mikaeleiman-diffs-X11-vs-X11-old.txt /tmp/x11diff | egrep -v -e '\s[<|>]\s' -e '\s<$' | expand | cut -c1-100 | sed 's/\s*$//'  > /tmp/x11diff.filt.txt`

[x11diff.filt.txt](https://github.com/XQuartz/XQuartz/files/6118506/x11diff.filt.txt)

**Comment by jeremyhu** [comment]
Ok, well I've got a change to help clean out remnants of earlier XQuartz installs during the installation, but I'm not 100% confident it will address the issue here.  I really need to be able to reproduce this.

@efosler Would you be willing to tar up your "broken" /opt/X11 directory and attach it here for me to poke at?

**Comment by efosler** [comment]
@jeremyhu Let me send it to you privately, if you don't mind (since I don't exactly know what's stored in there - it's *probably* ok, but I hate to put things up without knowing exactly what is in them).  If you google my name, you can easily find my email; drop me a note and I'll send it to you.  I should be able to look in my time machine and bring up the pre-install version as well if that is of use.

**Comment by jeremyhu** [comment]
> lrwxr-xr-x     1 root  wheel     20 Feb 27 23:01 fonts -> /opt/X11/share/fonts

@nbriggs Did you maybe start an X11 application around 11:01 on the 27th that laid down that symlink?  I can't see anything that we ever did that would have placed a symlink there.

**Comment by jeremyhu** [comment]
> I did not have `X11-old/share/fonts/fonts`, but I did have `X11-old/lib/X11/fonts -> ../../share/fonts`. I can try to splice together an `X11` directory to see what component, exactly, causes the font subsystem to break, but it may take me a few days; I currently have a live session that I'm using for other stuff :)

@jwise Did you get any fruit from that investigation/

**Comment by nbriggs** [comment]
> Did you maybe start an X11 application around 11:01 on the 27th that laid down that symlink?

I normally only run one X aware application, it doesn't depend on any fonts at all, and it doesn't know enough to do that, and I don't run it as root.

Poking around in install.log, I notice that the postinstall script generates font-related errors.   I've attached the Feb 27 parts.
[install-Feb-27.log](https://github.com/XQuartz/XQuartz/files/6125769/install-Feb-27.log)
Given the postinstall reports things like `./postinstall: font_cache is already running with PID 0.` -- perhaps what others are seeing is a failure to correctly update the cache resulting in no fonts being visible?

**Comment by jeremyhu** [comment]
@nbriggs Thanks.  I just got @efosler 's tarball and came to the same conclusion when trying to build the font cache.  The issue is that there is a stale /opt/X11/var/run/font_cache.lock

$ cat /opt/X11/var/run/font_cache.lock
0%                                                    

I'm curious how we got into such a state but will improve the font cache script to handle that better.

**Comment by jeremyhu** [comment]
Oh... the font_cache script is trying to use /usr/bin/lockfile ... which was removed from macOS a few years ago...
