### ISSUE TITLE
Feature Request: Brew cask

### ISSUE THREAD

**Issue by jeremymeyers** [XQuartz/XQuartz#98]
Would be great to be able to install/manage XQuartz through Brew. Possibly a bottle? https://docs.brew.sh/Bottles

**Comment by jeremyhu** [comment]
If that's something you're interested in, definitely reach out to homebrew.  This isn't a bug in XQuartz though, so closing.

**Comment by jeremymeyers** [comment]
Missed that this is already a thing. d'oh. https://formulae.brew.sh/cask/xquartz
